### ISSUE TITLE
快捷回复不生效

### ISSUE THREAD

**Issue by y19940406** [LLOneBot/LLOneBot#100]
QQ版本：9.9.7-21484

LLOneBot版本：3.11.0

调用LLOneBot的方式或者应用端(如postman直接调用，或NoneBot2、Koishi)：Http Post上报到Spring boot接口

BUG描述：在普通消息上报后，按照规范返回了包含reply字段的JSON串，尝试了纯字符串和数组都没有反应

复现步骤：如上所述

LLOneBot日志: 无

**Comment by linyuchen** [comment]
暂不支持快捷操作

**Comment by airdm** [comment]
> 暂不支持快捷操作

有计划去支持吗?

**Comment by linyuchen** [comment]
> > 暂不支持快捷操作
> 
> 
> 
> 有计划去支持吗?

会有

**Comment by linyuchen** [comment]
v3.19.1已支持
