### ISSUE TITLE
get_image或get_record 不返回数据？

### ISSUE THREAD

**Issue by zqwl** [LLOneBot/LLOneBot#101]
QQ版本：9.9.7

LLOneBot版本：3.11.0

BUG描述：get_image或get_record 不返回数据？

**Comment by linyuchen** [comment]
你的调用步骤呢，你这样提问会让我摸不着头脑的。

![image](https://github.com/LLOneBot/LLOneBot/assets/10002169/ebfa48c1-c3bf-4050-b98d-fd759e1c153a)

**Comment by zqwl** [comment]
sorry，我的问题，没有设置Content-Type，感谢回复
