### ISSUE TITLE
get_group_member_info 群成员管理员信息更新不及时的问题

### ISSUE THREAD

**Issue by airdm** [LLOneBot/LLOneBot#102]
LLOneBot版本：3.11

BUG描述：调用api 返回的role数据错误 可能是更新不及时

给bot管理员权限后调用get_group_member_info 查询bot管理员权限的时候role数据没有变化 目前等了1个小时没有变化.

**Comment by airdm** [comment]
从发布issue到现在 一直没更新数据.

**Comment by linyuchen** [comment]
这是个bug，在修

**Comment by linyuchen** [comment]
[v3.11.1](https://github.com/LLOneBot/LLOneBot/releases)已修复
