### ISSUE TITLE
【bug】请求发送随机视频，发送的视频文件不是mp4格式

### ISSUE THREAD

**Issue by VAHua** [LLOneBot/LLOneBot#103]
QQ版本：
9.9.7
LLOneBot版本：
3.11
调用LLOneBot的方式或者应用端(如postman直接调用，或NoneBot2、Koishi)：
nonebot2
BUG描述：
调用随机视频接口发送视频，发送出来的文件不是.mp4，而是一个php结尾的
nonebot代码：
![image](https://github.com/LLOneBot/LLOneBot/assets/129832780/3584a156-28e1-4de2-8dbd-b14e3b0ad3e4)
得到的文件：
![image](https://github.com/LLOneBot/LLOneBot/assets/129832780/8df7fb63-f1a2-407a-b6ab-9dcf779632b2)
希望的效果：
![image](https://github.com/LLOneBot/LLOneBot/assets/129832780/378b2339-b93b-4b7c-90cd-de29649d92b7)

LLOneBot日志:
2024/3/4 11:29:37 monika(2767629104): 收到反向Websocket消息 {"action":"send_msg","params":{"user_id":1186670822,"message_type":"private","message":[{"type":"video","data":{"file":"https://www.yujn.cn/api/heisis.php","cache":"0","proxy":null,"timeout":null}}]},"echo":"7"} 

2024/3/4 11:29:38 monika(2767629104): media path E:\temp\2767629104\nt_qq\nt_data\File\Ori\e33676791984d3adad33fd8998892bcc.php 

2024/3/4 11:29:40 monika(2767629104): ws 消息上报 ws://127.0.0.1:8080/onebot/v11/ws {"self_id":2767629104,"user_id":3557365244,"time":1709522980,"message_id":1709520394,"real_id":"7342345292138512614","message_type":"group","sender":{"user_id":3557365244,"nickname":"ㅤㅤㅤ","card":"","role":"member"},"raw_message":"这得让我好好想想","font":14,"sub_type":"normal","message":"这得让我好好想想","message_format":"string","post_type":"message","group_id":903860083,"raw":{"msgId":"7342345292138512614","msgRandom":"1865860942","msgSeq":"7416","cntSeq":"0","chatType":2,"msgType":2,"subMsgType":1,"sendType":0,"senderUid":"u_xuFxzOnz71doHDrB7jQFaQ","peerUid":"903860083","channelId":"","guildId":"","guildCode":"0","fromUid":"0","fromAppid":"0","msgTime":"1709522980","msgMeta":"0x","sendStatus":2,"sendRemarkName":"","sendMemberName":"","sendNickName":"ㅤㅤㅤ","guildName":"","channelName":"","elements":[{"elementType":1,"elementId":"7342345292138512613","extBufForUI":"0x","textElement":{"content":"这得让我好好想想","atType":0,"atUid":"0","atTinyId":"0","atNtUid":"","subElementType":0,"atChannelId":"0","linkInfo":null,"atRoleId":"0","atRoleColor":0,"atRoleName":"","needNotify":0},"faceElement":null,"marketFaceElement":null,"replyElement":null,"picElement":null,"pttElement":null,"videoElement":null,"grayTipElement":null,"arkElement":null,"fileElement":null,"liveGiftElement":null,"markdownElement":null,"structLongMsgElement":null,"multiForwardMsgElement":null,"giphyElement":null,"walletElement":null,"inlineKeyboardElement":null,"textGiftElement":null,"calendarElement":null,"yoloGameResultElement":null,"avRecordElement":null,"structMsgElement":null,"faceBubbleElement":null,"shareLocationElement":null,"tofuRecordElement":null,"taskTopMsgElement":null}],"records":[],"emojiLikesList":[],"commentCnt":"0","directMsgFlag":0,"directMsgMembers":[],"peerName":".","freqLimitInfo":null,"editable":false,"avatarMeta":"","avatarPendant":"","feedId":"","roleId":"0","timeStamp":"0","clientIdentityInfo":null,"isImportMsg":false,"atType":0,"roleType":0,"fromChannelRoleInfo":{"roleId":"0","name":"","color":0},"fromGuildRoleInfo":{"roleId":"0","name":"","color":0},"levelRoleInfo":{"roleId":"0","name":"","color":0},"recallTime":"0","isOnlineMsg":true,"generalFlags":"0x","clientSeq":"0","fileGroupSize":null,"foldingInfo":null,"multiTransInfo":null,"senderUin":"3557365244","peerUin":"903860083","msgAttrs":{},"anonymousExtInfo":null,"nameType":0,"avatarFlag":0,"extInfoForUI":null,"personalMedal":null,"categoryManage":0,"msgShortId":1709520394}}

**Comment by VAHua** [comment]
接口：https://www.yujn.cn/api/heisis.php

**Comment by MliKiowa** [comment]
你下载下来 发送不就行了

**Comment by VAHua** [comment]
> 随机视频每次插件那边重新下载 然后正常发送下载文件的不就行了

就是想直接通过接口发送，前面我用go-cqhttp调用了ffmpeg可以直接发送，我看llonebot也选择了ffmpeg，不知道是干嘛的呢

**Comment by MliKiowa** [comment]
> > 随机视频每次插件那边重新下载 然后正常发送下载文件的不就行了
> 
> 就是想直接通过接口发送，前面我用go-cqhttp调用了ffmpeg可以直接发送，我看llonebot也选择了ffmpeg，不知道是干嘛的呢

ffmpeg是处理语音的 你这个需要先跟进http的跳转获取视频地址 下载视频下来 然后用llonebot把视频发出去

**Comment by MliKiowa** [comment]
> 接口：https://www.yujn.cn/api/heisis.php

后缀名识别估计实现是直接根据URL拿了.php 所以发出来是PHP文件

**Comment by VAHua** [comment]
> > 接口：https://www.yujn.cn/api/heisis.php
> 
> 后缀名识别估计实现是直接根据URL拿了.php 所以发出来是PHP文件

经过测试，确实可以下载到本地，然后发送
![image](https://github.com/LLOneBot/LLOneBot/assets/129832780/43185f54-09b8-4fef-9e94-faabe8f0816d)
![image](https://github.com/LLOneBot/LLOneBot/assets/129832780/3eb01343-986a-4e31-bf30-a2da0a3c09dd)
呜呜呜，我代码全都要改了

**Comment by MliKiowa** [comment]
> > > 接口：https://www.yujn.cn/api/heisis.php
> > 
> > 
> > 后缀名识别估计实现是直接根据URL拿了.php 所以发出来是PHP文件
> 
> 经过测试，确实可以下载到本地，然后发送 ![image](https://private-user-images.githubusercontent.com/129832780/309639338-43185f54-09b8-4fef-9e94-faabe8f0816d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1MzEwMDQsIm5iZiI6MTcwOTUzMDcwNCwicGF0aCI6Ii8xMjk4MzI3ODAvMzA5NjM5MzM4LTQzMTg1ZjU0LTA5YjgtNGZlZi05ZTk0LWZhYWJlOGYwODE2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNFQwNTM4MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNDM5ZWQ3MDkwYzk5NGEwMmEzZTEyYmY1NDdiNTllNWU3ODQxNzJhZWYzMTUzYTFkZTZlZTExMmY1MzVjMTkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.83IBhzp-mLQ6g83mysCu67-RiY5c_qQxziGUbyQDYTA) ![image](https://private-user-images.githubusercontent.com/129832780/309639357-3eb01343-986a-4e31-bf30-a2da0a3c09dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1MzEwMDQsIm5iZiI6MTcwOTUzMDcwNCwicGF0aCI6Ii8xMjk4MzI3ODAvMzA5NjM5MzU3LTNlYjAxMzQzLTk4NmEtNGUzMS1iZjMwLWEyZGEwYTNjMDlkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNFQwNTM4MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYmY0YzJkYjI1MWNkYmExMzBjNDlkMTU0MGYxM2E2ZmE5ZmVmMmVkMDNjYjcxMWNkZmY1ZGYyMzY5YmU0Y2IwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4h8GC-brklhshlaSNbkSuP1tJieoUz3oeUTL4bhe7Jc) 呜呜呜，我代码全都要改了

这样我就close了

**Comment by MliKiowa** [comment]
> 这个应该是llonebot的bug，后缀名没处理好

除非你去追踪这个跳转 获取协议头 才能获取到对的后辍名 （感觉这个方案更垃圾了 还不如丢给用户

**Comment by VAHua** [comment]
> > 这个应该是llonebot的bug，后缀名没处理好
> 
> 除非你去追踪这个跳转 获取协议头 才能获取到对的后辍名 （感觉这个方案更垃圾了 还不如丢给用户 或者手动指定（更不好了

内置requests，像我这样请求[滑稽笑]

**Comment by linyuchen** [comment]
> > 这个应该是llonebot的bug，后缀名没处理好
> 
> 
> 
> 除非你去追踪这个跳转 获取协议头 才能获取到对的后辍名 （感觉这个方案更垃圾了 还不如丢给用户  或者手动指定（更不好了

会下载下来整个文件的，读取文件头可以识别

**Comment by linyuchen** [comment]
[v3.11.1](https://github.com/LLOneBot/LLOneBot/releases)已修复

**Comment by VAHua** [comment]
> [v3.11.1](https://github.com/LLOneBot/LLOneBot/releases)已修复

待我测试一下下

**Comment by VAHua** [comment]
![image](https://github.com/LLOneBot/LLOneBot/assets/129832780/58e4c5f3-31b5-441b-bfce-7ce9dec64f39)

**Comment by VAHua** [comment]
已解决，感谢大佬，大佬们牛逼！
![image](https://github.com/LLOneBot/LLOneBot/assets/129832780/86153654-19a7-45d1-bc88-852310fe76df)
![image](https://github.com/LLOneBot/LLOneBot/assets/129832780/db93ebd0-9572-46e5-8e39-4646a7c22eac)
