### ISSUE TITLE
求助：用了一个控制机器人撤回消息的插件，源码写的是seg.type == "reply"，但是我看日志没有type字段，我应该用哪个字段呢

### ISSUE THREAD

**Issue by VAHua** [LLOneBot/LLOneBot#104]
QQ版本：
9.9.7
LLOneBot版本：
3.11
调用LLOneBot的方式或者应用端(如postman直接调用，或NoneBot2、Koishi)：
nonebot2
BUG描述：
未找到回复消息时的type字段
复现步骤：
这是插件的源码：
__init_:
```
from typing import Optional

from nonebot import on_command, logger
from nonebot.adapters.onebot.v11 import ActionFailed, Bot
from nonebot.internal.params import Depends
from nonebot.permission import SUPERUSER

from .utils import reply_message_id
revoke_matcher = on_command("revoke", aliases={"撤回"}, permission=SUPERUSER)


@revoke_matcher.handle()
async def _(
        bot: Bot,
        reply_msg_id: Optional[int] = Depends(reply_message_id)
):
    try:
        if reply_msg_id is not None:
            await bot.delete_msg(message_id=reply_msg_id)
    except ActionFailed as e:
        logger.exception(e)
```

utils:
```
from typing import Optional

from nonebot.adapters.onebot.v11 import MessageEvent


def reply_message_id(event: MessageEvent) -> Optional[int]:
    message_id = None
    for seg in event.original_message:
        if seg.type == "reply":
            message_id = int(seg.data["id"])
            break
    return message_id
```

对机器人回复撤回，无反应
![image](https://github.com/LLOneBot/LLOneBot/assets/129832780/5c3e9d81-bdea-4dc7-a69e-b1c8ce2f5d39)

LLOneBot日志:
monika(2767629104): ws 消息上报 ws://127.0.0.1:8080/onebot/v11/ws {"self_id":2767629104,"user_id":1186670822,"time":1709532843,"message_id":1709526896,"real_id":"7342387654195542825","message_type":"group","sender":{"user_id":1186670822,"nickname":"青年午报","card":"","role":"admin"},"raw_message":"？","font":14,"sub_type":"normal","message":"？","message_format":"string","post_type":"message","group_id":903860083,"raw":{"msgId":"7342387654195542825","msgRandom":"1305466124","msgSeq":"7583","cntSeq":"0","chatType":2,"msgType":9,"subMsgType":33,"sendType":0,"senderUid":"u_o4mp6yEONbUxE_ePFHK7HA","peerUid":"903860083","channelId":"","guildId":"","guildCode":"0","fromUid":"0","fromAppid":"0","msgTime":"1709532843","msgMeta":"0x","sendStatus":2,"sendRemarkName":"沃德天*童哥*贞帅","sendMemberName":"","sendNickName":"青年午报","guildName":"","channelName":"","elements":[{"elementType":7,"elementId":"7342387654195542819","extBufForUI":"0x","textElement":null,"faceElement":null,"marketFaceElement":null,"replyElement":{"replayMsgId":"0","replayMsgSeq":"7582","replayMsgRootSeq":"0","replayMsgRootMsgId":"0","replayMsgRootCommentCnt":"0","sourceMsgIdInRecords":"7342387654195542826","sourceMsgText":"","sourceMsgTextElems":[{"replyAbsElemType":1,"textElemContent":"¿","faceElem":null}],"senderUid":"2767629104","senderUidStr":"u_UbNCwLm20EZaqvpgbH9nqg","replyMsgClientSeq":"0","replyMsgTime":"1709532826","replyMsgRevokeType":0,"sourceMsgIsIncPic":false,"sourceMsgExpired":false,"anonymousNickName":null,"originalMsgState":null},"picElement":null,"pttElement":null,"videoElement":null,"grayTipElement":null,"arkElement":null,"fileElement":null,"liveGiftElement":null,"markdownElement":null,"structLongMsgElement":null,"multiForwardMsgElement":null,"giphyElement":null,"walletElement":null,"inlineKeyboardElement":null,"textGiftElement":null,"calendarElement":null,"yoloGameResultElement":null,"avRecordElement":null,"structMsgElement":null,"faceBubbleElement":null,"shareLocationElement":null,"tofuRecordElement":null,"taskTopMsgElement":null},{"elementType":1,"elementId":"7342387654195542824","extBufForUI":"0x","textElement":{"content":"？","atType":0,"atUid":"0","atTinyId":"0","atNtUid":"","subElementType":0,"atChannelId":"0","linkInfo":null,"atRoleId":"0","atRoleColor":0,"atRoleName":"","needNotify":0},"faceElement":null,"marketFaceElement":null,"replyElement":null,"picElement":null,"pttElement":null,"videoElement":null,"grayTipElement":null,"arkElement":null,"fileElement":null,"liveGiftElement":null,"markdownElement":null,"structLongMsgElement":null,"multiForwardMsgElement":null,"giphyElement":null,"walletElement":null,"inlineKeyboardElement":null,"textGiftElement":null,"calendarElement":null,"yoloGameResultElement":null,"avRecordElement":null,"structMsgElement":null,"faceBubbleElement":null,"shareLocationElement":null,"tofuRecordElement":null,"taskTopMsgElement":null}],"records":[{"msgId":"7342387654195542826","msgRandom":"1691362561","msgSeq":"7582","cntSeq":"0","chatType":2,"msgType":2,"subMsgType":1,"sendType":1,"senderUid":"u_UbNCwLm20EZaqvpgbH9nqg","peerUid":"903860083","channelId":"","guildId":"","guildCode":"0","fromUid":"0","fromAppid":"0","msgTime":"1709532826","msgMeta":"0x","sendStatus":2,"sendRemarkName":"","sendMemberName":"","sendNickName":"monika","guildName":"","channelName":"","elements":[{"elementType":1,"elementId":"7342387654195542827","extBufForUI":"0x","textElement":{"content":"¿","atType":0,"atUid":"0","atTinyId":"0","atNtUid":"","subElementType":0,"atChannelId":"0","linkInfo":null,"atRoleId":"0","atRoleColor":0,"atRoleName":"","needNotify":0},"faceElement":null,"marketFaceElement":null,"replyElement":null,"picElement":null,"pttElement":null,"videoElement":null,"grayTipElement":null,"arkElement":null,"fileElement":null,"liveGiftElement":null,"markdownElement":null,"structLongMsgElement":null,"multiForwardMsgElement":null,"giphyElement":null,"walletElement":null,"inlineKeyboardElement":null,"textGiftElement":null,"calendarElement":null,"yoloGameResultElement":null,"avRecordElement":null,"structMsgElement":null,"faceBubbleElement":null,"shareLocationElement":null,"tofuRecordElement":null,"taskTopMsgElement":null}],"records":[],"emojiLikesList":[],"commentCnt":"0","directMsgFlag":0,"directMsgMembers":[],"peerName":".","freqLimitInfo":null,"editable":true,"avatarMeta":"","avatarPendant":"","feedId":"","roleId":"0","timeStamp":"0","clientIdentityInfo":null,"isImportMsg":false,"atType":0,"roleType":0,"fromChannelRoleInfo":{"roleId":"0","name":"","color":0},"fromGuildRoleInfo":{"roleId":"0","name":"","color":0},"levelRoleInfo":{"roleId":"0","name":"","color":0},"recallTime":"0","isOnlineMsg":false,"generalFlags":"0x","clientSeq":"35479","fileGroupSize":null,"foldingInfo":null,"multiTransInfo":null,"senderUin":"2767629104","peerUin":"903860083","msgAttrs":{},"anonymousExtInfo":null,"nameType":0,"avatarFlag":0,"extInfoForUI":null,"personalMedal":null,"categoryManage":0}],"emojiLikesList":[],"commentCnt":"0","directMsgFlag":0,"directMsgMembers":[],"peerName":".","freqLimitInfo":null,"editable":false,"avatarMeta":"","avatarPendant":"","feedId":"","roleId":"0","timeStamp":"0","clientIdentityInfo":null,"isImportMsg":false,"atType":6,"roleType":0,"fromChannelRoleInfo":{"roleId":"0","name":"","color":0},"fromGuildRoleInfo":{"roleId":"0","name":"","color":0},"levelRoleInfo":{"roleId":"0","name":"","color":0},"recallTime":"0","isOnlineMsg":true,"generalFlags":"0x","clientSeq":"0","fileGroupSize":null,"foldingInfo":null,"multiTransInfo":null,"senderUin":"1186670822","peerUin":"903860083","msgAttrs":{},"anonymousExtInfo":null,"nameType":0,"avatarFlag":0,"extInfoForUI":null,"personalMedal":null,"categoryManage":0,"msgShortId":1709526896}} 

不知道seg.type == "reply"应该取哪个字段，求大佬帮助
![image](https://github.com/LLOneBot/LLOneBot/assets/129832780/65ea0e46-3fe6-4da0-9c01-22b756fa5b90)

**Comment by airdm** [comment]
没有快速操作,用api吧

**Comment by linyuchen** [comment]
你贴的日志是bot那个问号的消息，你要看你发送撤回的那个消息的上报日志，正常来说是有type:reply的，建议在nb2那里打印你收到的消息，检查是否触发了nb2的command逻辑

**Comment by VAHua** [comment]
> 你贴的日志是bot那个问号的消息，你要看你发送撤回的那个消息的上报日志，正常来说是有type:reply的，建议在nb2那里打印你收到的消息，检查是否触发了nb2的command逻辑

```
03-04 16:47:58 [SUCCESS] nonebot | OneBot V11 2767629104 | [message.group.normal]: Message 1709527038 from 1186
670822@[群:903860083] '[at:qq=2767629104] 撤回'
03-04 16:47:58 [DEBUG] nonebot | Checking for matchers in priority 1...
03-04 16:47:58 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_revoke, 
lineno=10)
03-04 16:47:58 [DEBUG] nonebot | Running Matcher(type='message', module=nonebot_plugin_revoke, lineno=10)      
03-04 16:47:58 [DEBUG] nonebot | Running handler Dependent(call=_)
03-04 16:47:58 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_revoke, lineno=10) running comple
te
```
nonebot2跳过了此步骤

**Comment by VAHua** [comment]
切换了另一个插件，已解决，感谢大佬们
[nonebot-plugin-withdraw](https://github.com/noneplugin/nonebot-plugin-withdraw)
@MeetWq
也感谢各位的指导

**Comment by VAHua** [comment]
已解决

**Comment by linyuchen** [comment]
现在llonebot每次启动会清空历史消息，你要回复在llonebot启动后bot发出的消息才能拿的到reply的id
