### ISSUE TITLE
上报的群临时消息缺少"group_id"字段

### ISSUE THREAD

**Issue by zqwl** [LLOneBot/LLOneBot#107]
QQ版本：9.9.7

LLOneBot版本：3.11.0

BUG描述：
上报的群临时消息缺少"group_id"字段

另外send_private_msg能否支持下发送群临时消息

**Comment by linyuchen** [comment]
`group_id`下版本加上，为了LLOneBot能活得更久，发送临时消息不会做成release，需要自行阅读源码修改

**Comment by linyuchen** [comment]
经过测试，NTQQ的临时会话获取不了群号
