### ISSUE TITLE
上传文件 文件名有中文会变成url编码

### ISSUE THREAD

**Issue by airdm** [LLOneBot/LLOneBot#108]
LLOneBot版本：3.11
BUG描述：上传文件 文件名有中文会变成url编码
发送格式 [CQ:file,file=中文名.txt]
上传后文件名称会变成 %E4%B8%AD%E6%96%87%E5%90%8D.txt
在llonebot日志中 文件名还是中文.可是在QQ中就变成了URL编码了
希望可以添加一个额外参数可以自定义文件名

**Comment by airdm** [comment]
> 调用步骤呢

api send_group_msg 发送的 [CQ:file,file=http://127.0.0.1/中文名.txt]
文件可以上传成功 数据也没错,就是名字会错乱

**Comment by linyuchen** [comment]
> > 调用步骤呢
> 
> api send_group_msg 发送的 [CQ:file,file=http://127.0.0.1/中文名.txt] 文件可以上传成功 数据也没错,就是名字会错乱

get方法调用的吗

**Comment by airdm** [comment]
> > > 调用步骤呢
> > 
> > 
> > api send_group_msg 发送的 [CQ:file,file=http://127.0.0.1/中文名.txt] 文件可以上传成功 数据也没错,就是名字会错乱
> 
> get方法调用的吗

post方式发送的

**Comment by airdm** [comment]
在 log里面能看到 收到http请求 里面的内容是正常的中文 非url编码
