### ISSUE TITLE
HTTP服务body丢失

### ISSUE THREAD

**Issue by ysa0327** [LLOneBot/LLOneBot#109]
QQ版本：9.9.7-20811

LLOneBot版本：3.11.2

调用LLOneBot的方式或者应用端(如postman直接调用，或NoneBot2、Koishi)：Python使用requests.post调用http服务接口

BUG描述：调用http服务接口后，返回TypeError: Cannot read properties of undefined (reading 'type')，查看日志后未显示body，降级至3.11.0后正常

复现步骤：Python使用requests.post调用http服务接口，填写body data

LLOneBot日志: 收到http请求 /send_group_msg {}

**Comment by ysa0327** [comment]
3.11.2
![image](https://github.com/LLOneBot/LLOneBot/assets/49111405/43872343-9178-42ed-9024-b4ab59c43e8d)
3.11.0
![image](https://github.com/LLOneBot/LLOneBot/assets/49111405/31d30b93-c681-4021-8772-32b128842299)

**Comment by linyuchen** [comment]
无法复现你的情况，看一下你的python post的代码

**Comment by ysa0327** [comment]
貌似解决了，3.11.0以上版本需要在request的header加上application/json的Content-Type才能正常传输post的body信息

**Comment by ysa0327** [comment]
![image](https://github.com/LLOneBot/LLOneBot/assets/49111405/525db4cf-56d3-49ed-9ba2-c26125fa604d)
