### ISSUE TITLE
邀请bot进群 不会上报加群邀请事件

### ISSUE THREAD

**Issue by airdm** [LLOneBot/LLOneBot#110]
LLOneBot版本：3.11.1

BUG描述：收不到进群邀请事件

复现步骤：邀请bot进群后 不会上报加群邀请事件 但是在日志上会看到 收到群通知
这个bug只在部分bot上会出现.

LLOneBot日志:
2024/3/6 19:02:57 BOT(123456): 收到群通知 {"seq":"1709722977011111","type":1,"status":1,"group":{"groupCode":"123456","groupName":"1111111"},"user1":{"uid":"u_0Qw_AArBX15z","nickName":"BOTNAME"},"user2":{"uid":"u_UDp7Ca-wq71G","nickName":"name"},"actionUser":{"uid":"","nickName":""},"actionTime":"0","invitationExt":{"srcType":0,"groupCode":"0","waitStatus":0},"postscript":"","repeatSeqs":["170972265512345","1709722895123456"],"warningTips":"","time":1709722977919} 

2024/3/6 19:02:57 BOT(123456): nodeIKernelGroupService/getSingleScreenNotifies callback {"result":0,"errMsg":""} 

2024/3/6 19:02:58 BOT(123456): nodeIKernelGroupService/getGroupList callback {"result":0,"errMsg":"success"}

**Comment by airdm** [comment]
在QQNT界面的群通知里面 可以看到受邀的通知 并非被屏蔽或者忽略掉了.

**Comment by linyuchen** [comment]
最新版已修复
