### ISSUE TITLE
是否有相关教程

### ISSUE THREAD

**Issue by HEW666** [LLOneBot/LLOneBot#112]
小白，想看配置教程

**Comment by snowtafir** [comment]
> 小白，想看配置教程

[Installation method](https://github.com/LLOneBot/LLOneBot/blob/main/README.md)
[Connection method](https://12.onebot.dev/connect/)
[Glossary](https://12.onebot.dev/glossary/#onebot-onebot-standard)
...

**Comment by linyuchen** [comment]
https://llonebot.github.io/zh-CN/
