### ISSUE TITLE
无法上报消息 提示无法写入文件

### ISSUE THREAD

**Issue by airdm** [LLOneBot/LLOneBot#114]
LLOneBot版本：3.13.2

LLOneBot日志:
report message error:  Error: IO error: Z:\LiteLoaderQQNT\data\LLOneBot/msg_3112121212/000003.logAppend: cannot write:  ܾ    ʡ 

我尝试删除这个文件提示已被QQ占用

**Comment by airdm** [comment]
重启了一下QQNT就恢复正常了 不清楚是什么原因 顺便也升级到了3.13.3版本

**Comment by linyuchen** [comment]
QQ进程没退干净

**Comment by airdm** [comment]
刚刚出现网络波动后 QQNT自动会重新登录后 日志就提示 report message error:  Error: IO error: Z:\LiteLoaderQQNT\data\LLOneBot/msg_3123123123/000647.ldb: �Ҳ�������·����
这期间只是有网络波动导致QQ掉线了 没有其他操作.

**Comment by airdm** [comment]
重启QQ后才恢复正常. 这个问题会导致我不清楚那个QQ会出现此问题. 目前登录了很多QQNT 其中只有几个因为网络波动出现了此问题大部分因为网络波动掉线没有出现这个问题.出现此问题的QQ都会无法正常上报.

**Comment by airdm** [comment]
日志:report message error:  Error: IO error: Z:\LiteLoaderQQNT\data\LLOneBot/msg_3123123123/MANIFEST-000025Append: cannot write: ϵͳ�Ҳ���ָ�����ļ���

**Comment by linyuchen** [comment]
首先确认下你的硬盘或者容器中的空间是否满了，无法写文件了？

还有种可能，你的自动登录是否是退出QQ后重新启动，如果是这样有可能是之前的进程没有退出干净导致一直占用了数据库文件，新启动的进程就会无法使用数据库（数据库作用主要是记录消息id，避免重启后别人回复引用消息无效），可以尝试加入延迟几秒钟再重新启动。

根据你提供的信息有限，无法定位到数据库文件被占用的具体原因，不好修复。

现在v3.14.1版本新增了数据库无法使用的容错处理，只使用内存保存消息，重启后消息会丢失，无法进行引用回复，但是不会再阻塞上报流程。

**Comment by airdm** [comment]
> 首先确认下你的硬盘或者容器中的空间是否满了，无法写文件了？
> 
> 还有种可能，你的自动登录是否是退出QQ后重新启动，如果是这样有可能是之前的进程没有退出干净导致一直占用了数据库文件，新启动的进程就会无法使用数据库（数据库作用主要是记录消息id，避免重启后别人回复引用消息无效），可以尝试加入延迟几秒钟再重新启动。
> 
> 根据你提供的信息有限，无法定位到数据库文件被占用的具体原因，不好修复。
> 
> 现在v3.14.1版本新增了数据库无法使用的容错处理，只使用内存保存消息，重启后消息会丢失，无法进行引用回复，但是不会再阻塞上报流程。

空间没满  我所说的网络波动是无法连接互联网大概持续了1分钟然后恢复了,QQNT的程序是没有重启没有关的,他只是在断网的时候自己离线了,网络恢复时自己又恢复上线了.上线后接受消息和发送消息是正常的,就是LLOneBot出现了上面发的日志问题.在没出现断网问题之前LLOneBot是正常的. 你可以复现一下该问题.自己手动停用网卡等QQNT离线后再启用恢复上线后就会出现该问题.
