### ISSUE TITLE
调用接口发送随机视频，无法抛出错误

### ISSUE THREAD

**Issue by VAHua** [LLOneBot/LLOneBot#116]
QQ版本：
9.9.7
LLOneBot版本：
3.13.6
调用LLOneBot的方式或者应用端(如postman直接调用，或NoneBot2、Koishi)：
nonebot2
BUG描述：
调用接口发送随机视频，无法抛出错误
nonebot显示发送了消息
![image](https://github.com/LLOneBot/LLOneBot/assets/129832780/81d6cb28-9c5d-4313-b31b-c79e92a43271)

QQ显示：
![image](https://github.com/LLOneBot/LLOneBot/assets/129832780/373d3e14-b6ef-4768-8cc7-68469a7a27a3)

LLOneBot日志:

```
2024/3/7 18:04:55 monika(2767629104): 收到反向Websocket消息 {"action":"send_msg","params":{"user_id":1186670822,"group_id":903860083,"message_type":"group","message":[{"type":"video","data":{"file":"https://api.lolimi.cn/API/shiping/mj.php","cache":"0","proxy":null,"timeout":null}}]},"echo":"13"} 

2024/3/7 18:04:59 monika(2767629104): 发送视频 d:\Program Files\Tencent\QQNT\resources\app\LiteLoaderQQNT-main\data\LLOneBot\1724a45d-d896-4e12-b06b-36c72d31edeemj.php mj.php 

2024/3/7 18:04:59 monika(2767629104): media path E:\temp\2767629104\nt_qq\nt_data\File\Ori\d41d8cd98f00b204e9800998ecf8427e.php 

2024/3/7 18:04:59 monika(2767629104): 开始发送消息 {"chatType":2,"peerUid":"903860083"} [{"elementType":3,"elementId":"","fileElement":{"fileName":"mj.php","filePath":"E:\\temp\\2767629104\\nt_qq\\nt_data\\File\\Ori\\d41d8cd98f00b204e9800998ecf8427e.php","fileSize":"0","picHeight":1024,"picWidth":768}}] 

2024/3/7 18:04:59 monika(2767629104): 消息发送结果 {"msgId":"7417777454172073801","msgRandom":"404231106","msgSeq":"9153","cntSeq":"0","chatType":2,"msgType":3,"subMsgType":1,"sendType":1,"senderUid":"u_UbNCwLm20EZaqvpgbH9nqg","peerUid":"903860083","channelId":"","guildId":"undefined","guildCode":"0","fromUid":"0","fromAppid":"0","msgTime":"1709805899","msgMeta":"0x","sendStatus":0,"sendRemarkName":"","sendMemberName":"","sendNickName":"monika","guildName":"","channelName":"","elements":[{"elementType":3,"elementId":"7343560418886984885","extBufForUI":"0x","textElement":null,"faceElement":null,"marketFaceElement":null,"replyElement":null,"picElement":null,"pttElement":null,"videoElement":null,"grayTipElement":null,"arkElement":null,"fileElement":{"fileMd5":"d41d8cd98f00b204e9800998ecf8427e","fileName":"mj.php","filePath":"E:\\temp\\2767629104\\nt_qq\\nt_data\\File\\Ori\\d41d8cd98f00b204e9800998ecf8427e.php","fileSize":"0","picHeight":1024,"picWidth":768,"picThumbPath":{},"expireTime":"0","file10MMd5":"d41d8cd98f00b204e9800998ecf8427e","fileSha":"da39a3ee5e6b4b0d3255bfef95601890afd80709","fileSha3":"05fe405753166f125559e7c9ac558654f107c7e9","videoDuration":0,"transferStatus":5,"progress":0,"invalidState":0,"fileUuid":"undefined","fileSubId":"undefined","thumbFileSize":0,"fileBizId":null,"thumbMd5":null,"folderId":null,"fileGroupIndex":0,"fileTransType":null,"subElementType":0},"liveGiftElement":null,"markdownElement":null,"structLongMsgElement":null,"multiForwardMsgElement":null,"giphyElement":null,"walletElement":null,"inlineKeyboardElement":null,"textGiftElement":null,"calendarElement":null,"yoloGameResultElement":null,"avRecordElement":null,"structMsgElement":null,"faceBubbleElement":null,"shareLocationElement":null,"tofuRecordElement":null,"taskTopMsgElement":null}],"records":[],"emojiLikesList":[],"commentCnt":"0","directMsgFlag":0,"directMsgMembers":[],"peerName":".","freqLimitInfo":null,"editable":false,"avatarMeta":"","avatarPendant":"","feedId":"","roleId":"0","timeStamp":"0","clientIdentityInfo":null,"isImportMsg":false,"atType":0,"roleType":0,"fromChannelRoleInfo":{"roleId":"0","name":"","color":0},"fromGuildRoleInfo":{"roleId":"0","name":"","color":0},"levelRoleInfo":{"roleId":"0","name":"","color":0},"recallTime":"0","isOnlineMsg":false,"generalFlags":"0x","clientSeq":"22329","fileGroupSize":null,"foldingInfo":null,"multiTransInfo":null,"senderUin":"2767629104","peerUin":"903860083","msgAttrs":{},"anonymousExtInfo":null,"nameType":0,"avatarFlag":0,"extInfoForUI":null,"personalMedal":null,"categoryManage":0,"qqpromote":{"chatType":"child"},"msgShortId":-2147483359} 

2024/3/7 18:04:59 monika(2767629104): ws 消息上报 ws://127.0.0.1:8080/onebot/v11/ws {"status":"ok","retcode":0,"data":{"message_id":-2147483359},"message":"","wording":"","echo":"13"} 
```

**Comment by linyuchen** [comment]
新版本已修复

**Comment by VAHua** [comment]
> 新版本已修复

调用随机图片接口，如果未返回数据，机器人发送了东西，但是没有发送出去
![image](https://github.com/LLOneBot/LLOneBot/assets/129832780/fe0eb089-0dbd-4336-b419-9638d17ce4fe)

**Comment by VAHua** [comment]
顺便在此下面提个建议，发送视频的时候，现在用的是上传文件，会导致群文件杂乱，并且如果没有上传文件的权限，发不出来
![image](https://github.com/LLOneBot/LLOneBot/assets/129832780/280b78f1-f312-48b6-840f-df775f6f408a)

建议改成这样
![image](https://github.com/LLOneBot/LLOneBot/assets/129832780/38aac360-1cff-4fbb-8ff9-8f8e80194785)

**Comment by linyuchen** [comment]
> > 新版本已修复
> 
> 调用随机图片接口，如果未返回数据，机器人发送了东西，但是没有发送出去 ![image](https://private-user-images.githubusercontent.com/129832780/311128783-fe0eb089-0dbd-4336-b419-9638d17ce4fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5MjQxMDIsIm5iZiI6MTcwOTkyMzgwMiwicGF0aCI6Ii8xMjk4MzI3ODAvMzExMTI4NzgzLWZlMGViMDg5LTBkYmQtNDMzNi1iNDE5LTk2MzhkMTdjZTRmZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwOFQxODUwMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZjdjZDAwYzJhNmQ3ZjlhMzM0ZmU3MDI5NGZmYWUyODQ3OTE5YWU1ODFjNzBiNDNlMjQyYjVhM2RiYmQyZTYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IkG3VELRFThbuL5KNMlRU6vQmgQ2SMTcnP_imHEL-YQ)

[v3.13.8](https://github.com/LLOneBot/LLOneBot/releases)已修复

**Comment by VAHua** [comment]
> > 顺便在此下面提个建议，发送视频的时候，现在用的是上传文件，会导致群文件杂乱，并且如果没有上传文件的权限，发不出来 ![image](https://private-user-images.githubusercontent.com/129832780/311133750-280b78f1-f312-48b6-840f-df775f6f408a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5MjQxMDIsIm5iZiI6MTcwOTkyMzgwMiwicGF0aCI6Ii8xMjk4MzI3ODAvMzExMTMzNzUwLTI4MGI3OGYxLWYzMTItNDhiNi04NDBmLWRmNzc1ZjZmNDA4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwOFQxODUwMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNjA1NmEyMDgxYjZmMTcwYjFlNDY4NjI3NGQ3YWJlYjUxNDkxODJmMTUxY2VmMTBmNDMyMTZkMDQ4M2FiN2EyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pSCPnqKEM5GA7ppjOP-afvv6nF9oGEgUH0X0Fe7Vm2Y)
> > 建议改成这样 ![image](https://private-user-images.githubusercontent.com/129832780/311133847-38aac360-1cff-4fbb-8ff9-8f8e80194785.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5MjQxMDIsIm5iZiI6MTcwOTkyMzgwMiwicGF0aCI6Ii8xMjk4MzI3ODAvMzExMTMzODQ3LTM4YWFjMzYwLTFjZmYtNGZiYi04ZmY5LThmOGU4MDE5NDc4NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwOFQxODUwMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMDQ5ZjUxMzA0NzcwYjVhYzJhYjU5ZWMwNmYxNDg1MGQ0ODhhNDVlYzgxYmFlMGRkMWY2ODdhNDMwMTcxNWQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QssHe6LFw-vaHuxvhLKp4PetTglPZ5DbfjKpbt8mgDA)
> 
> pc上的ntqq没有发视频功能，只用发文件，无法实现和手机一样发送短视频

收到，感谢大佬
