### ISSUE TITLE
调用随机视频接口，后缀名错误的问题再次出现

### ISSUE THREAD

**Issue by VAHua** [LLOneBot/LLOneBot#117]
QQ版本：
9.9.7
LLOneBot版本：
3.13.6
调用LLOneBot的方式或者应用端(如postman直接调用，或NoneBot2、Koishi)：
nonebot2
BUG描述：
调用随机视频接口，后缀名错误的问题再次出现
复现步骤：
调用接口https://www.yujn.cn/api/jpmt.php，上传的文件后缀名错误
![image](https://github.com/LLOneBot/LLOneBot/assets/129832780/6e28e6d0-cdc6-4dac-a208-a48eaaaf34ec)

**Comment by linyuchen** [comment]
自己加个name参数指定文件名

```json
{
    "type": "video",
    "data": {
        "file": "http://xxx",
        "name": "视频.mp4"
    }
}
```

**Comment by linyuchen** [comment]
新版本已修复自动识别后缀

**Comment by VAHua** [comment]
> 新版本已修复自动识别后缀

额，那我关了
