### ISSUE TITLE
应该回复表情的时候提示无法获取URL

### ISSUE THREAD

**Issue by yzjmxy** [LLOneBot/LLOneBot#118]
QQ版本：9.9.7-21217

LLOneBot版本：LLOneBot v3.13.7

调用LLOneBot的方式或者应用端(如postman直接调用，或NoneBot2、Koishi)：NoneBot2

BUG描述：机器人在自动回复表情包的时候报错显示无法获取URl，不知道是无协议还是bug

复现步骤：

LLOneBot日志:[llonebot-2024-3-8.log](https://github.com/LLOneBot/LLOneBot/files/14534386/llonebot-2024-3-8.log)

**Comment by linyuchen** [comment]
是bug，如果是你自己写的插件，尝试把file参数改成url，`"file": "http://xxxx"`

不方便改就等下版本修复

**Comment by linyuchen** [comment]
[v3.13.8](https://github.com/LLOneBot/LLOneBot/releases)已修复

**Comment by yzjmxy** [comment]
> [v3.13.8](https://github.com/LLOneBot/LLOneBot/releases)已修复

好好好！待我试试
