### ISSUE TITLE
send_group_forward_msg相关问题

### ISSUE THREAD

**Issue by yamei333** [LLOneBot/LLOneBot#119]
QQ版本：9.9.7-21173

LLOneBot版本：3.13.7

调用LLOneBot的方式或者应用端(如postman直接调用，或NoneBot2、Koishi)：呃, 我不知道该怎么描述, 我安了插件然后通过反向ws来实现的 (实现端是C#, 项目为原先gocq-http的反向ws实现修改而来)

BUG描述：send_group_forward_msg 中自定义的名字和QQ号(显示头像用)没有起作用, 取代的是始终显示为bot的QQ名及头像

复现步骤：
参考日志, 构建了两条msg内容为
```
"name1", 10000, "msg1"
"name2", 10000, "msg2"
```
而最终收到合并转发消息显示的是Bot的名字

LLOneBot日志: 
- 发送消息
```
{"action":"send_group_forward_msg","params":{"group_id":"15873217","messages":[{"type":"node","data":{"name":"name1","uin":"10000","content":[{"type":"text","data":{"text":"msg1"}}]}},{"type":"node","data":{"name":"name2","uin":"10000","content":[{"type":"text","data":{"text":"msg2"}}]}}]},"echo":"a1561fee-a3ae-49ca-9d22-8666404206d3"} 
```
- 收到消息(上报自身发送消息)
```
{"self_id":205552607,"user_id":205552607,"time":1709889771,"message_id":-2147482859,"real_id":"7343920647764769501","message_type":"private","sender":{"user_id":205552607,"nickname":"ﾐﾐﾐ(mimimi)","card":""},"raw_message":"msg1","font":14,"sub_type":"friend","message":"msg1","message_format":"string","post_type":"message_sent"} 
```
- 详细日志
[llonebot-2024-3-8.log](https://github.com/LLOneBot/LLOneBot/files/14536212/llonebot-2024-3-8.log)

※另外还有一个问题, 如果合并转发消息里第一条是使用messageId构建的, messageId记录的消息会显示为合并转发的最后一条消息

**Comment by linyuchen** [comment]
不支持伪造name和uin
