### ISSUE TITLE
at 历史消息时，间歇性出现"获取不到引用的消息 Error: NotFound"

### ISSUE THREAD

**Issue by Container-Zero** [LLOneBot/LLOneBot#122]
QQNT版本：`9.97-21484`

LLOneBot版本：`3.13.7`

koishi版本：`4.17.2`

调用LLOneBot的方式或者应用端(如postman直接调用，或NoneBot2、Koishi)：
`Koishi->koishi-plugin-adapter-onebot->llapi->LLonebot->QQNT`

BUG描述：
at自己或他人所发送的过的消息，有概率无法获取其消息内容，日志报错无法获取message_id，同时adapter-onebot端后台也将出现如下报错：
![image](https://github.com/LLOneBot/LLOneBot/assets/20435019/ff5408a7-8eca-4462-9278-a16f3dfcba01)

复现步骤：
1.发送一些消息
2.依次at这些消息
3.有概率出现报错：获取不到引用的消息 Error: NotFound:，最终导致无法获取at的原消息内容

LLOneBot日志（at过去所发送的图片）:
[llonebot-2024-3-9.log](https://github.com/LLOneBot/LLOneBot/files/14541460/llonebot-2024-3-9.log)

日志中的用户敏感数据(仅账号、用户名称、群号)已进行替换模糊处理，其它记录数据未动，还请谅解。

**Comment by linyuchen** [comment]
[v3.13.8](https://github.com/LLOneBot/LLOneBot/releases)已修复
