### ISSUE TITLE
偶现事件重复上报

### ISSUE THREAD

**Issue by MisaLiu** [LLOneBot/LLOneBot#125]
## 运行环境
* QQNT 版本: 9.9.7-21484
* LiteLoader 版本: 1.0.3
* LLOneBot 版本: 3.13.7
* OneBot 客户端: 自制（NodeJS）

## 复现步骤
触发任意一个事件（例如加群申请）

## 期望的结果
事件只被触发一次

## 目前的结果
事件被触发了两次甚至更多

## 截图
![image](https://github.com/LLOneBot/LLOneBot/assets/62408957/bf0612a4-523e-4d5b-92cb-31973a4deb4b)

## 日志
还没有，之后尝试补上

**Comment by airdm** [comment]
我这边也出现了这类情况,比如在1点收到过加群申请 已经通过了之后 2点 3点 甚至很久之后还会收到这个人的加群申请并且flag是相同的,但是这个人没有再加过群而且一直在群里. 此类问题包括的事件有 加群请求事件 群成员增加事件 群成员减少事件

**Comment by linyuchen** [comment]
是在重启QQ之后重复收到吗

**Comment by MisaLiu** [comment]
> 是在重启QQ之后重复收到吗

不是，正常运行的时候就有可能重复收到事件

**Comment by linyuchen** [comment]
[LLOneBot v3.13.11.zip](https://github.com/LLOneBot/LLOneBot/files/14550612/LLOneBot.v3.13.11.zip)

现已将群通知存入了数据库，应该不会再次重复上报了，帮忙测试下试试看。

另外群成员变动事件现在不是走的群通知，是暴力遍历判断群人数变动的，后面会优化一下
