### ISSUE TITLE
[兼容性问题]: 在旧版QQ获取不到自己的QQ号

### ISSUE THREAD

**Issue by EatHatsuneShallots** [LLOneBot/LLOneBot#126]
QQ版本：Linux 3.2.0-16449 arm64

LLOneBot版本：v3.13.10

调用LLOneBot的方式或者应用端(如postman直接调用，或NoneBot2、Koishi)：
无需

BUG描述：
获取到的`self info`为空
配置文件的名称为`config_.json`
`get_login_info`获得的`user_id`为`null`

复现步骤：
无需任何操作

LLOneBot日志:
```
2024/3/10 13:40:32 : start get self info
2024/3/10 13:40:32 : get self info api result: {}
2024/3/10 13:40:32 : self info {"uid":"","uin":"","nick":"","online":true}
```
然后一直打印类似的日志

**Comment by MliKiowa** [comment]
你使用了choroncat吗

**Comment by EatHatsuneShallots** [comment]
> 你使用了choroncat吗

没有相关插件

**Comment by linyuchen** [comment]
v3.19.1已修复

**Comment by EatHatsuneShallots** [comment]
配置文件好像没修，文件名仍是`config_.json`
~~能考虑在获取到`Self ID`之后初始化吗()~~
而且发送群消息会提示`群xxxxxx不存在`，私聊的话就是`不能发送临时消息`

> v3.19.1已修复

**Comment by linyuchen** [comment]
> 配置文件好像没修，文件名仍是`config_.json`
> ~~能考虑在获取到`Self ID`之后初始化吗()~~
> 而且发送群消息会提示`群xxxxxx不存在`，私聊的话就是`不能发送临时消息`
> 
> > v3.19.1已修复
> 
> 

QQ版本太老了，一些api用不了和缺失，不打算兼容了，还是升级下QQ吧

**Comment by EatHatsuneShallots** [comment]
那请问至少要多少版本合适呢

> > 配置文件好像没修，文件名仍是`config_.json`
> > ~~能考虑在获取到`Self ID`之后初始化吗()~~
> > 而且发送群消息会提示`群xxxxxx不存在`，私聊的话就是`不能发送临时消息`
> > 
> > > v3.19.1已修复
> > 
> > 
> 
> QQ版本太老了，一些api用不了和缺失，不打算兼容了，还是升级下QQ吧

**Comment by linyuchen** [comment]
> 那请问至少要多少版本合适呢
> 
> > > 配置文件好像没修，文件名仍是`config_.json`
> > > ~能考虑在获取到`Self ID`之后初始化吗()~
> > > 而且发送群消息会提示`群xxxxxx不存在`，私聊的话就是`不能发送临时消息`
> > > > v3.19.1已修复
> > 
> > 
> > QQ版本太老了，一些api用不了和缺失，不打算兼容了，还是升级下QQ吧

至少版本号不清楚，至多是支持到目前最新的 22355，这里推荐用实验下来比较稳定的 21804

**Comment by airdm** [comment]
22355 会出现私聊失效的问题, 推荐先用21804
https://dldir1.qq.com/qqfile/qq/QQNT/Windows/QQ_9.9.7_240305_x64_01.exe
