### ISSUE TITLE
调用群聊全体禁言api时出现问题

### ISSUE THREAD

**Issue by B1397KB** [LLOneBot/LLOneBot#127]
QQ版本：9.9.7

LLOneBot版本：3.13.11

调用LLOneBot的方式或者应用端(如postman直接调用，或NoneBot2、Koishi)：http直接请求（浏览器）

BUG描述：调用set_group_whole_ban时enable参数无论传入true还是false都会执行禁言操作,无法解除禁言

复现步骤：直接调用 传入true或false

LLOneBot日志：

**Comment by linyuchen** [comment]
看一下你请求的参数，不要直接文字描述，最好上截图，怀疑是你提交的字符串`'true'`

**Comment by B1397KB** [comment]
http://127.0.0.1:5703/set_group_whole_ban?group_id=747413170&enable=true
http://127.0.0.1:5703/set_group_whole_ban?group_id=747413170&enable=false
{"status":"ok","retcode":0,"data":null,"message":"","wording":"","echo":null}

**Comment by linyuchen** [comment]
> http://127.0.0.1:5703/set_group_whole_ban?group_id=747413170&enable=true http://127.0.0.1:5703/set_group_whole_ban?group_id=747413170&enable=false {"status":"ok","retcode":0,"data":null,"message":"","wording":"","echo":null}

直接get方法调用会把参数识别成字符串

如果要取消禁言需要把enable置空,`/set_group_whole_ban?group_id=747413170&enable=`

**推荐所有 api 的HTTP调用方式为 POST**

**Comment by B1397KB** [comment]
{
    "status": "failed",
    "retcode": 200,
    "data": null,
    "message": "TypeError: Cannot read properties of undefined (reading 'toString')",
    "wording": "TypeError: Cannot read properties of undefined (reading 'toString')",
    "echo": null
}

post报错

**Comment by linyuchen** [comment]
> { "status": "failed", "retcode": 200, "data": null, "message": "TypeError: Cannot read properties of undefined (reading 'toString')", "wording": "TypeError: Cannot read properties of undefined (reading 'toString')", "echo": null }
> 
> post报错

附上 post 的内容，仅仅从结果无法得知错误原因

**Comment by B1397KB** [comment]
![image](https://github.com/LLOneBot/LLOneBot/assets/74302558/e30df56a-16ef-4067-a2d7-11e290978777)

**Comment by linyuchen** [comment]
![image](https://github.com/LLOneBot/LLOneBot/assets/10002169/0980f040-e01e-4b34-9c76-b6c8f97320ea)

**Comment by B1397KB** [comment]
好的 post实现成功
