### ISSUE TITLE
帮助：日志似乎不完整

### ISSUE THREAD

**Issue by VAHua** [LLOneBot/LLOneBot#129]
QQ版本：
9.9.7
LLOneBot版本：
3.14.1
调用LLOneBot的方式或者应用端(如postman直接调用，或NoneBot2、Koishi)：
nonebot2
BUG描述：
测试收到长消息，查看日志，日志不完整
复现步骤：
转发消息到机器人
LLOneBot日志:
`2024/3/15 09:20:01 monika(2767629104): ws 消息上报 ws://127.0.0.1:8080/onebot/v11/ws {"self_id":2767629104,"user_id":1186670822,"time":1710465602,"message_id":-2147461976,"real_id":-2147461976,"message_type":"group","sender":{"user_id":1186670822,"nickname":"青年午报","card":"","role":"admin"},"raw_message":"[CQ:json,data={\"app\":\"com.tencent.structmsg\"&#44;\"config\":{\"ctime\":1710465494&#44;\"forward\":1&#44;\"token\":\"50ea08d6750813c795232d303f8ce0e1\"&#44;\"type\":\"normal\"}&#44;\"extra\":{\"app_type\":1&#44;\"appid\":100497308&#44;\"uin\":2642545561}&#44;\"meta\":{\"music\":{\"action\":\"\"&#44;\"android_pkg_name\":\"\"&#44;\"app_type\":1&#44;\"appid\":100497308&#44;\"ctime\":1710465494&#44;\"desc\":\"许嵩\"&#44;\"jumpUrl\":\"https://i.y.qq.com/v8/playsong.html?songmid=001FGQba3i10mw&amp;type=0\"&#44;\"musicUrl\":\"http://ws.stream.qqmusic.qq.c...","font":14,"sub_type":"normal","message":"[CQ:json,data={\"app\":\"com.tencent.structmsg\"&#44;\"config\":{\"ctime\":1710465494&#44;\"forward\":1&#44;\"token\":\"50ea08d6750813c795232d303f8ce0e1\"&#44;\"type\":\"normal\"}&#44;\"extra\":{\"app_type\":1&#44;\"appid\":100497308&#44;\"uin\":2642545561}&#44;\"meta\":{\"music\":{\"action\":\"\"&#44;\"android_pkg_name\":\"\"&#44;\"app_type\":1&#44;\"appid\":100497308&#44;\"ctime\":1710465494&#44;\"desc\":\"许嵩\"&#44;\"jumpUrl\":\"https://i.y.qq.com/v8/playsong.html?songmid=001FGQba3i10mw&amp;type=0\"&#44;\"musicUrl\":\"http://ws.stream.qqmusic.qq.c...","message_format":"string","post_type":"message","group_id":756266094,"raw":{"msgId":"7346393817725108605","msgRandom":"810468297","msgSeq":"1100","cntSeq":"0","chatType":2,"msgType":11,"subMsgType":0,"sendType":0,"senderUid":"u_o4mp6yEONbUxE_ePFHK7HA","peerUid":"756266094","channelId":"","guildId":"","guildCode":"0","fromUid":"0","fromAppid":"0","msgTime":"1710465602","msgMeta":"0x","sendStatus":2,"sendRemarkName":"沃德天*童哥*贞帅","sendMemberName":"","sendNickName":"青年午报","guildName":"","channelName":"","elements":[{"elementType":10,"elementId":"7346393817725108603","extBufForUI":"0x","textElement":null,"faceElement":null,"marketFaceElement":null,"replyElement":null,"picElement":null,"pttElement":null,"videoElement":null,"grayTipElement":null,"arkElement":{"bytesData":"{\"app\":\"com.tencent.structmsg\",\"config\":{\"ctime\":1710465494,\"forward\":1,\"token\":\"50ea08d6750813c795232d303f8ce0e1\",\"type\":\"normal\"},\"extra\":{\"app_type\":1,\"appid\":100497308,\"uin\":2642545561},\"meta\":{\"music\":{\"action\":\"\",\"android_pkg_name\":\"\",\"app_type\":1,\"appid\":100497308,\"ctime\":1710465494,\"desc\":\"许嵩\",\"jumpUrl\":\"https://i.y.qq.com/v8/playsong.html?songmid=001FGQba3i10mw&type=0\",\"musicUrl\":\"http://ws.stream.qqmusic.qq.com/AI00000SOTba29pW1c.flac?guid=0&vkey=E753A7A07845C587D3D684BD5B171443E768EC2...","linkInfo":null,"subElementType":null},"fileElement":null,"liveGiftElement":null,"markdownElement":null,"structLongMsgElement":null,"multiForwardMsgElement":null,"giphyElement":null,"walletElement":null,"inlineKeyboardElement":null,"textGiftElement":null,"calendarElement":null,"yoloGameResultElement":null,"avRecordElement":null,"structMsgElement":null,"faceBubbleElement":null,"shareLocationElement":null,"tofuRecordElement":null,"taskTopMsgElement":null}],"records":[],"emojiLikesList":[],"commentCnt":"0","directMsgFlag":0,"directMsgMembers":[],"peerName":"api在线测试群","freqLimitInfo":null,"editable":false,"avatarMeta":"","avatarPendant":"","feedId":"","roleId":"0","timeStamp":"0","clientIdentityInfo":null,"isImportMsg":false,"atType":0,"roleType":0,"fromChannelRoleInfo":{"roleId":"0","name":"","color":0},"fromGuildRoleInfo":{"roleId":"0","name":"","color":0},"levelRoleInfo":{"roleId":"0","name":"","color":0},"recallTime":"0","isOnlineMsg":true,"generalFlags":"0x","clientSeq":"0","fileGroupSize":null,"foldingInfo":null,"multiTransInfo":null,"senderUin":"1186670822","peerUin":"756266094","msgAttrs":{},"anonymousExtInfo":null,"nameType":0,"avatarFlag":0,"extInfoForUI":null,"personalMedal":null,"categoryManage":0,"msgShortId":-2147461976}} `

消息体不完整，省略了一些东西
![image](https://github.com/LLOneBot/LLOneBot/assets/129832780/0933d560-56d8-4a24-a784-7759b3c2a523)

**Comment by linyuchen** [comment]
内容过长，日志会自动截断方便阅读
