### ISSUE TITLE
转发消息失败

### ISSUE THREAD

**Issue by airdm** [LLOneBot/LLOneBot#134]
QQ版本：21484

LLOneBot版本：3.15.1

BUG描述：
无法正常转发消息

LLOneBot日志:
2024/3/18 12:53:25 bot(123123): forward failed 转发消息失败,{"result":4,"errMsg":"Data Not Existed!"} 

2024/3/18 12:53:25 bot(123123): 发生错误 发送转发消息失败 TypeError: Cannot read properties of null (reading 'msgShortId')

**Comment by linyuchen** [comment]
日志不完整，只能猜 你是转发了已经撤回了消息

下次提问请附上触发报错的前因日志，不要只上个错误结果！

**Comment by airdm** [comment]
> 日志不完整，只能猜 你是转发了已经撤回了消息
> 
> 下次提问请附上触发报错的前因日志，不要只上个错误结果！

就少了一个post api的一条 无其他, 我用了其他方式解决了此问题,在QQNT中把自己也就是BOT自己删了重新加了一次,发现也不行,但是我发现我在post的时候他有在给转发的信息发给自己,对自己的聊天窗口中是有消息的,但是关闭窗口后又打开后转发的消息就消失了,之后重启了QQNT后恢复了. 所以具体原因不明.是否是bug 你来判断吧.
