### ISSUE TITLE
希望添加私聊文件接收

### ISSUE THREAD

**Issue by zxczaq001** [LLOneBot/LLOneBot#136]
我看文档现在私聊接收文件还是空值 希望可以快点实现
挺多功能需要 求生之路插件无法远程接收地图 原神bot无法接收以前导出的历史抽卡记录

**Comment by linyuchen** [comment]
v3.17.0 已支持, https://llonebot.github.io/zh-CN/develop/api#%E6%89%A9%E5%B1%95api
