### ISSUE TITLE
希望戳一戳消息可以提供来源和目标

### ISSUE THREAD

**Issue by WJZ-P** [LLOneBot/LLOneBot#144]
QQ版本：9.9.7-21804 (64位)

LLOneBot版本：v3.16.1

我使用的开发库是aipcqhttp，在llonebot平台下无法处理或接受戳一戳消息，在CQ平台则正常，希望可以提供支持。

**aiocqhttp 是 [OneBot](https://github.com/howmanybots/onebot) (原 [酷Q](https://cqp.cc/) 的 [CQHTTP 插件](https://cqhttp.cc/)) 的 Python SDK，采用异步 I/O，封装了 web 服务器相关的代码，支持 OneBot 的 HTTP 和反向 WebSocket 两种通信方式，让使用 Python 的开发者能方便地开发插件。**
https://github.com/nonebot/aiocqhttp

辛苦了

**Comment by lgc2333** [comment]
很抱歉，由于NTQQ架构限制，我们无法做到获取戳一戳来源，并且我们已经在文档中写的很清楚了，还请谅解
