### ISSUE TITLE
未开启调试模式时，反向ws无法上报商城表情信息

### ISSUE THREAD

**Issue by bukkumaaku** [LLOneBot/LLOneBot#150]
QQ版本：9.9.7-21804 (64位)

LLOneBot版本：3.18.3（开启了CQ码上报模式）

调用LLOneBot的方式或者应用端(如postman直接调用，或NoneBot2、Koishi)：反向websocket+php

BUG描述：在开启调试模式之前，发送商城表情反向ws无法发送相关信息，但是只有开启调试模式之后，发送商城表情才会发送相关信息

复现步骤：开关调试模式，查看日志的写入

LLOneBot日志:（这两段日志之间发送了若干商城表情，只有开启了调试模式时才写入了一份日志）
2024/3/22 10:08:34 robot(1234567890): ![image](https://github.com/LLOneBot/LLOneBot/assets/76622967/0d2bd650-2877-48c5-9273-b74ea673eb6a)
![image](https://github.com/LLOneBot/LLOneBot/assets/76622967/8e42b02b-8c39-42ba-a9e2-5c0d9035af3c)
![image](https://github.com/LLOneBot/LLOneBot/assets/76622967/ac305cc7-02f8-47a5-a36d-34f825a7f37f)
![image](https://github.com/LLOneBot/LLOneBot/assets/76622967/d71a3cb7-9704-4dd2-939c-e4bb8627b0ff)

**Comment by airdm** [comment]
调试模式 是用来开发的,如果没有开发的功能在非调试模式下肯定不会有反应的.

**Comment by airdm** [comment]
可能是因为商城表情目前不支持 是单独的一种事件所以在非调试模式下没有反应.

**Comment by bukkumaaku** [comment]
> 可能是因为商城表情目前不支持 是单独的一种事件所以在非调试模式下没有反应.

之后会有支持商城表情的打算吗？

**Comment by MliKiowa** [comment]
> > 可能是因为商城表情目前不支持 是单独的一种事件所以在非调试模式下没有反应.
> 
> 之后会有支持商城表情的打算吗？

#51

**Comment by bukkumaaku** [comment]
> > > 可能是因为商城表情目前不支持 是单独的一种事件所以在非调试模式下没有反应.
> > 
> > 
> > 之后会有支持商城表情的打算吗？
> 
> #51

好的谢谢
