### ISSUE TITLE
似乎无法发送私聊消息？

### ISSUE THREAD

**Issue by UlicaLopez** [LLOneBot/LLOneBot#151]
QQ版本：9.9.7.240305

LLOneBot版本：3.18.3

调用LLOneBot的方式或者应用端(如postman直接调用，或NoneBot2、Koishi)：onebotv11/Http(OlivOS)

BUG描述：无法发送私聊消息

复现步骤：布吉岛

LLOneBot日志:
2024/3/22 14:52:43 Mr.J(2747417707): 新消息事件HTTP上报成功: http://127.0.0.1:55001/OlivOSMsgApi/qq/onebot/default {"self_id":2747417707,"user_id":1973273744,"time":1711090363,"message_id":-2147477714,"real_id":-2147477714,"message_type":"private","sender":{"user_id":1973273744,"nickname":"密大猎犬","card":""},"raw_message":".r","font":14,"sub_type":"friend","message":".r","message_format":"string","post_type":"message"} 

2024/3/22 14:52:43 Mr.J(2747417707): receive http header token 823400 

2024/3/22 14:52:43 Mr.J(2747417707): 收到http请求 /send_msg {"message_type":"private","user_id":"1973273744","group_id":-1,"message":"[北辰海]掷骰: 1D100=39","auto_escape":false} 

2024/3/22 14:52:43 Mr.J(2747417707): nodeIKernelGroupService/getGroupList callback {"result":0,"errMsg":"success"} 

2024/3/22 14:52:43 Mr.J(2747417707): get group 108676947 members success 

2024/3/22 14:52:43 Mr.J(2747417707): get group 499727225 members success 

2024/3/22 14:52:43 Mr.J(2747417707): get group 499727225 members success 

2024/3/22 14:52:43 Mr.J(2747417707): get group 108676947 members success 

2024/3/22 14:52:43 Mr.J(2747417707): get group 217082982 members success 

2024/3/22 14:52:43 Mr.J(2747417707): get group 217082982 members success 

2024/3/22 14:52:43 Mr.J(2747417707): get group 207376210 members success 

2024/3/22 14:52:43 Mr.J(2747417707): get group 207376210 members success 

2024/3/22 14:52:43 Mr.J(2747417707): get group 524580488 members success 

2024/3/22 14:52:43 Mr.J(2747417707): get group 735374470 members success 

2024/3/22 14:52:43 Mr.J(2747417707): get group 574046083 members success 

2024/3/22 14:52:43 Mr.J(2747417707): get group 625250854 members success 

2024/3/22 14:52:43 Mr.J(2747417707): get group 524580488 members success 

2024/3/22 14:52:43 Mr.J(2747417707): get group 625250854 members success 

2024/3/22 14:52:43 Mr.J(2747417707): get group 150325517 members success 

2024/3/22 14:52:43 Mr.J(2747417707): get group 150325517 members success 

2024/3/22 14:52:43 Mr.J(2747417707): get group 574046083 members success 

2024/3/22 14:52:43 Mr.J(2747417707): get group 735374470 members success 

2024/3/22 14:52:43 Mr.J(2747417707): get group 536692056 members success 

2024/3/22 14:52:43 Mr.J(2747417707): get group 536692056 members success 

2024/3/22 14:52:43 Mr.J(2747417707): get group 598406022 members success 

2024/3/22 14:52:43 Mr.J(2747417707): get group 598406022 members success 

2024/3/22 14:52:43 Mr.J(2747417707): get group 657392762 members success 

2024/3/22 14:52:43 Mr.J(2747417707): get group 690011711 members success 

2024/3/22 14:52:43 Mr.J(2747417707): get group 657392762 members success 

2024/3/22 14:52:43 Mr.J(2747417707): get group 690011711 members success 

2024/3/22 14:52:43 Mr.J(2747417707): get group 784879755 members success 

2024/3/22 14:52:44 Mr.J(2747417707): get group 784879755 members success 

2024/3/22 14:52:44 Mr.J(2747417707): get group 920247053 members success 

2024/3/22 14:52:44 Mr.J(2747417707): get group 920247053 members success 

2024/3/22 14:52:44 Mr.J(2747417707): get group 902976307 members success 

2024/3/22 14:52:44 Mr.J(2747417707): get group 902976307 members success 

2024/3/22 14:52:44 Mr.J(2747417707): get group 878274634 members success 

2024/3/22 14:52:44 Mr.J(2747417707): get group 878274634 members success 

2024/3/22 14:52:44 Mr.J(2747417707): get group 878713739 members success 

2024/3/22 14:52:44 Mr.J(2747417707): get group 878713739 members success 

2024/3/22 14:52:44 Mr.J(2747417707): get group 909172981 members success 

2024/3/22 14:52:44 Mr.J(2747417707): get group 909172981 members success 

2024/3/22 14:52:44 Mr.J(2747417707): get group 936551301 members success 

2024/3/22 14:52:44 Mr.J(2747417707): get group 936551301 members success 

2024/3/22 14:52:44 Mr.J(2747417707): get group 936730018 members success 

2024/3/22 14:52:44 Mr.J(2747417707): get group 936730018 members success 

2024/3/22 14:52:44 Mr.J(2747417707): get group 937276700 members success 

2024/3/22 14:52:44 Mr.J(2747417707): get group 937276700 members success 

2024/3/22 14:52:44 Mr.J(2747417707): get group 939881456 members success 

2024/3/22 14:52:44 Mr.J(2747417707): get group 939881456 members success 

2024/3/22 14:52:48 Mr.J(2747417707): ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelGroupService/getGroupList ["nodeIKernelGroupService/getGroupList",{"force_update":true},null] 

2024/3/22 14:55:35 Mr.J(2747417707): 新消息事件HTTP上报成功: http://127.0.0.1:55001/OlivOSMsgApi/qq/onebot/default {"self_id":2747417707,"user_id":2747417707,"time":1711090534,"message_id":-2147477712,"real_id":-2147477712,"message_type":"private","sender":{"user_id":2747417707,"nickname":"Mr.J","card":""},"raw_message":"[CQ:file,file=llonebot-2024-3-22.log,file_id=,file_size=64592]","font":14,"sub_type":"friend","message":"[CQ:file,file=llonebot-2024-3-22.log,file_id=,file_size=64592]","message_format":"string","post_type":"message_sent","target_id":1973273744}

**Comment by linyuchen** [comment]
v3.19.1已修复
