### ISSUE TITLE
[BUG] 超过一段时常私聊会失效

### ISSUE THREAD

**Issue by airdm** [LLOneBot/LLOneBot#153]
### 系统版本

Windows 10

### QQNT 版本

9.9.8-22355

### LLOneBot 版本

3.18.3

### OneBot 客户端

自研发客户端

### 发生了什么?

每过一段时间会导致私聊失效重启QQ后才能恢复正常,
打开调试和日志开关后, 私聊无任何日志, 没有任何反应,
群聊正常, 其他事件未测试.

这个私聊会在某些特定的用户中失效
比如有 用户A 和用户B
在出现私聊失效前用户A 有跟BOT私聊说过话 用户B没有
出现私聊失效后 用户A 私聊有反应有日志 用户B没有反应也没有日志

### 如何复现

1.登录QQ
2.等待一段时间
3.私聊失效

### 期望的结果?

可以正常私聊

**Comment by airdm** [comment]
用的是最新版本的QQNT

**Comment by MisaLiu** [comment]
请提供日志（LLOneBot 以及客户端日志）以方便排查问题

**Comment by airdm** [comment]
> 请提供日志（LLOneBot 以及客户端日志）以方便排查问题

我说了 失效时没任何日志  即便打开了调试模式也没有日志

**Comment by MisaLiu** [comment]
更换账号后问题是否存在？

**Comment by airdm** [comment]
> 更换账号后问题是否存在？

你说的更换账号是什么操作?

**Comment by MisaLiu** [comment]
> > 更换账号后问题是否存在？
> 
> 你说的更换账号是什么操作?

更换 QQNT 的登录账号，有时候腾讯会风控用户发信行为，所以有时需要更换账号测试是否为框架问题

**Comment by airdm** [comment]
> > > 更换账号后问题是否存在？
> > 
> > 
> > 你说的更换账号是什么操作?
> 
> 更换 QQNT 的登录账号，有时候腾讯会风控用户发信行为，所以有时需要更换账号测试是否为框架问题

退出问题账号的QQNT后再登录后就会恢复正常. 这个问题有没有可能我用的最新版本的QQNT的原因?

**Comment by MisaLiu** [comment]
以及问一下，您示例中提到的用户 A 与 B 和 Bot 账号是否为好友关系？

**Comment by airdm** [comment]
> 以及问一下，您示例中提到的用户 A 与 B 和 Bot 账号是否为好友关系？

是好友. 因为我得BOT必须加了好友才能正常通信

**Comment by MisaLiu** [comment]
> > > > 更换账号后问题是否存在？
> > > 
> > > 
> > > 你说的更换账号是什么操作?
> > 
> > 
> > 更换 QQNT 的登录账号，有时候腾讯会风控用户发信行为，所以有时需要更换账号测试是否为框架问题
> 
> 退出问题账号的QQNT后再登录后就会恢复正常. 这个问题有没有可能我用的最新版本的QQNT的原因?

有可能的，可以的话可以尝试回退旧版本

**Comment by airdm** [comment]
> > > > > 更换账号后问题是否存在？
> > > > 
> > > > 
> > > > 你说的更换账号是什么操作?
> > > 
> > > 
> > > 更换 QQNT 的登录账号，有时候腾讯会风控用户发信行为，所以有时需要更换账号测试是否为框架问题
> > 
> > 
> > 退出问题账号的QQNT后再登录后就会恢复正常. 这个问题有没有可能我用的最新版本的QQNT的原因?
> 
> 有可能的，可以的话可以尝试回退旧版本

我现在回退到21804版本在观察.

**Comment by airdm** [comment]
到目前为止21804版本一直稳定未出现私聊无反应无日志的问题,可能是21804以上新版本的问题.

**Comment by airdm** [comment]
这几天测试了22578版本 发现一切正常 可能就是22355有问题,可以跳过22355版本进行更新
附上下载地址
https://dldir1.qq.com/qqfile/qq/QQNT/fa5373ac/QQ9.9.9.22578_x64.exe
