### ISSUE TITLE
[BUG] 群组成员减少事件和群文件上传事件

### ISSUE THREAD

**Issue by sckiyo** [LLOneBot/LLOneBot#155]
### 系统版本

Debian bookworm

### QQNT 版本

3.2.5-21713

### LLOneBot 版本

3.18.3

### OneBot 客户端

alicebot 0.10.0

### 发生了什么?

群组成员减少事件提示缺少operator_id字段。
![屏幕截图 2024-03-23 171042 - 副本](https://github.com/LLOneBot/LLOneBot/assets/118417762/c3f0d71a-0b04-4cfd-8df1-7c890ccec0ec)
data中的字段名为operate_id。另外group_id字段是字符串，好像一般应该是int？（去看了onebot11也写的int64）

群文件上传事件file字段缺少busid。
![屏幕截图 2024-03-23 201036 - 副本](https://github.com/LLOneBot/LLOneBot/assets/118417762/acfa6e1f-9a92-4c9b-ad24-0b405a76a128)
alicebot的要求是这样的：（我去看了onebot11也有busid）
![屏幕截图 2024-03-23 201839](https://github.com/LLOneBot/LLOneBot/assets/118417762/9af616a8-cbdb-4b72-8aa0-04c1bf7d54b9)

### 如何复现

有人退群，有人上传群文件

### 期望的结果?

群组成员减少事件：operate_id改为operator_id（我不知道是不是会有框架需要operate_id），group_id类型改为int。
群文件上传事件：加个busid，随便给个值都行。

**Comment by linyuchen** [comment]
v3.19.1 已添加和修正相关字段
