### ISSUE TITLE
[BUG] ChatGPT QQ Bot无法在LLOneBot使用

### ISSUE THREAD

**Issue by LovelyGuYiMeng** [LLOneBot/LLOneBot#161]
### 系统版本

windows server 2022

### QQNT 版本

9.9.8-22401

### LLOneBot 版本

3.18.4

### OneBot 客户端

Windows-quickstart-go-cqhttp-refs.tags.v2.5.2

### 发生了什么?

按理说ChatGpt QQ Bot能在LLOneBot正常使用，但是使用后报错，无法正常使用
而用go-cqhttp时可以正常使用
![QQ截图20240327150654](https://github.com/LLOneBot/LLOneBot/assets/76251800/196af609-06d1-4010-9530-0adab9806693)

### 如何复现

正常在LLOneBot使用ChatGpt QQ Bot就可以复现

### 期望的结果?

应该跟go-cqhttp时一样正常使用

**Comment by linyuchen** [comment]
llonebot设置中把消息上报格式改成cq码
![image](https://github.com/LLOneBot/LLOneBot/assets/10002169/27067baa-8c86-4d8e-8303-2fdc53d95f12)
