### ISSUE TITLE
[BUG] 群成员被踢 事件错误

### ISSUE THREAD

**Issue by aglszz** [LLOneBot/LLOneBot#164]
### 系统版本

win11

### QQNT 版本

最新版本

### LLOneBot 版本

3.20.1

### OneBot 客户端

1

### 发生了什么?

群成员被踢  事件错误   返回的主动退群   "sub_type":"leave" 

### 如何复现

随便踢个人就行

### 期望的结果?

群成员被踢  事件返回   "sub_type":"kick"

**Comment by linyuchen** [comment]
v3.20.2 已修复

**Comment by aglszz** [comment]
> v3.20.2 已修复



> v3.20.2 已修复

没办法实现非管理员是获取到踢出的吗

**Comment by linyuchen** [comment]
> > v3.20.2 已修复
> 
> 
> 
> 
> 
> 
> 
> > v3.20.2 已修复
> 
> 
> 
> 没办法实现非管理员是获取到踢出的吗 

没法 QQ没有给到具体通知

**Comment by aglszz** [comment]
> 没法 QQ没有给到具体通知

根据这个operator_id 也不能吗
![image](https://github.com/LLOneBot/LLOneBot/assets/27655065/8083b705-e844-42da-8021-5ed4c3e077cc)

**Comment by aglszz** [comment]
![image](https://github.com/LLOneBot/LLOneBot/assets/27655065/ae9539af-44ea-4f7b-a3be-c71157c4ff9c)

**Comment by linyuchen** [comment]
群通知只有管理员才能收的到
