### ISSUE TITLE
[BUG] 图片不能接收，rkey问题没修好？

### ISSUE THREAD

**Issue by A2Sumie** [LLOneBot/LLOneBot#171]
### 系统版本

Windows 11 23H2 企业版

### QQNT 版本

9.9.8-22355

### LLOneBot 版本

3.20.2 and 3.20.3

### OneBot 客户端

cq-picsearcher-bot 3.16.4

### 发生了什么?

图片接收异常，昨天3.20.2刚修时解决了表情图片收不到的问题，今日3.20.2以及更新的3.20.3下接收不了任何图片

### 如何复现

cq-picsearcher-bot 3.16.4下搜图和原图两个需要接收图片再做处理的功能完全失效

另外3.20.1的时候给客户端开发者报是表情图片失效
https://github.com/Tsuk1ko/cq-picsearcher-bot/issues/459#issuecomment-2026855724

### 期望的结果?

正常提供可以下载图片的url
或者提供一个不贴rkey的缓和选项，这样不是表情的话还是能用的

https://github.com/whitechi73/OpenShamrock/issues/236 另外这个不知道怎么（有没有）解决的也贴着

**Comment by linyuchen** [comment]
看你的描述是收不到图片上报？还是url失效？如果是url失效，贴一下失效的url

**Comment by A2Sumie** [comment]
> 看你的描述是收不到图片上报？还是url失效？如果是url失效，贴一下失效的url

URL失效，上报是正常的，浏览器打开提示invalid rkey，另作为参考设备在日本
`https://multimedia.nt.qq.com.cn/download?appid=1406&amp;fileid=CgoxNTkxMTkyNjY5EhSZNsrbn0QIwNcMw2-nA3Huw9rqfBjL2Qwg_goou93DgfyahQNQgIOYSw&amp;spec=0&amp;rkey=CAQSKAB6JWENi5LMk0kc62l8Pm3Jn1dsLZHyRLAnNmHGoZ3y_gDZPqZt-64,file_size=208075`

**Comment by linyuchen** [comment]
你改成了cq码上报，图片url中的&被转义了`&amp;`需要把`amp;`去掉

另外 appid=1406 的url不能访问在v3.20.4已修复

**Comment by A2Sumie** [comment]
> 你改成了cq码上报，图片url中的&被转义了`&amp;`需要把`amp;`去掉
> 
> 另外 appid=1406 的url不能访问在v3.20.4已修复
> 
> 这是修复后的url：https://gchat.qpic.cn/download?appid=1407&fileid=CgoxNTkxMTkyNjY5EhSZNsrbn0QIwNcMw2-nA3Huw9rqfBjL2Qwg_goou93DgfyahQNQgIOYSw&rkey=CAQSKAB6JWENi5LMk0kc62l8Pm3Jn1dsLZHyRLAnNmHGoZ3y_gDZPqZt-64&spec=0

核对了一下上报是消息段，不过3.20.4解决了
