### ISSUE TITLE
可能是我的问题的一个Issues，关于发送视频文件较大则断开ws连接

### ISSUE THREAD

**Issue by JFM6266** [LLOneBot/LLOneBot#173]
我随机解析了抖音的一些视频。例如有解析后视频文件大小为30MB、68MB、86MB、106MB、141MB不等，发现从86MB这个视频开始，大于这个就断开连接了。具体阈值是多少我不知道，因为是随机解析的。我现在也不知道问题是什么，插件那边我也问过，他们解析可以发送没问题（但他们是icqq或拉格朗），因此我也找不出来，如果确实没什么问题的话，就算了。可能是我的问题则自行忽视。
谢谢佬，麻烦了~
ps：解析插件群有建议说改解析插件，判断文件大了则直接上传文件

Q版本9.9.9-22578
LLOneBot版本3.20.6
trss崽反向ws连接
用到的解析插件：https://gitee.com/kyrzy0416/rconsole-plugin

**Comment by linyuchen** [comment]
v3.20.7已修复发大文件断开的bug，但是测试直接发太大视频是发不出去的，客户端显示发送失败红点，改成发文件比较好

**Comment by JFM6266** [comment]
好的，谢谢~
