### ISSUE TITLE
[BUG] 同时加载轻量工具箱和LLOB时 ucrtbase.dll炸掉 导致QQNT主程序崩溃

### ISSUE THREAD

**Issue by Shanshui2024** [LLOneBot/LLOneBot#176]
### 系统版本

Windows 11 Pro 23H2 22631.3374

### QQNT 版本

9.9.9-22578

### LLOneBot 版本

3.20.7

### OneBot 客户端

无

### 发生了什么?

~~可能只有我自己出了这个bug~~
在同时加载轻量工具箱和LLOB之后，QQNT主程序因**ucrtbase.dll**模块炸开而炸开
![image](https://github.com/LLOneBot/LLOneBot/assets/120782591/57c095db-9b85-435a-b257-f07139fd6c60)

### 如何复现

1.在plugins文件夹中放入轻量工具箱和LLOB
2.打开QQNT客户端（

### 期望的结果?

正常来说其不应崩溃，但经过初步测试 发现在加载这两者插件之后一定炸开
（旧版本的LLOB和轻量工具箱也曾出现过这种问题，但触发频率小很多）

**Comment by airdm** [comment]
有没有尝试过降低QQNT的版本试一下,还有就是有没有开LLONEBOT的戳一戳开关.

**Comment by Dragon-ts** [comment]
似乎和轻量工具箱没什么关系
可能和戳一戳有关，我这里在打开戳一戳约10小时后发生了上述崩溃情况

**Comment by MliKiowa** [comment]
> 似乎和轻量工具箱没什么关系 可能和戳一戳有关，我这里在打开戳一戳约10小时后发生了上述崩溃情况

戳一戳实现本来就不优雅 引发崩溃可能是内存方面的崩溃 如果有更多日志就可以进一步分析了（QQ崩溃可以在命令行和report文件夹找到更多日志

**Comment by Shanshui2024** [comment]
不好意思才看到消息（捂脸）
有关于戳一戳功能：因为我当时在研究自制正向WS框架，所以只开启了基础功能，没有开启戳一戳
关于轻量工具箱：版本号是latest（具体的忘了 在用手机 访问起来不方便）
有关于report稍后我会登录电脑端发过来

**Comment by Shanshui2024** [comment]
轻量工具箱版本：2.22.1
降低QQNT版本：这种情况其实在9.9.8版本就出现了，但是频率很低，几乎十几次才会报错一次
有关于命令行日志：
```D:\Tencent\QQNT>qq

D:\Tencent\QQNT>not mini app.
[preload] process type:
[app]module file name: D:\Tencent\QQNT\QQ.exe
[preload] hotupdate base version: 9.9.9-22578
[preload] hotupdate current version: 9.9.9-22578
[preload] install app version: 9.9.9-22578

[preload] succeeded. D:\Tencent\QQNT\resources\app\versions\9.9.9-22578\major.node
[preload] succeeded. D:\Tencent\QQNT\resources\app\versions\9.9.9-22578\wrapper.node
[preload] succeeded. D:\Tencent\QQNT\resources\app\app_launcher\launcher.node
[preload] register done. launcher.node
[LiteLoader] Start finding all plugins.
[LiteLoader] Found plugin: LLOneBot v3.20.7
[LiteLoader] Found plugin: 轻量工具箱
[LiteLoader] Found 2 plugins, start loading plugins.
init db fail ReferenceError: Cannot access 'selfInfo' before initialization
    at initDB (D:\LiteloaderQQNT\plugins\LLOB\main\main.cjs:246:11)
    at D:\LiteloaderQQNT\plugins\LLOB\main\main.cjs:259:7
    at new Promise (<anonymous>)
    at new DBUtil (D:\LiteloaderQQNT\plugins\LLOB\main\main.cjs:243:5)
    at Module.<anonymous> (D:\LiteloaderQQNT\plugins\LLOB\main\main.cjs:449:16)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at Module._load (node:internal/modules/cjs/loader:967:12)
    at u._load (node:electron/js2c/asar_bundle:2:14589)
llonebot websocket service started
[preload] register done. major.node
Error occurred in handler for 'get-remote-win': Error: No handler registered for 'get-remote-win'
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:86829)
    at Object.apply (D:\LiteloaderQQNT\plugins\LLOB\main\main.cjs:28354:24)
    at WebContents.emit (node:events:517:28)
[preload] register done. wrapper.node
llonebot init db success
[app]module file name: D:\Tencent\QQNT\QQ.exe
67803583ae7f6f4bb098d8f1bfa66f9234e92439983c98d8db47b6f46f0fa1d9
c48457ac24c9ad33bd2e0250f734116535df7e8caeb043a6d3164fd6ea65046c
038af0f860c11926f748b1c930a9ffe058de3284cf91fd12c758c238a133a631
error code v2:-8```
随后报错炸开

**Comment by xiyuesaves** [comment]
```
init db fail ReferenceError: Cannot access 'selfInfo' before initialization
at initDB (D:\LiteloaderQQNT\plugins\LLOB\main\main.cjs:246:11)
at D:\LiteloaderQQNT\plugins\LLOB\main\main.cjs:259:7
at new Promise ()
at new DBUtil (D:\LiteloaderQQNT\plugins\LLOB\main\main.cjs:243:5)
at Module. (D:\LiteloaderQQNT\plugins\LLOB\main\main.cjs:449:16)
at Module._compile (node:internal/modules/cjs/loader:1271:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
at Module.load (node:internal/modules/cjs/loader:1126:32)
at Module._load (node:internal/modules/cjs/loader:967:12)
at u._load (node:electron/js2c/asar_bundle:2:14589)
```
看起来是由于 LLOneBot 初始化数据库失败导致的错误

**Comment by Shanshui2024** [comment]
> 看起来是由于 LLOneBot 初始化数据库失败导致的错误

那怎么办（（（（

**Comment by xiyuesaves** [comment]
> > 看起来是由于 LLOneBot 初始化数据库失败导致的错误
> 
> 那怎么办（（（（

我不是 LLOneBot 的开发者，这你得等他们回复）

**Comment by Shanshui2024** [comment]
（

> > > 看起来是由于 LLOneBot 初始化数据库失败导致的错误
> > 
> > 
> > 那怎么办（（（（
> 
> 我不是 LLOneBot 的开发者，这你得等他们回复）

（

**Comment by linyuchen** [comment]
> ```
> init db fail ReferenceError: Cannot access 'selfInfo' before initialization
> at initDB (D:\LiteloaderQQNT\plugins\LLOB\main\main.cjs:246:11)
> at D:\LiteloaderQQNT\plugins\LLOB\main\main.cjs:259:7
> at new Promise ()
> at new DBUtil (D:\LiteloaderQQNT\plugins\LLOB\main\main.cjs:243:5)
> at Module. (D:\LiteloaderQQNT\plugins\LLOB\main\main.cjs:449:16)
> at Module._compile (node:internal/modules/cjs/loader:1271:14)
> at Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
> at Module.load (node:internal/modules/cjs/loader:1126:32)
> at Module._load (node:internal/modules/cjs/loader:967:12)
> at u._load (node:electron/js2c/asar_bundle:2:14589)
> ```
> 
> 看起来是由于 LLOneBot 初始化数据库失败导致的错误

这个错误不影响的，在try里面的，会继续重试的

后面这行`llonebot init db success`就是重试后成功了

**Comment by Shanshui2024** [comment]
emmm
这个日志有点长的离谱
日志：
Active code page: 65001

D:\Tencent\QQNT>qq

D:\Tencent\QQNT>not mini app.
[preload] process type:
[app]module file name: D:\Tencent\QQNT\QQ.exe
[preload] hotupdate base version: 9.9.9-22578
[preload] hotupdate current version: 9.9.9-22578
[preload] install app version: 9.9.9-22578

[preload] succeeded. D:\Tencent\QQNT\resources\app\versions\9.9.9-22578\wrapper.node
[preload] succeeded. D:\Tencent\QQNT\resources\app\app_launcher\launcher.node
[preload] succeeded. D:\Tencent\QQNT\resources\app\versions\9.9.9-22578\major.node
[preload] register done. launcher.node
[LiteLoader] Start finding all plugins.
[LiteLoader] Found plugin: LLOneBot v3.20.7
[LiteLoader] Found plugin: 轻量工具箱
[LiteLoader] Found 2 plugins, start loading plugins.
init db fail ReferenceError: Cannot access 'selfInfo' before initialization
    at initDB (D:\LiteloaderQQNT\plugins\LLOB\main\main.cjs:246:11)
    at D:\LiteloaderQQNT\plugins\LLOB\main\main.cjs:259:7
    at new Promise (<anonymous>)
    at new DBUtil (D:\LiteloaderQQNT\plugins\LLOB\main\main.cjs:243:5)
    at Module.<anonymous> (D:\LiteloaderQQNT\plugins\LLOB\main\main.cjs:449:16)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at Module._load (node:internal/modules/cjs/loader:967:12)
    at u._load (node:electron/js2c/asar_bundle:2:14589)
llonebot websocket service started
[LT]<主进程>  当前版本无法开启远程调试
[LT]<主进程>  当前环境未安装sass，动态更新样式未启用
[LT]<主进程>  轻量工具箱已加载
[LT]<撤回实例>  新的历史记录实例，目标文件 latestRecallMessage.json 实例状态 读写 切片大小 100
[preload] register done. major.node
Error occurred in handler for 'get-remote-win': Error: No handler registered for 'get-remote-win'
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:86829)
    at Object.apply (D:\LiteloaderQQNT\plugins\LLOB\main\main.cjs:28354:24)
    at WebContents.emit (node:events:517:28)
[preload] register done. wrapper.node
[LT]<主进程>  获取配置信息
[LT]<主进程>  获取配置信息
[LT]<主进程>  捕获到消息数据 1
[LT]<主进程>  捕获到消息数据 8
[LT]<主进程>  捕获到消息数据 20
[LT]<主进程>  捕获到消息数据 5
[LT]<主进程>  捕获到消息数据 1
[LT]<主进程>  捕获到消息数据 2
[LT]<主进程>  捕获到消息数据 18
[LT]<主进程>  捕获到消息数据 3
[LT]<主进程>  捕获到消息数据 15
[LT]<主进程>  捕获到消息数据 2
[LT]<主进程>  捕获到消息数据 20
[LT]<主进程>  捕获到消息数据 20
[LT]<主进程>  7354349326625003321 没有对应时间的历史切片
[LT]<主进程>  7354349326625003323 没有对应时间的历史切片
[LT]<主进程>  捕获到消息数据 20
[LT]<主进程>  7354349317516152569 没有对应时间的历史切片
[LT]<主进程>  捕获到消息数据 1
[LT]<主进程>  7353599565592472887 没有对应时间的历史切片
[LT]<主进程>  捕获到消息数据 20
[LT]<主进程>  7354349326625003321 没有对应时间的历史切片
[LT]<主进程>  7354349326625003323 没有对应时间的历史切片
[LT]<主进程>  捕获到消息数据 13
[LT]<主进程>  捕获到消息数据 13
llonebot init db success
[LT]<主进程>  捕获到消息数据 15
[LT]<主进程>  捕获到消息数据 15
[LT]<主进程>  捕获到消息数据 20
[LT]<主进程>  7354349326625003371 没有对应时间的历史切片
[LT]<主进程>  7354349326625003373 没有对应时间的历史切片
[LT]<主进程>  7354349326625003375 没有对应时间的历史切片
[LT]<主进程>  捕获到消息数据 14
[LT]<主进程>  捕获到消息数据 20
[LT]<主进程>  7354349317516152569 没有对应时间的历史切片
[LT]<主进程>  捕获到消息数据 20
[LT]<主进程>  捕获到消息数据 20
[LT]<主进程>  捕获到消息数据 20
[LT]<主进程>  捕获到消息数据 20
[LT]<主进程>  7354352839395729225 从常驻缓存中找到消息记录 {
  msgId: '7354352839395729225',
  msgRandom: '0',
  msgSeq: '105636',
  cntSeq: '0',
  chatType: 2,
  msgType: 1,
  subMsgType: 0,
  sendType: 0,
  senderUid: '',
  peerUid: '875386515',
  channelId: '',
  guildId: '',
  guildCode: '0',
  fromUid: '0',
  fromAppid: '0',
  msgTime: '0',
  msgMeta: '0x',
  sendStatus: 2,
  sendRemarkName: '',
  sendMemberName: '',
  sendNickName: '',
  guildName: '',
  channelName: '',
  elements: [],
  records: [],
  emojiLikesList: [],
  commentCnt: '0',
  directMsgFlag: 0,
  directMsgMembers: [],
  peerName: '【不存在的故事】剧情',
  freqLimitInfo: null,
  editable: false,
  avatarMeta: '',
  avatarPendant: '',
  feedId: '',
  roleId: '0',
  timeStamp: '0',
  clientIdentityInfo: null,
  isImportMsg: false,
  atType: 0,
  roleType: 0,
  fromChannelRoleInfo: { roleId: '0', name: '', color: 0 },
  fromGuildRoleInfo: { roleId: '0', name: '', color: 0 },
  levelRoleInfo: { roleId: '0', name: '', color: 0 },
  recallTime: '0',
  isOnlineMsg: false,
  generalFlags: '0x',
  clientSeq: '0',
  fileGroupSize: null,
  foldingInfo: null,
  multiTransInfo: null,
  senderUin: '0',
  peerUin: '875386515',
  msgAttrs: Map(0) {},
  anonymousExtInfo: null,
  nameType: 0,
  avatarFlag: 0,
  extInfoForUI: null,
  personalMedal: null,
  categoryManage: 0,
  msgEventInfo: null,
  lite_tools_recall: {
    operatorNick: 'SFA AND FURRY MOB killing zombies',
    operatorRemark: null,
    operatorMemRemark: null,
    origMsgSenderNick: 'SFA AND FURRY MOB killing zombies',
    origMsgSenderRemark: null,
    origMsgSenderMemRemark: null,
    recallTime: '1712318713'
  }
}
[LT]<主进程>  7354352839395729201 从常驻缓存中找到消息记录 {
  msgId: '7354352839395729201',
  msgRandom: '0',
  msgSeq: '105641',
  cntSeq: '0',
  chatType: 2,
  msgType: 1,
  subMsgType: 0,
  sendType: 0,
  senderUid: '',
  peerUid: '875386515',
  channelId: '',
  guildId: '',
  guildCode: '0',
  fromUid: '0',
  fromAppid: '0',
  msgTime: '0',
  msgMeta: '0x',
  sendStatus: 2,
  sendRemarkName: '',
  sendMemberName: '',
  sendNickName: '',
  guildName: '',
  channelName: '',
  elements: [],
  records: [],
  emojiLikesList: [],
  commentCnt: '0',
  directMsgFlag: 0,
  directMsgMembers: [],
  peerName: '【不存在的故事】剧情',
  freqLimitInfo: null,
  editable: false,
  avatarMeta: '',
  avatarPendant: '',
  feedId: '',
  roleId: '0',
  timeStamp: '0',
  clientIdentityInfo: null,
  isImportMsg: false,
  atType: 0,
  roleType: 0,
  fromChannelRoleInfo: { roleId: '0', name: '', color: 0 },
  fromGuildRoleInfo: { roleId: '0', name: '', color: 0 },
  levelRoleInfo: { roleId: '0', name: '', color: 0 },
  recallTime: '0',
  isOnlineMsg: false,
  generalFlags: '0x',
  clientSeq: '0',
  fileGroupSize: null,
  foldingInfo: null,
  multiTransInfo: null,
  senderUin: '0',
  peerUin: '875386515',
  msgAttrs: Map(0) {},
  anonymousExtInfo: null,
  nameType: 0,
  avatarFlag: 0,
  extInfoForUI: null,
  personalMedal: null,
  categoryManage: 0,
  msgEventInfo: null,
  lite_tools_recall: {
    operatorNick: 'SFA AND FURRY MOB killing zombies',
    operatorRemark: null,
    operatorMemRemark: null,
    origMsgSenderNick: 'SFA AND FURRY MOB killing zombies',
    origMsgSenderRemark: null,
    origMsgSenderMemRemark: null,
    recallTime: '1712318713'
  }
}
[LT]<主进程>  7354354163086545716 从常驻缓存中找到消息记录 {
  msgId: '7354354163086545716',
  msgRandom: '711544478',
  msgSeq: '105645',
  cntSeq: '0',
  chatType: 2,
  msgType: 2,
  subMsgType: 2,
  sendType: 0,
  senderUid: 'u_NM2uFwsJp-4EGzp01Sgc9Q',
  peerUid: '875386515',
  channelId: '',
  guildId: '',
  guildCode: '0',
  fromUid: '0',
  fromAppid: '0',
  msgTime: '1712319012',
  msgMeta: '0x',
  sendStatus: 2,
  sendRemarkName: '',
  sendMemberName: '白璃',
  sendNickName: '',
  guildName: '',
  channelName: '',
  elements: [
    {
      elementType: 2,
      elementId: '7354354163086545715',
      extBufForUI: '0x',
      textElement: null,
      faceElement: null,
      marketFaceElement: null,
      replyElement: null,
      picElement: [Object],
      pttElement: null,
      videoElement: null,
      grayTipElement: null,
      arkElement: null,
      fileElement: null,
      liveGiftElement: null,
      markdownElement: null,
      structLongMsgElement: null,
      multiForwardMsgElement: null,
      giphyElement: null,
      walletElement: null,
      inlineKeyboardElement: null,
      textGiftElement: null,
      calendarElement: null,
      yoloGameResultElement: null,
      avRecordElement: null,
      structMsgElement: null,
      faceBubbleElement: null,
      shareLocationElement: null,
      tofuRecordElement: null,
      taskTopMsgElement: null
    }
  ],
  records: [],
  emojiLikesList: [],
  commentCnt: '0',
  directMsgFlag: 0,
  directMsgMembers: [],
  peerName: '【不存在的故事】剧情',
  freqLimitInfo: null,
  editable: false,
  avatarMeta: '',
  avatarPendant: '',
  feedId: '',
  roleId: '0',
  timeStamp: '0',
  clientIdentityInfo: null,
  isImportMsg: false,
  atType: 0,
  roleType: 0,
  fromChannelRoleInfo: { roleId: '0', name: '', color: 0 },
  fromGuildRoleInfo: { roleId: '0', name: '', color: 0 },
  levelRoleInfo: { roleId: '0', name: '', color: 0 },
  recallTime: '0',
  isOnlineMsg: true,
  generalFlags: '0x',
  clientSeq: '0',
  fileGroupSize: null,
  foldingInfo: null,
  multiTransInfo: null,
  senderUin: '3057438507',
  peerUin: '875386515',
  msgAttrs: Map(3) {
    0 => {
      attrType: 0,
      attrId: '7354354163086545714',
      vasMsgInfo: [Object],
      vasPersonalInfo: null,
      groupHonor: null,
      kingHonor: null,
      publicAccountAttrs: null,
      sharedMsgInfo: null,
      gameChatSession: null,
      uinInfoAttr: null,
      longMsgAttr: null,
      robotExt: null,
      zPlanMsgInfo: null,
      qqConnectAttr: null,
      extendBusiness: null,
      sendMsgRspTransSvrInfo: null
    },
    2 => {
      attrType: 2,
      attrId: '7354354163086545712',
      vasMsgInfo: null,
      vasPersonalInfo: null,
      groupHonor: [Object],
      kingHonor: null,
      publicAccountAttrs: null,
      sharedMsgInfo: null,
      gameChatSession: null,
      uinInfoAttr: null,
      longMsgAttr: null,
      robotExt: null,
      zPlanMsgInfo: null,
      qqConnectAttr: null,
      extendBusiness: null,
      sendMsgRspTransSvrInfo: null
    },
    3 => {
      attrType: 3,
      attrId: '7354354163086545713',
      vasMsgInfo: null,
      vasPersonalInfo: null,
      groupHonor: null,
      kingHonor: [Object],
      publicAccountAttrs: null,
      sharedMsgInfo: null,
      gameChatSession: null,
      uinInfoAttr: null,
      longMsgAttr: null,
      robotExt: null,
      zPlanMsgInfo: null,
      qqConnectAttr: null,
      extendBusiness: null,
      sendMsgRspTransSvrInfo: null
    }
  },
  anonymousExtInfo: null,
  nameType: 0,
  avatarFlag: 0,
  extInfoForUI: null,
  personalMedal: null,
  categoryManage: 0,
  msgEventInfo: null,
  lite_tools_recall: {
    operatorNick: '3057438507',
    operatorRemark: null,
    operatorMemRemark: '白璃',
    origMsgSenderNick: '3057438507',
    origMsgSenderRemark: null,
    origMsgSenderMemRemark: '白璃',
    recallTime: '1712319022'
  }
}
[LT]<图片处理模块>  该消息含有图片 {
  elementType: 2,
  elementId: '7354354163086545715',
  extBufForUI: '0x',
  textElement: null,
  faceElement: null,
  marketFaceElement: null,
  replyElement: null,
  picElement: {
    picSubType: 0,
    fileName: 'F669420EBC15962206F3932B219A9E39.jpg',
    fileSize: '96104',
    picWidth: 1728,
    picHeight: 1019,
    original: false,
    md5HexStr: 'f669420ebc15962206f3932b219a9e39',
    sourcePath: 'C:\\Users\\shans\\Documents\\Tencent Files\\3381734705\\nt_qq\\nt_data\\Pic\\2024-04\\Ori\\f669420ebc15962206f3932b219a9e39.jpg',
    thumbPath: {},
    transferStatus: 0,
    progress: 0,
    picType: 1000,
    invalidState: 0,
    fileUuid: 'CgozMDU3NDM4NTA3EhQYiEJssneSr2Kz39WTEL0r15BpTxjo7gUg_wookoHCs4WrhQNQgL2jAQ',
    fileSubId: '',
    thumbFileSize: 0,
    fileBizId: null,
    downloadIndex: null,
    summary: '',
    emojiFrom: 0,
    emojiWebUrl: '',
    emojiAd: { url: '', desc: '' },
    emojiMall: { packageId: 0, emojiId: 0 },
    emojiZplan: {
      actionId: 0,
      actionName: '',
      actionType: 0,
      playerNumber: 0,
      peerUid: '0',
      bytesReserveInfo: ''
    },
    originImageMd5: 'D5636D54B500DE4397669A30EA025E8F',
    originImageUrl: '/download?appid=1407&fileid=CgozMDU3NDM4NTA3EhQYiEJssneSr2Kz39WTEL0r15BpTxjo7gUg_wookoHCs4WrhQNQgL2jAQ&spec=0',
    import_rich_media_context: null,
    isFlashPic: null,
    storeID: 1
  },
  pttElement: null,
  videoElement: null,
  grayTipElement: null,
  arkElement: null,
  fileElement: null,
  liveGiftElement: null,
  markdownElement: null,
  structLongMsgElement: null,
  multiForwardMsgElement: null,
  giphyElement: null,
  walletElement: null,
  inlineKeyboardElement: null,
  textGiftElement: null,
  calendarElement: null,
  yoloGameResultElement: null,
  avRecordElement: null,
  structMsgElement: null,
  faceBubbleElement: null,
  shareLocationElement: null,
  tofuRecordElement: null,
  taskTopMsgElement: null
}

[LT]<主进程>  捕获到主窗口
pp]module file name: D:\Tencent\QQNT\QQ.exe
67803583ae7f6f4bb098d8f1bfa66f9234e92439983c98d8db47b6f46f0fa1d9
c48457ac24c9ad33bd2e0250f734116535df7e8caeb043a6d3164fd6ea65046c
038af0f860c11926f748b1c930a9ffe058de3284cf91fd12c758c238a133a631
error code v2:-8
[LT]<主进程>  捕获到消息数据 20
[LT]<主进程>  捕获到消息数据 20
[LT]<主进程>  捕获到消息数据 14
[LT]<主进程>  捕获到消息数据 1
[LT]<主进程>  7353599565592472887 没有对应时间的历史切片
......（底下都是没有对应时间的历史切片和捕获到消息数据）

**Comment by xiyuesaves** [comment]
请注意打码隐私信息，就日志信息来看没有任何问题，是一启动就崩溃还是隔一段时间才崩溃呢？以及，可以尝试手动删除所有的撤回数据再看看

**Comment by Shanshui2024** [comment]
一启动就崩溃了
感谢大佬 我在修改轻量工具箱的缓存消息数之后便不再报错了
太感谢您了！！

**Comment by xiyuesaves** [comment]
@Shanshui2024 能麻烦测试一下这个版本的轻量工具箱还会导致qq崩溃吗？我修改了阻止撤回缓存逻辑的代码，想看看这个问题还在不在
[lite_tools_v4.zip](https://github.com/LLOneBot/LLOneBot/files/14885317/lite_tools_v4.zip)
