### ISSUE TITLE
[BUG] 群消息raw_message字段部分字符与实际消息不一致

### ISSUE THREAD

**Issue by dlcnx** [LLOneBot/LLOneBot#178]
### 系统版本

Windows 10

### QQNT 版本

9.9.7-21804

### LLOneBot 版本

3.20.7

### OneBot 客户端

dls ws1.9.25

### 发生了什么?

当群消息中包括字符"["、"]"、"&"时，llonebot返回消息中raw_message字段内容会被替换为`&#91; &#93; &amp;`
> 使用的是websocket正向连接

### 如何复现

在群聊中发送字符`[]&`
llonebot返回群消息raw_message字段内容为`&#91;&#93;&amp;`

### 期望的结果?

希望能正常返回原字符[]&

**Comment by linyuchen** [comment]
[CQ码转义](https://github.com/botuniverse/onebot-11/blob/master/message/string.md#%E8%BD%AC%E4%B9%89)

**Comment by dlcnx** [comment]
好的，谢谢
