### ISSUE TITLE
[BUG] 无法联系 ntqq api

### ISSUE THREAD

**Issue by F-fengzi** [LLOneBot/LLOneBot#181]
### 系统版本

Ubuntu 22.04

### QQNT 版本

3.2.7-22741

### LLOneBot 版本

3.22.0

### OneBot 客户端

Koishi 4.17.3 / koishi-plugin-adapter-onebot 6.5.1

### 发生了什么?

出现如下类型超时错误
`ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelGroupService/getGroupList ["nodeIKernelGroupService/getGroupList",{"force_update":true},null]`

### 如何复现

- 使用 LLOneBot 3.22.0
- 我的运行环境是 Ubuntu 22.04
- 启动或尝试发送任意消息，我尝试的是群组消息，也许可以复现

### 期望的结果?

该错误不应出现

**尝试暂时降级到 3.21.0 后成功修复过问题，但仍不稳定**

### LLOneBot 运行日志

<details>
<summary>展开</summary>

```shell
4/8/2024, 1:06:40 AM 呱(呱): self info {"uid":"呱","uin":"呱","nick":"呱","online":true} {"account":"呱","mainAccount":"","uin":"呱","uid":"呱","nickName":"","gender":0,"age":0,"faceUrl":"","a2":"","d2":"","d2key":""}

4/8/2024, 1:06:40 AM 呱(呱): llonebot pid 1002

4/8/2024, 1:06:40 AM 呱(呱): 开始连接反向ws ws://localhost:5140/onebot

4/8/2024, 1:06:40 AM 呱(呱): Trying to connect to the websocket server: ws://localhost:5140/onebot

4/8/2024, 1:06:40 AM 呱(呱): LLOneBot start

4/8/2024, 1:06:41 AM 呱(呱): {"errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":5140}

4/8/2024, 1:06:41 AM 呱(呱): The websocket connection: ws://localhost:5140/onebot closed, trying reconnecting...

4/8/2024, 1:06:41 AM 呱(呱): 反向ws断开 ws://localhost:5140/onebot

4/8/2024, 1:06:44 AM 呱(呱): Trying to connect to the websocket server: ws://localhost:5140/onebot

4/8/2024, 1:06:44 AM 呱(呱): {"errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":5140}

4/8/2024, 1:06:44 AM 呱(呱): The websocket connection: ws://localhost:5140/onebot closed, trying reconnecting...

4/8/2024, 1:06:44 AM 呱(呱): 反向ws断开 ws://localhost:5140/onebot

4/8/2024, 1:06:47 AM 呱(呱): Trying to connect to the websocket server: ws://localhost:5140/onebot

4/8/2024, 1:06:47 AM 呱(呱): ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelProfileService/getUserDetailInfoWithBizInfo ["nodeIKernelProfileService/getUserDetailInfoWithBizInfo",{"uid":"呱"},null]

4/8/2024, 1:06:47 AM 呱(呱): get self nickname failed undefined

4/8/2024, 1:06:47 AM 呱(呱): ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelGroupService/getGroupList ["nodeIKernelGroupService/getGroupList",{"force_update":true},null]

4/8/2024, 1:06:50 AM 呱(呱): Connected to the websocket server: ws://localhost:5140/onebot

4/8/2024, 1:06:50 AM 呱(呱): ws 消息上报 ws://localhost:5140/onebot {"time":1712538410,"self_id":呱,"post_type":"meta_event","meta_event_type":"lifecycle","sub_type":"connect"}

4/8/2024, 1:06:50 AM 呱(呱): 收到反向Websocket消息 {"action":"get_login_info","params":{},"echo":2}

4/8/2024, 1:06:50 AM 呱(呱): 收到反向Websocket消息 {"action":"get_guild_service_profile","params":{},"echo":4}

4/8/2024, 1:06:50 AM 呱(呱): ws 消息上报 ws://localhost:5140/onebot {"status":"failed","retcode":1404,"data":null,"message":"不支持的api get_guild_service_profile","wording":"不支持的api get_guild_service_profile","echo":4}

4/8/2024, 1:06:50 AM 呱(呱): ws 消息上报 ws://localhost:5140/onebot {"status":"ok","retcode":0,"data":{"user_id":呱,"nickname":"呱"},"message":"","wording":"","echo":2}

4/8/2024, 1:06:54 AM 呱(呱): ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelProfileService/getUserDetailInfoWithBizInfo ["nodeIKernelProfileService/getUserDetailInfoWithBizInfo",{"uid":"呱"},null]

4/8/2024, 1:06:54 AM 呱(呱): get self nickname failed undefined

4/8/2024, 1:07:00 AM 呱(呱): ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelProfileService/getUserDetailInfoWithBizInfo ["nodeIKernelProfileService/getUserDetailInfoWithBizInfo",{"uid":"呱"},null]

4/8/2024, 1:07:00 AM 呱(呱): get self nickname failed undefined

4/8/2024, 1:07:06 AM 呱(呱): ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelProfileService/getUserDetailInfoWithBizInfo ["nodeIKernelProfileService/getUserDetailInfoWithBizInfo",{"uid":"呱"},null]

4/8/2024, 1:07:06 AM 呱(呱): get self nickname failed undefined

（省略五次）

4/8/2024, 1:07:47 AM 呱(呱): ws 消息上报 ws://localhost:5140/onebot {"time":1712538467,"self_id":呱,"post_type":"meta_event","meta_event_type":"heartbeat","status":{"online":true,"good":true},"interval":60000}

4/8/2024, 1:08:22 AM 呱(呱): 收到反向Websocket消息 {"action":"send_group_msg","params":{"group_id":[呱],"message":[{"type":"text","data":{"text":"呱: \n"}},{"type":"text","data":{"text":"呱"}}]},"echo":6}

4/8/2024, 1:08:27 AM 呱(呱): ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelGroupService/getGroupList ["nodeIKernelGroupService/getGroupList",{"force_update":true},null]

4/8/2024, 1:08:27 AM 呱(呱): ws 消息上报 ws://localhost:5140/onebot {"status":"failed","retcode":1400,"data":null,"message":"群[呱]不存在","wording":"群[呱]不存在","echo":null}

4/8/2024, 1:08:35 AM 呱(呱): 收到反向Websocket消息 {"action":"send_group_msg","params":{"group_id":[呱],"message":[{"type":"text","data":{"text":"呱: \n"}},{"type":"text","data":{"text":"呱"}}]},"echo":8}

4/8/2024, 1:08:40 AM 呱(呱): ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelGroupService/getGroupList ["nodeIKernelGroupService/getGroupList",{"force_update":true},null]

4/8/2024, 1:08:40 AM 呱(呱): ws 消息上报 ws://localhost:5140/onebot {"status":"failed","retcode":1400,"data":null,"message":"群[呱]不存在","wording":"群[呱]不存在","echo":null}

（之后为无关内容）
```

</details>

### OneBot 客户端运行日志

（会显示一个ws超时，但大概和根本原因无关）

**Comment by linyuchen** [comment]
应该和 llonebot 版本无关，出现 ipc 超时大概率是 QQ 内部这个获取群列表接口自身出问题了，这种在 Linux 上出现的比较多，重启 QQ 就好了。
只是恰好你更新版本需要重启 QQ ，误以为是版本问题？

或许在后续版本会优化一下群列表的获取。

**Comment by EatHatsuneShallots** [comment]
3.2.5-20811遇到类似问题，受此影响导致无法获取群聊和好友列表，进而导致无法发送消息

**Comment by EatHatsuneShallots** [comment]
更新：我这里 QQNT 登录后加载似乎有点慢，大概需要十几秒左右（启用了 4 个包括 LLOneBot 在内的插件）
或许是因为这个导致的

**Comment by idranme** [comment]
v3.27.4 是否依然存在该问题？

**Comment by EatHatsuneShallots** [comment]
> v3.27.4 是否依然存在该问题？

使用后导致 QQ 无法启动，且日志没有任何报错
LLOneBot 日志未生成
LiteLoaderQQNT 版本 https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/commit/524035fd6ef167e943d2a828a45df9d2c241451f
<details>
<summary>QQ 日志</summary>
<pre><blockcode>
version_config_filename :/root/.config/QQ/versions/config.json
app_package_filename :/opt/QQ/resources/app/package.json
config_build_id :24402
config_base_version :3.2.9-24402
config_current_version :3.2.9-24402
app_build_version :24402
version_config_filename :/root/.config/QQ/versions/config.json
app_package_filename :/opt/QQ/resources/app/package.json
config_build_id :24402
config_base_version :3.2.9-24402
config_current_version :3.2.9-24402
app_build_version :24402
version_config_filename :/root/.config/QQ/versions/config.json
app_package_filename :/opt/QQ/resources/app/package.json
config_build_id :24402
config_base_version :3.2.9-24402
config_current_version :3.2.9-24402
app_build_version :24402
[preload] succeeded. /opt/QQ/resources/app/major.node
[preload] succeeded. /opt/QQ/resources/app/major.node
[18118:0805/103238.744364:ERROR:file_path_watcher_inotify.cc(822)] Failed to read /proc/sys/fs/inotify/max_user_watches
[18119:0805/103238.744700:ERROR:file_path_watcher_inotify.cc(822)] Failed to read /proc/sys/fs/inotify/max_user_watches
[18118:0805/103238.748822:ERROR:content_main_runner_impl.cc(500)] Failed to initialize cpuinfo
[18119:0805/103238.749271:ERROR:content_main_runner_impl.cc(500)] Failed to initialize cpuinfo
[32m[LiteLoader][0m Start finding all plugins.
[32m[LiteLoader][0m Found plugin: 演示模式 (Disabled)
[32m[LiteLoader][0m Found plugin: LLOneBot v3.27.4
[32m[LiteLoader][0m Found plugin: ESC 快捷键
[32m[LiteLoader][0m Found plugin: 插件检测更新API
[32m[LiteLoader][0m Found plugin: 定时消息
[32m[LiteLoader][0m Found plugin: Chii DevTools
[32m[LiteLoader][0m Found plugin: Euphony
[32m[LiteLoader][0m Found plugin: Fake Message
[32m[LiteLoader][0m Found plugin: JustF5
[32m[LiteLoader][0m Found plugin: 彻底禁用更新
[32m[LiteLoader][0m Found plugin: 插件列表查看
[32m[LiteLoader][0m Found plugin: 轻量工具箱
[32m[LiteLoader][0m Found plugin: 本地查看图片和视频 (Disabled)
[32m[LiteLoader][0m Found plugin: 文本转语音 (Disabled)
[32m[LiteLoader][0m Found plugin: Transitio
[32m[LiteLoader][0m Found 15 plugins, start loading plugins.
llonebot websocket service started
2024-08-05 10:32:46 starting server at localhost:41659/
[18115:0805/103247.652136:ERROR:file_path_watcher_inotify.cc(822)] Failed to read /proc/sys/fs/inotify/max_user_watches
[18115:0805/103247.711557:ERROR:zygote_host_impl_linux.cc(273)] Failed to adjust OOM score of renderer with pid 18184: 权限不够 (13)
[18115:0805/103247.778511:ERROR:udev_watcher.cc(52)] Failed to initialize a udev monitor.
[CheckUpdate] auto_send_messages > checkUpdate starts
[CheckUpdate] auto_send_messages > Use https://example.com mirror
[CheckUpdate] semVer is registered.
(node:18115) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `qq --trace-warnings ...` to show where the warning was created)
[18199:0805/103248.391173:ERROR:file_path_watcher_inotify.cc(822)] Failed to read /proc/sys/fs/inotify/max_user_watches
Xlib:  extension "DPMS" missing on display ":3.0".
Xlib:  extension "DPMS" missing on display ":3.0".
Xlib:  extension "DPMS" missing on display ":3.0".
Xlib:  extension "DPMS" missing on display ":3.0".
Xlib:  extension "DPMS" missing on display ":3.0".
Xlib:  extension "DPMS" missing on display ":3.0".
Xlib:  extension "DPMS" missing on display ":3.0".
Xlib:  extension "DPMS" missing on display ":3.0".
Warning: vkCreateInstance: Found no drivers!
Warning: vkCreateInstance failed with VK_ERROR_INCOMPATIBLE_DRIVER
    at CheckVkSuccessImpl (../../third_party/dawn/src/dawn/native/vulkan/VulkanError.cpp:101)
    at CreateVkInstance (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:493)
    at Initialize (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:379)
    at Create (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:301)
    at operator() (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:556)

Warning: eglChooseConfig returned zero configs
    at Create (../../third_party/dawn/src/dawn/native/opengl/ContextEGL.cpp:65)
    at Create (../../third_party/dawn/src/dawn/native/opengl/PhysicalDeviceGL.cpp:110)

Xlib:  extension "DPMS" missing on display ":3.0".
Xlib:  extension "DPMS" missing on display ":3.0".
Xlib:  extension "DPMS" missing on display ":3.0".
Xlib:  extension "DPMS" missing on display ":3.0".
Xlib:  extension "DPMS" missing on display ":3.0".
Xlib:  extension "DPMS" missing on display ":3.0".
Xlib:  extension "DPMS" missing on display ":3.0".
Xlib:  extension "DPMS" missing on display ":3.0".

(Thunar:22475): GLib-WARNING **: 10:36:36.869: ../../../glib/gmain.c:5802: waitid(pid:18115, pidfd=13) failed: 无效的参数 (22). See documentation of g_child_watch_source_new() for possible causes.
Xlib:  extension "DPMS" missing on display ":3.0".
Xlib:  extension "DPMS" missing on display ":3.0".
Xlib:  extension "DPMS" missing on display ":3.0".

</blockcode></pre>
</details>

**Comment by idranme** [comment]
LiteloaderQQNT 最低兼容 QQNT 25765 版本

**Comment by EatHatsuneShallots** [comment]
> LiteloaderQQNT 1.2.0 最低兼容 QQNT 25765 版本

我用的是最后一个支持旧版的 CI 版本

**Comment by idranme** [comment]
> > LiteloaderQQNT 1.2.0 最低兼容 QQNT 25765 版本
> 
> 我用的是最后一个支持旧版的 CI 版本

别用 CI 版本
