### ISSUE TITLE
需求：被动WebSocket模式下，缺少快速操作消息的处理（handle_quick_operation_async）

### ISSUE THREAD

**Issue by existed0406** [LLOneBot/LLOneBot#186]
### 系统版本

Ubuntu 22.04

### QQNT 版本

9.9.7-21217

### LLOneBot 版本

3.22.0

### OneBot 客户端

yobot_remix

### 发生了什么?

被动WebSocket模式下，无法响应handle_quick_operation_async消息
![bug1](https://github.com/LLOneBot/LLOneBot/assets/54903786/79129ed0-a5d1-4337-b31d-711e5ee59bc4)
![bug2](https://github.com/LLOneBot/LLOneBot/assets/54903786/d32c1ca6-5cc6-49bd-a7d7-0126c7c0a6b4)

### 如何复现

1.本地运行一个基于 python aiocqhttp 的服务端 WebSocket程序，如 https://github.com/eggggi/yobot_remix
2.启动LLOneBot,确认正确连接
3.发送指令（例如私聊状态下的：登录）

aiocqhttp的说明：
![aiocqhttp](https://github.com/LLOneBot/LLOneBot/assets/54903786/f6888460-7d21-4f7c-8c4e-05a390f00f94)

### 期望的结果?

期望回复对应的消息，但由于yobot_remix是基于Python的aiocqhttp库实现的，其返回的快速回复消息（格式：{reply: reply}）会被封装为{action: ".handle_quick_operation_async"}类型的消息。LLOneBot这边会因为缺少对应的ActionHandler把消息丢弃而不做处理。

### LLOneBot 运行日志

```shell
4/10/2024, 7:13:56 AM Mob(xxx): ws 消息上报 ws://172.17.0.1:9222/ws/ {"self_id":xxx,"user_id":xxx,"time":1712733236,"message_id":-2147483108,"real_id":-2147483108,"message_type":"private","sender":{"user_id":xxx,"nickname":"Mediocrity","card":""},"raw_message":"登录","font":14,"sub_type":"friend","message":[{"data":{"text":"登录"},"type":"text"}],"message_format":"array","post_type":"message"} 

4/10/2024, 7:13:56 AM Mob(xxx): 收到反向Websocket消息 {"action":".handle_quick_operation_async","params":{"self_id":xxx,"context":{"self_id":xxx,"user_id":xxx,"time":1712733236,"message_id":-2147483108,"real_id":-2147483108,"message_type":"private","font":14,"sub_type":"friend","message_format":"array","post_type":"message"},"operation":{"reply":"http://xxx:9222/login/c/#qqid=xxx&key=cEBAs2","at_sender":false}},"echo":{"seq":6}} 

4/10/2024, 7:13:56 AM Mob(xxx): ws 消息上报 ws://172.17.0.1:9222/ws/ {"status":"failed","retcode":1404,"data":null,"message":"不支持的api .handle_quick_operation_async","wording":"不支持的api .handle_quick_operation_async","echo":{"seq":6}}
```

**Comment by linyuchen** [comment]
快速操作只支持 http

**Comment by linyuchen** [comment]
v3.26.0已支持
