### ISSUE TITLE
[BUG] 退群后调用get_group_info在参数no_cache为true时依旧能获取到退群前群组信息

### ISSUE THREAD

**Issue by Fripine** [LLOneBot/LLOneBot#191]
### 系统版本

Windows 10 LTSC

### QQNT 版本

9.9.7-21804

### LLOneBot 版本

3.22.1

### OneBot 客户端

sealdice1.4.5

### 发生了什么?

退群后，依旧能获得群信息

> {"group_id":7xxxxxx,"group_name":"游xxxxxxx","member_count":3,"max_member_count":200},"message":"","wording":"","echo":"-11"} 

重启QQNT两次后变为正常

> {"status":"failed","retcode":1200,"data":null,"message":"群7xxxxxx不存在","wording":"群7xxxxxx不存在","echo":"-12"}

### 如何复现

根据OneBot 11标准，调用get_group_info，传入参数group_id，no_cache，no_cache设为true

### 期望的结果?

若no_cache为true，缓存应被清空，获取到的数据应该是这样
> {"status":"failed","retcode":1200,"data":null,"message":"群7xxxxxx不存在","wording":"群7xxxxxx不存在","echo":"-12"}

### LLOneBot 运行日志

```shell
收到正向Websocket消息 {"action":"get_group_info","params":{"group_id":7xxxxxx,"no_cache":true},"echo":"-11"} 

ws 消息上报  {"status":"ok","retcode":0,"data":{"group_id":7xxxxxx,"group_name":"游xxxxxxx","member_count":3,"max_member_count":200},"message":"","wording":"","echo":"-11"}
```

**Comment by linyuchen** [comment]
是bot主动退群吗

**Comment by Fripine** [comment]
> 是bot主动退群吗

场景：通过手机qq客户端v9.0.30.15995登录qq主动退群，看了一下代码，似乎没有支持no_cache参数？

**Comment by linyuchen** [comment]
v3.23.0已修复

**Comment by Fripine** [comment]
> v3.23.0已修复

感谢开发者所做贡献，辛苦！不过这个问题依旧存在。

复现流程：A账号使用挂载了LLOB的QQNT windows客户端登录，再使用手机QQ客户端登录A账号，在手机QQ客户端中主动退出某群后，电脑端调用get_group_list返回结果依旧存有该群信息，意味着此时get_group_list不能返回最新的群列表数据。若将QQNT windows客户端重登两次后，get_group_list返回数据将不再有该群信息，此时返回的才是最新数据。

还有一点，根据OneBot11协议，get_group_info带有no_cache参数，若该参数为true，onebot客户端返回的需是最新数据。

再次感谢开发者作出的努力！若我的表述不够清楚可以直接提问，如果由于平台缺陷无法支持该功能，可以直接Close

**Comment by linyuchen** [comment]
> > v3.23.0已修复
> 
> 感谢开发者所做贡献，辛苦！不过这个问题依旧存在。
> 
> 复现流程：A账号使用挂载了LLOB的QQNT windows客户端登录，再使用手机QQ客户端登录A账号，在手机QQ客户端中主动退出某群后，电脑端调用get_group_list返回结果依旧存有该群信息，意味着此时get_group_list不能返回最新的群列表数据。若将QQNT windows客户端重登两次后，get_group_list返回数据将不再有该群信息，此时返回的才是最新数据。
> 
> 还有一点，根据OneBot11协议，get_group_info带有no_cache参数，若该参数为true，onebot客户端返回的需是最新数据。
> 
> 再次感谢开发者作出的努力！若我的表述不够清楚可以直接提问，如果由于平台缺陷无法支持该功能，可以直接Close

情况是这样的，PC上的NTQQ自身不会同步在手机退群的，群列表依然会有（自己看界面上就是这样的），并且无法直接从列表识别这个群是退掉的，只能通关发送消息来判断，v3.23.0新增了发送群消息判断群已经退出来达到同步群列表的目的。

关于no_cache，这个字段在 ntqq 上没有用，因为强制刷新得到的结果是一样的
