### ISSUE TITLE
[BUG] ntqq api连接报错

### ISSUE THREAD

**Issue by BMC-Gordon0921** [LLOneBot/LLOneBot#192]
### 系统版本

Ubuntu 22.04

### QQNT 版本

3.2.7-22868

### LLOneBot 版本

3.22.1

### OneBot 客户端

Nonebot 2.2.1

### 发生了什么?

跟着教程配置完之后，连接bot，nonebot后端出现`<websockets> connection open`，但在启动QQ时命令行出现
`init db fail ReferenceError: Cannot access 'selfInfo' before initialization
    at initDB (/opt/LiteLoader/plugins/LLOneBot/main/main.cjs:261:11)
    at /opt/LiteLoader/plugins/LLOneBot/main/main.cjs:274:7
    at new Promise (<anonymous>)
    at new DBUtil (/opt/LiteLoader/plugins/LLOneBot/main/main.cjs:258:5)
    at Module.<anonymous> (/opt/LiteLoader/plugins/LLOneBot/main/main.cjs:464:16)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at Module._load (node:internal/modules/cjs/loader:967:12)
    at u._load (node:electron/js2c/asar_bundle:2:14589)
llonebot websocket service started
[19926:0413/200051.190630:ERROR:file_path_watcher_inotify.cc(822)] Failed to read /proc/sys/fs/inotify/max_user_watches
[19926:0413/200051.288765:ERROR:udev_watcher.cc(52)] Failed to initialize a udev monitor.
[19955:0413/200052.977595:ERROR:viz_main_impl.cc(196)] Exiting GPU process due to errors during initialization
[19962:0413/200053.677765:ERROR:command_buffer_proxy_impl.cc(127)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
Error occurred in handler for 'get-remote-win': Error: No handler registered for 'get-remote-win'
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:86829)
    at Object.apply (/opt/LiteLoader/plugins/LLOneBot/main/main.cjs:28568:24)
    at WebContents.emit (node:events:517:28)
[19926:0413/200055.929963:ERROR:object_proxy.cc(577)] Failed to call method: org.freedesktop.login1.Manager.Inhibit: object_path= /org/freedesktop/login1: org.freedesktop.DBus.Error.Spawn.ChildExited: Launch helper exited with unknown return code 1
[20001:0413/200056.253335:ERROR:gl_utils.cc(412)] [.WebGL-0x40002a6a00]GL Driver Message (OpenGL, Performance, GL_CLOSE_PATH_NV, High): GPU stall due to ReadPixels
[19962:0413/200056.518109:ERROR:command_buffer_proxy_impl.cc(319)] GPU state invalid after WaitForGetOffsetInRange.
[19926:0413/200056.524209:ERROR:gpu_process_host.cc(993)] GPU process exited unexpectedly: exit_code=11
linux-bugly: init bugly ...
[BuglyManager.cpp][InitBuglyManager][198]InitBuglyManager path: /root/.config/QQ/crash_files/
[BuglyService.cpp][registBugly][589]set signal stack
[BuglyService.cpp][registSignalHandler][520]regist native handler
[BuglyService.cpp][setParam][618]setParam, key:appVersion, value:3.2.7-22868..
linux-bugly: init bugly done.
OneBot V11 server started 0.0.0.0:3000
llonebot init db success
[BuglyManager.cpp][UploadBugly][107]!!!in UploadBugly.
[NativeCrashHandler.cpp][getCrashDetailBeanFromRecord][52]!!!! in NativeCrashHandler getCrashDetailBeanFromRecord, open file error!!!,dumpFilePath:/root/.config/QQ/crash_files/rqd_record.eup.
[NativeCrashHandler.cpp][uploadCrashEvent][331]get null crashDetailBean, return!
`
在log文件中出现：
`2024/4/13 20:01:04 3236994860(3236994860): self info {"uid":"u_S2-Q5q_Vw9vvi0LenPp9UA","uin":"3236994860","nick":"3236994860","online":true} {"account":"3236994860","mainAccount":"","uin":"3236994860","uid":"u_S2-Q5q_Vw9vvi0LenPp9UA","nickName":"","gender":0,"age":0,"faceUrl":"","a2":"","d2":"","d2key":""} 

2024/4/13 20:01:04 3236994860(3236994860): llonebot pid 19926 

2024/4/13 20:01:04 3236994860(3236994860): ??????ws ws://127.0.0.1:11038/onebot/v11/ws 

2024/4/13 20:01:04 3236994860(3236994860): Trying to connect to the websocket server: ws://127.0.0.1:11038/onebot/v11/ws 

2024/4/13 20:01:04 3236994860(3236994860): LLOneBot start 

2024/4/13 20:01:04 3236994860(3236994860): OneBot V11 server started 0.0.0.0:3000 

2024/4/13 20:01:04 3236994860(3236994860): Connected to the websocket server: ws://127.0.0.1:11038/onebot/v11/ws 

2024/4/13 20:01:04 3236994860(3236994860): ws ???? ws://127.0.0.1:11038/onebot/v11/ws {"time":1713009664,"self_id":3236994860,"post_type":"meta_event","meta_event_type":"lifecycle","sub_type":"connect"} 

2024/4/13 20:01:09 3236994860(3236994860): ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelProfileService/getUserDetailInfoWithBizInfo ["nodeIKernelProfileService/getUserDetailInfoWithBizInfo",{"uid":"u_S2-Q5q_Vw9vvi0LenPp9UA"},null] 

2024/4/13 20:01:09 3236994860(3236994860): get self nickname failed undefined 

2024/4/13 20:01:09 3236994860(3236994860): ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelGroupService/getGroupList ["nodeIKernelGroupService/getGroupList",{"force_update":true},null] 

2024/4/13 20:01:16 3236994860(3236994860): ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelProfileService/getUserDetailInfoWithBizInfo ["nodeIKernelProfileService/getUserDetailInfoWithBizInfo",{"uid":"u_S2-Q5q_Vw9vvi0LenPp9UA"},null] 

2024/4/13 20:01:16 3236994860(3236994860): get self nickname failed undefined 

2024/4/13 20:01:22 3236994860(3236994860): ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelProfileService/getUserDetailInfoWithBizInfo ["nodeIKernelProfileService/getUserDetailInfoWithBizInfo",{"uid":"u_S2-Q5q_Vw9vvi0LenPp9UA"},null] 

2024/4/13 20:01:22 3236994860(3236994860): get self nickname failed undefined 

2024/4/13 20:01:28 3236994860(3236994860): ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelProfileService/getUserDetailInfoWithBizInfo ["nodeIKernelProfileService/getUserDetailInfoWithBizInfo",{"uid":"u_S2-Q5q_Vw9vvi0LenPp9UA"},null] 

2024/4/13 20:01:28 3236994860(3236994860): get self nickname failed undefined 

2024/4/13 20:01:34 3236994860(3236994860): ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelProfileService/getUserDetailInfoWithBizInfo ["nodeIKernelProfileService/getUserDetailInfoWithBizInfo",{"uid":"u_S2-Q5q_Vw9vvi0LenPp9UA"},null] 

2024/4/13 20:01:34 3236994860(3236994860): get self nickname failed undefined 

2024/4/13 20:01:40 3236994860(3236994860): ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelProfileService/getUserDetailInfoWithBizInfo ["nodeIKernelProfileService/getUserDetailInfoWithBizInfo",{"uid":"u_S2-Q5q_Vw9vvi0LenPp9UA"},null] 

2024/4/13 20:01:40 3236994860(3236994860): get self nickname failed undefined 

2024/4/13 20:01:46 3236994860(3236994860): ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelProfileService/getUserDetailInfoWithBizInfo ["nodeIKernelProfileService/getUserDetailInfoWithBizInfo",{"uid":"u_S2-Q5q_Vw9vvi0LenPp9UA"},null] 

2024/4/13 20:01:46 3236994860(3236994860): get self nickname failed undefined 

2024/4/13 20:01:52 3236994860(3236994860): ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelProfileService/getUserDetailInfoWithBizInfo ["nodeIKernelProfileService/getUserDetailInfoWithBizInfo",{"uid":"u_S2-Q5q_Vw9vvi0LenPp9UA"},null] 

2024/4/13 20:01:52 3236994860(3236994860): get self nickname failed undefined 

2024/4/13 20:01:58 3236994860(3236994860): ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelProfileService/getUserDetailInfoWithBizInfo ["nodeIKernelProfileService/getUserDetailInfoWithBizInfo",{"uid":"u_S2-Q5q_Vw9vvi0LenPp9UA"},null] 

2024/4/13 20:01:58 3236994860(3236994860): get self nickname failed undefined 

2024/4/13 20:02:04 3236994860(3236994860): ws ???? ws://127.0.0.1:11038/onebot/v11/ws {"time":1713009724,"self_id":3236994860,"post_type":"meta_event","meta_event_type":"heartbeat","status":{"online":true,"good":true},"interval":60000} 

2024/4/13 20:02:04 3236994860(3236994860): ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelProfileService/getUserDetailInfoWithBizInfo ["nodeIKernelProfileService/getUserDetailInfoWithBizInfo",{"uid":"u_S2-Q5q_Vw9vvi0LenPp9UA"},null] 

2024/4/13 20:02:04 3236994860(3236994860): get self nickname failed undefined 
`
nonebot连接只提示 connection open 不接受qq消息，没有提示

### 如何复现

复现操作未知，但多次尝试重启QQ和bot后端均未能达成正常连接。

### 期望的结果?

在connection open后能够成功接收消息段并由nonebot响应器进行响应

### LLOneBot 运行日志

```shell
2024/4/13 20:01:04 3236994860(3236994860): self info {"uid":"u_S2-Q5q_Vw9vvi0LenPp9UA","uin":"3236994860","nick":"3236994860","online":true} {"account":"3236994860","mainAccount":"","uin":"3236994860","uid":"u_S2-Q5q_Vw9vvi0LenPp9UA","nickName":"","gender":0,"age":0,"faceUrl":"","a2":"","d2":"","d2key":""} 

2024/4/13 20:01:04 3236994860(3236994860): llonebot pid 19926 

2024/4/13 20:01:04 3236994860(3236994860): ??????ws ws://127.0.0.1:11038/onebot/v11/ws 

2024/4/13 20:01:04 3236994860(3236994860): Trying to connect to the websocket server: ws://127.0.0.1:11038/onebot/v11/ws 

2024/4/13 20:01:04 3236994860(3236994860): LLOneBot start 

2024/4/13 20:01:04 3236994860(3236994860): OneBot V11 server started 0.0.0.0:3000 

2024/4/13 20:01:04 3236994860(3236994860): Connected to the websocket server: ws://127.0.0.1:11038/onebot/v11/ws 

2024/4/13 20:01:04 3236994860(3236994860): ws ???? ws://127.0.0.1:11038/onebot/v11/ws {"time":1713009664,"self_id":3236994860,"post_type":"meta_event","meta_event_type":"lifecycle","sub_type":"connect"} 

2024/4/13 20:01:09 3236994860(3236994860): ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelProfileService/getUserDetailInfoWithBizInfo ["nodeIKernelProfileService/getUserDetailInfoWithBizInfo",{"uid":"u_S2-Q5q_Vw9vvi0LenPp9UA"},null] 

2024/4/13 20:01:09 3236994860(3236994860): get self nickname failed undefined 

2024/4/13 20:01:09 3236994860(3236994860): ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelGroupService/getGroupList ["nodeIKernelGroupService/getGroupList",{"force_update":true},null] 

2024/4/13 20:01:16 3236994860(3236994860): ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelProfileService/getUserDetailInfoWithBizInfo ["nodeIKernelProfileService/getUserDetailInfoWithBizInfo",{"uid":"u_S2-Q5q_Vw9vvi0LenPp9UA"},null] 

2024/4/13 20:01:16 3236994860(3236994860): get self nickname failed undefined 

2024/4/13 20:01:22 3236994860(3236994860): ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelProfileService/getUserDetailInfoWithBizInfo ["nodeIKernelProfileService/getUserDetailInfoWithBizInfo",{"uid":"u_S2-Q5q_Vw9vvi0LenPp9UA"},null] 

2024/4/13 20:01:22 3236994860(3236994860): get self nickname failed undefined 

2024/4/13 20:01:28 3236994860(3236994860): ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelProfileService/getUserDetailInfoWithBizInfo ["nodeIKernelProfileService/getUserDetailInfoWithBizInfo",{"uid":"u_S2-Q5q_Vw9vvi0LenPp9UA"},null] 

2024/4/13 20:01:28 3236994860(3236994860): get self nickname failed undefined 

2024/4/13 20:01:34 3236994860(3236994860): ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelProfileService/getUserDetailInfoWithBizInfo ["nodeIKernelProfileService/getUserDetailInfoWithBizInfo",{"uid":"u_S2-Q5q_Vw9vvi0LenPp9UA"},null] 

2024/4/13 20:01:34 3236994860(3236994860): get self nickname failed undefined 

2024/4/13 20:01:40 3236994860(3236994860): ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelProfileService/getUserDetailInfoWithBizInfo ["nodeIKernelProfileService/getUserDetailInfoWithBizInfo",{"uid":"u_S2-Q5q_Vw9vvi0LenPp9UA"},null] 

2024/4/13 20:01:40 3236994860(3236994860): get self nickname failed undefined 

2024/4/13 20:01:46 3236994860(3236994860): ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelProfileService/getUserDetailInfoWithBizInfo ["nodeIKernelProfileService/getUserDetailInfoWithBizInfo",{"uid":"u_S2-Q5q_Vw9vvi0LenPp9UA"},null] 

2024/4/13 20:01:46 3236994860(3236994860): get self nickname failed undefined 

2024/4/13 20:01:52 3236994860(3236994860): ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelProfileService/getUserDetailInfoWithBizInfo ["nodeIKernelProfileService/getUserDetailInfoWithBizInfo",{"uid":"u_S2-Q5q_Vw9vvi0LenPp9UA"},null] 

2024/4/13 20:01:52 3236994860(3236994860): get self nickname failed undefined 

2024/4/13 20:01:58 3236994860(3236994860): ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelProfileService/getUserDetailInfoWithBizInfo ["nodeIKernelProfileService/getUserDetailInfoWithBizInfo",{"uid":"u_S2-Q5q_Vw9vvi0LenPp9UA"},null] 

2024/4/13 20:01:58 3236994860(3236994860): get self nickname failed undefined 

2024/4/13 20:02:04 3236994860(3236994860): ws ???? ws://127.0.0.1:11038/onebot/v11/ws {"time":1713009724,"self_id":3236994860,"post_type":"meta_event","meta_event_type":"heartbeat","status":{"online":true,"good":true},"interval":60000} 

2024/4/13 20:02:04 3236994860(3236994860): ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelProfileService/getUserDetailInfoWithBizInfo ["nodeIKernelProfileService/getUserDetailInfoWithBizInfo",{"uid":"u_S2-Q5q_Vw9vvi0LenPp9UA"},null] 

2024/4/13 20:02:04 3236994860(3236994860): get self nickname failed undefined 

2024/4/13 20:03:04 3236994860(3236994860): ws ???? ws://127.0.0.1:11038/onebot/v11/ws {"time":1713009784,"self_id":3236994860,"post_type":"meta_event","meta_event_type":"heartbeat","status":{"online":true,"good":true},"interval":60000}
```

### OneBot 客户端运行日志

```shell
04-13 20:01:04 [????] <nonebot> OneBot V11 | Bot 3236994860 connected
04-13 20:01:04 [????] <websockets> connection open
（之前的都是插件加载，在open后没有任何动静了）
```

**Comment by linyuchen** [comment]
NTQQ的ipc通信超时，具体原因未知，有可能Linux上QQ环境问题，尝试重装QQ或者降低QQ版本试试

如果能进行QQ界面操作，手动发送消息试一下能否发送，发送成功后重启QQ看看

**Comment by gucheng599** [comment]
MACOS也遇到了这个问题

```
{'status': 'failed', 'retcode': 200, 'data': None, 'message': 'ntqq api timeout IPC_UP_2, ns-FsApi-2, getFileMd5, getFileMd5,/Users/haiperry/Desktop/多对多/936996208/IMG_6433.PNG', 'wording': 'ntqq api timeout IPC_UP_2, ns-FsApi-2, getFileMd5, getFileMd5,{filepath}', 'echo': None}
```

**Comment by Ant00000ny** [comment]
- macOS 13
- LLOneBot 3.26.7

同样的问题

```plaintext
7/12/2024, 8:30:36 PM xxx(xxx): ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelProfileService/getUserDetailInfoWithBizInfo ["nodeIKernelProfileService/getUserDetailInfoWithBizInfo",{"uid":"xxx"},null] 

7/12/2024, 8:30:36 PM xxx(xxx): get self nickname failed undefined 
```

**Comment by idranme** [comment]
v3.27.4 是否依然存在该问题？

**Comment by Ant00000ny** [comment]
目前为止没有再出现过。
