### ISSUE TITLE
[BUG] Url的参数不识别

### ISSUE THREAD

**Issue by hurttttr** [LLOneBot/LLOneBot#194]
### 系统版本

ubuntu22.02

### QQNT 版本

docker部署

### LLOneBot 版本

3.22.1

### OneBot 客户端

青龙

### 发生了什么?

gocqhttp可以将user_id的值可以放在url中，例如`http://127.0.0.1/send_private_msg?user_id=xxx`，目前本项目的只能在post请求体中，一些项目无法使用本项目作为推送方式
![image](https://github.com/LLOneBot/LLOneBot/assets/58456022/cb6b5e04-0e7a-4adb-96c7-9d8de700d262)

### 如何复现

将请求体中的user_id通过url传递

### 期望的结果?

可以兼容上述的请求方式

**Comment by linyuchen** [comment]
使用url的参数时需要将 http 请求方法改成 get

**Comment by linyuchen** [comment]
v3.23.0已支持 POST url 参数

**Comment by hurttttr** [comment]
十分感谢
