### ISSUE TITLE
需求:登录BOT时不上报登录前消息的限制

### ISSUE THREAD

**Issue by airdm** [LLOneBot/LLOneBot#195]
希望可以增加一个登录QQ时不要处理留言信息的功能,这会导致刚登录时出现大量事件上报导致冻结.
QQNT会时不时出现崩溃的问题,再次登录时BOT会一口气处理大量的留言信息.希望可以添加一个限制,例如在登录的10秒内的信息不会进行事件上报.或者不处理登录前的消息.

**Comment by airdm** [comment]
或者直接可以不对历史留言信息进行事件上报

**Comment by linyuchen** [comment]
v3.23.0已过滤登录前的消息

**Comment by Fripine** [comment]
> v3.23.0已过滤登录前的消息

该功能可否改为开关型，有些bot数据量不大，但是在断线重连后需要尽快将未接收到的数据进行处理、存储，如果一律舍弃不处理可能造成数据丢失
