### ISSUE TITLE
[BUG]  部分图片地址仅内陆可以访问，无法在外网访问

### ISSUE THREAD

**Issue by Container-Zero** [LLOneBot/LLOneBot#198]
### 系统版本

Windows Server 2012

### QQNT 版本

9.9.8-22165

### LLOneBot 版本

3.22.1

### OneBot 客户端

Koishi->koishi-plugin-adapter-onebot->LLonebot->LiteLoaderQQNT->QQNT

### 发生了什么?

部分图片地址仅内陆IP可以访问，外网IP或代理下为未响应

### 如何复现

如下述地址：

https://gchat.qpic.cn/download?appid=1407&fileid=Cgk3NTgwNTU4OTISFB2zZ0doDz-aksQDmTUHexnXUfNcGI3CWCD_Cii93aT2rMuFA1CAvaMB&rkey=CAQSKAB6JWENi5LMk0kc62l8Pm3Jn1dsLZHyRLAnNmHGoZ3y_gDZPqZt-64&spec=0

https://gchat.qpic.cn/download?appid=1407&fileid=CgoyNzk5NDA4Mjc3EhQOm1Ac3lZaBKK6xdVVtrfu-zpo9Rj58UAg_woo6omlma_HhQNQgL2jAQ&rkey=CAQSKAB6JWENi5LMk0kc62l8Pm3Jn1dsLZHyRLAnNmHGoZ3y_gDZPqZt-64&spec=0

在空Referer情况下全局代理，或外网环境下访问会显示未响应，但使用内陆网可正常响应图片内容（已确认并非外网网络环境问题，只要是非内陆IP都不可访问）

### 期望的结果?

图片链接在任何网络环境下都可以正常访问

**Comment by jinyu2022** [comment]
这个好像是qq自己的封控机制。

**Comment by Container-Zero** [comment]
> 这个好像是qq自己的封控机制。

这是最近才出现的，我本来也觉得是被屏蔽了，但是仔细一想还是觉得有些不太确定：
1.大部分图片链接是可以在海外环境下访问的，仅有少部分图片会出现上述情况
2.这些链接是不是QQ图片的原始链接，如果是的话海外用户用QQ应该会收不到图片？

我不太清楚是不是腾讯自己的海外CDN管理问题，还是说真的是新的风控机制，所以提个 Issues 来确认下状况。

**Comment by linyuchen** [comment]
貌似是图床的 CDN 问题，目前 LLOneBot 这边没什么办法

**Comment by Container-Zero** [comment]
> 貌似是图床的 CDN 问题，目前 LLOneBot 这边没什么办法

好的，但是否可以为 LLOneBot 增加一个设置选项，以替换 `gchat.qpic.cn` 为自建反代服务来规避网络环境带来的影响？
我知道这个错误并非 LLOneBot 的问题，但这个选项可能能够临时解决这个问题以及避免以后相似的情况出现，可以让开发者自行确保网络环境的稳定性。

非错误方修复错误的需求并非合理，但您觉得上述提议如何？

**Comment by jinyu2022** [comment]
反代可以自己建的吧，nginx

**Comment by Container-Zero** [comment]
> 反代可以自己建的吧，nginx

是的，我的意思就是自己建，然后在输入框填上自建的反代来替换 `gchat.qpic.cn` ，当然不是要求作者提供反代服务。

**Comment by jinyu2022** [comment]
> 是的，我的意思就是自己建，然后在输入框填上自建的反代来替换 `gchat.qpic.cn` ，当然不是要求作者提供反代服务。

但是你有自己的反代服务的话，直接在bot里接收消息，替换一下url字符串不就好了？

**Comment by Container-Zero** [comment]
> > 是的，我的意思就是自己建，然后在输入框填上自建的反代来替换 `gchat.qpic.cn` ，当然不是要求作者提供反代服务。
> 
> 但是你有自己的反代服务的话，直接在bot里接收消息，替换一下url字符串不就好了？

因为涉及到大量基于图片类的项目，包括非我维护的项目，每个都要修改捕获的图片 url 工程量实在太大了。

**Comment by jinyu2022** [comment]
> > 但是你有自己的反代服务的话，直接在bot里接收消息，替换一下url字符串不就好了？
> 
> 因为涉及到大量基于图片类的项目，包括非我维护的项目，每个都要修改捕获的图片 url 工程量实在太大了。

没有一个统一的消息入口吗？有的话直接在入口修改然后往后传就行。不然确实麻烦了。你可以试着提交pr

**Comment by linyuchen** [comment]
调用`/get_image`获取本地文件路径或者base64来获取图片，新的图床有时效，搞反代什么的就没必要了

**Comment by Container-Zero** [comment]
> 调用`/get_image`获取本地文件路径或者base64来获取图片，新的图床有时效，搞反代什么的就没必要了

好的，但目前又出现新的问题，bot 自己发的图片信息上报后，访问该图片链接，显示网页无法访问。

**Comment by jinyu2022** [comment]
> 好的，但目前又出现新的问题，bot 自己发的图片信息上报后，访问该图片链接，显示网页无法访问。

缺少rkey？这玩意目前难以获取

**Comment by Container-Zero** [comment]
> > 好的，但目前又出现新的问题，bot 自己发的图片信息上报后，访问该图片链接，显示网页无法访问。
> 
> 缺少rkey？这玩意目前难以获取

https://gchat.qpic.cn/download?appid=1407&fileid=CgoyNzk5NDA4Mjc3EhQSGvXG2IAPmzlxzEOJoNEa0Wc8xBi8zUQg_woo1_SmjZvThQNQgL2jAQ&rkey=CAQSKAB6JWENi5LMk0kc62l8Pm3Jn1dsLZHyRLAnNmHGoZ3y_gDZPqZt-64&spec=0

不，链接中包含 rkey，没有发生丢失 rkey 的情况，但链接打开时显示的是无法连接。
只有bot自身发的图片会出现无法连接的情况，其他人发的图片所获取的链接可以正常访问。
但貌似bot自身发的动图 (gif格式) 所产生的链接是正常的，可以访问。

即使针对 Issue 中的环境全部更新至最新：
OONT版本：`9.9.8-22165` -> `9.9.9-22961`
LLonebot版本：`3.22.1` -> `3.23.0`
koishi-plugin-adapter-onebot版本：`6.5.0` -> `6.5.1`

此问题依旧存在。
并且在此之上依旧嵌套上述海外网络无法访问图片的问题(即使是上述可以访问的gif链接，在海外依旧无法访问)。

**Comment by linyuchen** [comment]
3.24.0已修复

**Comment by Container-Zero** [comment]
> 3.24.0已修复

感谢！

**Comment by Container-Zero** [comment]
> 3.24.0已修复

使用新域名的 `multimedia.nt.qq.com.cn` 的图片链接也开始失效了

打开此类图片链接显示内容如下：
```
{"retcode":-5503007,"retmsg":"download url has expired","retryflag":0}
```

**Comment by linyuchen** [comment]
> > 3.24.0已修复
> 
> 版本已更新至 `3.24.2` 使用新域名的 `multimedia.nt.qq.com.cn` 的图片链接也开始失效了
> 
> 打开此类图片链接显示内容如下：
> 
> ```
> {"retcode":-5503007,"retmsg":"download url has expired","retryflag":0}
> ```

链接是新拿到的吗

**Comment by Container-Zero** [comment]
> > > 3.24.0已修复
> > 
> > 
> > 版本已更新至 `3.24.2` 使用新域名的 `multimedia.nt.qq.com.cn` 的图片链接也开始失效了
> > 打开此类图片链接显示内容如下：
> > ```
> > {"retcode":-5503007,"retmsg":"download url has expired","retryflag":0}
> > ```
> 
> 链接是新拿到的吗

是的，刚发的图10秒内获取的链接并打开也是如上报错

**Comment by linyuchen** [comment]
> > > > 3.24.0已修复
> 
> > > 
> 
> > > 
> 
> > > 版本已更新至 `3.24.2` 使用新域名的 `multimedia.nt.qq.com.cn` 的图片链接也开始失效了
> 
> > > 打开此类图片链接显示内容如下：
> 
> > > ```
> 
> > > {"retcode":-5503007,"retmsg":"download url has expired","retryflag":0}
> 
> > > ```
> 
> > 
> 
> > 链接是新拿到的吗
> 
> 
> 
> 是的，刚发的图10秒内获取的链接并打开也是如上报错

用v3.24.3试试

**Comment by Container-Zero** [comment]
> > > > > 3.24.0已修复
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 版本已更新至 `3.24.2` 使用新域名的 `multimedia.nt.qq.com.cn` 的图片链接也开始失效了
> > 
> > 
> > > > 打开此类图片链接显示内容如下：
> > 
> > 
> > > >
> > 
> > 
> > > > {"retcode":-5503007,"retmsg":"download url has expired","retryflag":0}
> > 
> > 
> > > >
> > 
> > 
> > > 
> > 
> > 
> > > 链接是新拿到的吗
> > 
> > 
> > 是的，刚发的图10秒内获取的链接并打开也是如上报错
> 
> 用v3.24.3试试

经测试，已修复
