### ISSUE TITLE
[enhancement] 希望可以增加一个自动清理缓存的功能

### ISSUE THREAD

**Issue by airdm** [LLOneBot/LLOneBot#201]
C:\Users\Administrator\Documents\Tencent Files\123456\nt_qq\nt_data 目录下的log,pic,video文件夹的缓存文件占用了服务器大部分空间,希望可以增加一个自动定时清理的功能.

**Comment by linyuchen** [comment]
有自动删除接收到文件的功能

**Comment by airdm** [comment]
> 有自动删除接收到文件的功能

你说的这个功能我开着的 但是这个文件夹里面是QQNT 聊天缓存默认文件夹,平均一周就要有20G的无用文件,希望可以加一个清理功能或者api

**Comment by xANoyU** [comment]
> 有api，`/clean_cache`

这个要怎么调用哦，5.4.1版本，data/temp里面几十G了
