### ISSUE TITLE
[BUG] 多账号配置不一样时其中一个账号侧边栏异常

### ISSUE THREAD

**Issue by Starrain08** [LLOneBot/LLOneBot#210]
### 系统版本

Windows 11 家庭中文版

### QQNT 版本

9.9.9-23159

### LLOneBot 版本

3.24.2

### OneBot 客户端

zerobot 1.7.7

### 发生了什么?

多账号登录时，且每个账号配置不一样时，其中一个账号的侧边栏出现延迟加载，并且原本功能都无法使用，加载出后才能使用，补充插件列表信息
![image](https://github.com/LLOneBot/LLOneBot/assets/119772101/5f78702a-3963-4945-9c82-3afb67c786fc)

### 如何复现

1.安装llonebot
2.调整两个账户的配置
3.重启QQ

### 期望的结果?

延迟加载消失，功能正常

**Comment by linyuchen** [comment]
没法复现，并且`原本功能`都无法使用，这个`原本功能`是什么，能否具体一点

尝试把插件一一关掉检查下是不是插件冲突了

**Comment by 2055135** [comment]
例如左下角里的锁定，消息也无法发送

**Comment by 2055135** [comment]
使用chii Devtool抓出一个错误，过一段时间错误消失，侧边栏恢复正常

**Comment by 2055135** [comment]
![image](https://github.com/LLOneBot/LLOneBot/assets/119772101/e15bad3c-04cd-47c1-abbe-d2b256006054)

**Comment by airdm** [comment]
你尝试下关闭其他插件只用llob 我这里多开很多都没有你说的情况.

**Comment by 2055135** [comment]
> 你尝试下关闭其他插件只用llob 我这里多开很多都没有你说的情况.

尝试过，也出现此问题
