### ISSUE TITLE
消息事件无法获取发送者专属头衔

### ISSUE THREAD

**Issue by Lancercmd** [LLOneBot/LLOneBot#211]
### 系统版本

Windows 11 Pro 22H2

### QQNT 版本

9.9.9-23159

### LLOneBot 版本

3.24.2

### OneBot 客户端

nonebot-adapter-onebot 2.4.3

### 发生了什么?

无法获取专属头衔，或获取到的专属头衔为空。

这个问题在上一个 QQNT 版本的使用过程中出现。

### 如何复现

获取 GroupMessageEvent.sender.title

### 期望的结果?

对于实际存在专属头衔的，应获取到专属头衔。

**Comment by linyuchen** [comment]
`这个问题在上一个 QQNT 版本的使用过程中出现。`，你的意思是现在你用的 9.9.9-23159 是正常的吗，头衔是最近的某个NTQQ版本才支持的

**Comment by Lancercmd** [comment]
> `这个问题在上一个 QQNT 版本的使用过程中出现。`，你的意思是现在你用的 9.9.9-23159 是正常的吗，头衔是最近的某个NTQQ版本才支持的

我看了一下，是 GroupMessageEvent 属性中的 title 为空，但 `get_group_member_info` API 调用可以获取到专属头衔。

**Comment by wozaiha** [comment]
> `这个问题在上一个 QQNT 版本的使用过程中出现。`，你的意思是现在你用的 9.9.9-23159 是正常的吗，头衔是最近的某个NTQQ版本才支持的

请问未来是否有计划支持群荣誉（如群头衔等OneBot API？）

**Comment by idranme** [comment]
v3.31.9 已支持
