### ISSUE TITLE
[BUG] get_stranger_info 似乎无法取得到较新的QQ号的信息

### ISSUE THREAD

**Issue by MeowRay** [LLOneBot/LLOneBot#213]
### 系统版本

Windows Server 2022 Datacenter

### QQNT 版本

9.9.9-23424

### LLOneBot 版本

3.24.2

### OneBot 客户端

? 

### 发生了什么?

get_stranger_info 接口无法取得较新(近两年)注册的QQ信息，而较老的QQ号则可以。

在QQNT客户端界面以账号查找则都可以搜到

![image](https://github.com/LLOneBot/LLOneBot/assets/29674595/ffffc619-daf7-4e08-8500-d8681c23628d)

![image](https://github.com/LLOneBot/LLOneBot/assets/29674595/0b9b8d07-c18b-480f-a875-7a44021786f2)

### 如何复现

http://xxxx:3000/get_stranger_info?access_token=xxxx&user_id=3803341832

### 期望的结果?

正确取得或者返回对应结果信息

**Comment by linyuchen** [comment]
get_stranger_info 只能用于获取和当前登录账号有关系的 QQ 信息，如：同个群，是好友，申请好友的对象，申请加群的对象（尚未完善），并非真正意义的查询陌生人

**Comment by MeowRay** [comment]
> get_stranger_info 只能用于获取和当前登录账号有关系的 QQ 信息，如：同个群，是好友，申请好友的对象，申请加群的对象（尚未完善），并非真正意义的查询陌生人

在QQNT客户端手动搜索可以搜到头像和昵称的基础信息，如果是有限制能否支持到能获取的信息？
