### ISSUE TITLE
[Suggestion] 在src/onebot11/constructor.ts:159时额外检测Image类型

### ISSUE THREAD

**Issue by Akizon77** [LLOneBot/LLOneBot#214]
# 在[src/onebot11/constructor.ts:159](https://github.com/LLOneBot/LLOneBot/blob/9b3916307a0a35bf64a724e0cebd1b8b70b1ec80/src/onebot11/constructor.ts#L159)时额外检测Image类型
## 描述

这本是一个腾讯方面的问题，QQNT保存的几乎所有图片都是.jpg
LLOneBot在上报时，会把本是GIF、PNG的图片都上报成JPG（[file字段](https://github.com/LLOneBot/LLOneBot/blob/main/src/onebot11/types.ts#L169)）导致接入Onebot的应用(Eg:Koishi)在向其他平台发送文件时出现问题

## 可能的解决方案

在上报([构造OB11Message](https://github.com/LLOneBot/LLOneBot/blob/9b3916307a0a35bf64a724e0cebd1b8b70b1ec80/src/onebot11/constructor.ts#L159))时和 [#src/ntqqapi/constructor.ts:88](https://github.com/LLOneBot/LLOneBot/blob/627955e7fdfbbd27b89e449e563f37c478e3440d/src/ntqqapi/constructor.ts#L88) 一样检测一下文件类型。应该可以通过调用[此函数解决](https://github.com/LLOneBot/LLOneBot/blob/main/src/common/utils/file.ts#L12)

**Comment by linyuchen** [comment]
修改后缀会面临一些问题：

如果把原始文件名修改了，那么NTQQ可能就找不到这个图片，聊天记录内就不显示，影响NTQQ客户端的正常使用。

如果是copy一份，占用的硬盘空间还挺多的，毕竟沙雕群友天天没事发动图。

有更好的解决方案吗

**Comment by Akizon77** [comment]
可以在文件的末尾添加额外的字符串来标记
在接收到上传文件的事件时，额外判断文件名末尾是否匹配特定字符

原文件： `4BBBD21E12EAD650519735050B7DF8EE.jpg`
上报： `4BBBD21E12EAD650519735050B7DF8EE.jpg.llonebot_randomvalue.gif`

```typescript
function modifyFilename(originalFilename: string, realType: string): string {
    const randomValue = "randomvalue";
    return `${originalFilename}.llonebot_${randomValue}.${realType}`;
}
```
接受时复原
```typescript
function parseAndRestoreFilename(modifiedFilename: string): string {
    const pattern = /^(.+)\.llonebot_(\w+)\.(\w+)$/; 
    const match = modifiedFilename.match(pattern);
    if (match) {
        return match[1];
    }
    return modifiedFilename;
}
```

~没有什么是加中间件解决不了的xd，如果有，那就再加一个~
