### ISSUE TITLE
[功能询问]群成员列表字段不全

### ISSUE THREAD

**Issue by Natsukage** [LLOneBot/LLOneBot#221]
get_group_member_list时，last_sent_time等参数默认为0，目前的代码中注释是拿不到相关消息所以默认返回0。
但是看到隔壁NapCatQQ已经可以获取相关内容了[关联issue](https://github.com/NapNeko/NapCatQQ/issues/3)
所以想问下这个功能现在在LLOneBot这边可以实现吗？
多谢！

**Comment by linyuchen** [comment]
可以实现，暂时没有和 NapCat 同步

**Comment by wfhfly** [comment]
> 可以实现，暂时没有和 NapCat 同步

啥时候可以支持一下last_sent_time，join_time等字段呢

**Comment by byx2020** [comment]
同样请求支持join_time字段，因为需要通过这个字段来判断一个QQ号是否存在于本群

**Comment by idranme** [comment]
v3.29.3 已解决
