### ISSUE TITLE
[功能反馈]快速操作 reply 并没有引用对方进行回复

### ISSUE THREAD

**Issue by ours1505** [LLOneBot/LLOneBot#226]
https://docs.go-cqhttp.org/reference/#%E4%B8%8A%E6%8A%A5
在go-cqhttp中，快速操作可以引用并回复消息，LLOnebot并不会引用原消息，无法区分在用户操作较多时无法区分下发命令的用户

**Comment by linyuchen** [comment]
已添加引用原消息，重新下载v3.26.0

**Comment by ours1505** [comment]
fixed

**Comment by coldwinds** [comment]
我在用的go-cqhttp v1.0.1 是不会引用原消息的，是新版加的吗 @ours1505

是否给个全局设置 可以设置引用/不引用 @linyuchen

**Comment by linyuchen** [comment]
> 我在用的go-cqhttp v1.0.1 是不会引用原消息的，是新版加的吗 @ours1505
> 
> 是否给个全局设置 可以设置引用/不引用 @linyuchen

v3.26.2已添加设置项
