### ISSUE TITLE
[功能询问]LLonebot是否支持无图形界面部署？

### ISSUE THREAD

**Issue by intling-luo** [LLOneBot/LLOneBot#230]
想在云服务器Ubuntu22.04 x64上部署，地摊服务器性能过于有限，且安装图形界面略臃肿，是否有无图形界面部署的办法？

**Comment by Natsukage** [comment]
LLOneBot的文档里有写，你可以试试用无头的[NapCatQQ](https://github.com/NapNeko/NapCatQQ)，应该能满足你的需求
但是NapCatQQ用了并不是全开源的，如果想要自己调试或者修改功能的话会很麻烦（没法自己编译），所以看你的需求了

**Comment by intling-luo** [comment]
> LLOneBot的文档里有写，你可以尝试用无头的[NapCatQQ](https://github.com/NapNeko/NapCatQQ)，应该能满足你的需求 但是NapCatQQ好像不是全开源的，如果想要自己调试或者修改功能的话会很麻烦（不能自己编译），所以看你的需求了

感谢解答,我会试试的
