### ISSUE TITLE
[Suggestion] get_msg方法没有返回raw字段

### ISSUE THREAD

**Issue by Natsukage** [LLOneBot/LLOneBot#232]
### 系统版本

Windows 11 专业版 23H2

### QQNT 版本

9.9.9.23424

### LLOneBot 版本

3.24.3

### OneBot 客户端

无

### 发生了什么?

开启调试模式后，正常上报的信息均包含了raw字段，但是使用get_msg获取到的信息中没有raw字段

### 如何复现

使用get_msg进行获取信息操作

### 期望的结果?

希望开启调试模式后，get_msg也能够给出raw字段内容
由于OneBot11的局限性，在现在不修改服务端的情况下，很多内容实际上只能通过客户端解析raw消息来拿到。例如发送消息中raw里附带了群名，但是正常上报的消息中没有这条内容，必须根据群号再次执行一次群查询。
还有一些信息例如图片的md5、文件的md5等内容除了raw以外完全没有上报的途径。
所以get_msg是否能够获取raw的内容区别还是挺大的。

### LLOneBot 运行日志

```shell
2024/5/23 14:15:30 LL(12345): 收到正向Websocket消息 {"action":"get_msg","echo":"de57606b-4f3b-4a82-8d30-66ad99bc8f52","params":{"message_id":-2147481114}} 

2024/5/23 14:15:30 LL(12345): ws 消息上报  {"status":"ok","retcode":0,"data":{"self_id":12345,"user_id":54321,"time":1716394253,"message_id":-2147481114,"real_id":-2147481114,"message_seq":-2147481114,"message_type":"group","sender":{"user_id":54321,"nickname":"13579","card":"","role":"owner"},"raw_message":"测试","font":14,"sub_type":"normal","message":[{"data":{"text":"测试"},"type":"text"}],"message_format":"array","post_type":"message","group_id":11111},"message":"","wording":"","echo":"de57606b-4f3b-4a82-8d30-66ad99bc8f52"}
```

### OneBot 客户端运行日志

```shell
无
```

**Comment by MliKiowa** [comment]
不要依赖raw raw在各个地方都是不一样的

**Comment by linyuchen** [comment]
3.26.1已添加raw字段
