### ISSUE TITLE
[BUG] 无法收到来自群成员邀请的群申请

### ISSUE THREAD

**Issue by rongrong1000** [LLOneBot/LLOneBot#237]
### 系统版本

win server 2012

### QQNT 版本

9.9.7-21484 (64位)

### LLOneBot 版本

3.26.2

### OneBot 客户端

无

### 发生了什么?

无法收到来自群成员邀请的群申请
如果自己单独申请进群则没有问题

### 如何复现

群成员邀请一个qq好友
群成员不是管理员

### 期望的结果?

收到事件

### LLOneBot 运行日志

```shell
无
```

### OneBot 客户端运行日志

```shell
无
```

**Comment by linyuchen** [comment]
v3.26.3
