### ISSUE TITLE
[BUG] 安装 LLOneBot 后设置中无法显示

### ISSUE THREAD

**Issue by YatsukiRenka** [LLOneBot/LLOneBot#239]
### 系统版本

Windows 11 专业版 23H2

### QQNT 版本

9.9.10-24108

### LLOneBot 版本

3.26.2

### OneBot 客户端

无

### 发生了什么?

根据 wiki 使用 https://github.com/super1207/install_llob 进行安装后无法在 设置-LiteLoaderQQNT 中发现 LLOneBot 插件
手动下载解压进 C:\Program Files\Tencent\QQNT\resources\app\LiteLoaderQQNT-main\plugins 重启后亦然
卸载 QQNT 并清除干净残余文件后重新手动安装 LiteLoaderQQNT 和 LLOneBot 仍然无法显示 LLOneBot 插件

![image](https://github.com/LLOneBot/LLOneBot/assets/38554950/d6370622-a681-4df4-9734-0b0e0f477549)
![image](https://github.com/LLOneBot/LLOneBot/assets/38554950/072c4a71-3a31-4ae9-90ec-6fc95c8e9d7b)

### 如何复现

正常安装即可触发

### 期望的结果?

是否尚未兼容最新 QQNT / LiteLoaderQQNT 版本? 如果不是的话希望能获取一些排查问题的帮助

**Comment by linyuchen** [comment]
LLOneBot放到数据目录的plugins里
![image](https://github.com/LLOneBot/LLOneBot/assets/10002169/ee421eaf-109b-42d7-91e9-1c0fbd95865d)

**Comment by YatsukiRenka** [comment]
> LLOneBot放到数据目录的plugins里 ![image](https://private-user-images.githubusercontent.com/10002169/333989447-ee421eaf-109b-42d7-91e9-1c0fbd95865d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3OTE2MDEsIm5iZiI6MTcxNjc5MTMwMSwicGF0aCI6Ii8xMDAwMjE2OS8zMzM5ODk0NDctZWU0MjFlYWYtMTA5Yi00MmQ3LTkxZTktMWMwZmJkOTU4NjVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDA2MjgyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlOTI2NDgyMmRhOGNkNTQxZmI0NzZhNDk1YTZlMzUzMmM0NGM5NDVhNjVkODY1NTYwYTI4YmViMjliZWI3ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._pMmjN57hGRyrVi1KJ5ZpDSOrP_Enb3R2lVfrGtnH4Q)

好了, 感谢
