### ISSUE TITLE
[Feature] 是否会支持群文件管理的相关API

### ISSUE THREAD

**Issue by gucheng599** [LLOneBot/LLOneBot#241]
### 系统版本

Windows11

### QQNT 版本

9.9.10

### LLOneBot 版本

3.26.2

### OneBot 客户端

1.1.1

### 发生了什么?

看到目前已经支持了"上传群文件"的接口，如果能够支持 创建群文件夹（/create_group_file_folder）、获取群文件夹信息（get_group_root_files）接口 会更加方便bot控制群文件

### 如何复现

![image](https://github.com/LLOneBot/LLOneBot/assets/46436123/5a1423f2-da70-482f-b041-1dc669df4d3c)

### 期望的结果?

是否有可能支持 创建群文件夹（/create_group_file_folder）、获取群文件夹信息（get_group_root_files）的API。
因为部分bot会使用到这两个Api接口

**Comment by CarlGao4** [comment]
同问

**Comment by idranme** [comment]
v3.31.2 已支持 `/create_group_file_folder`

**Comment by gucheng599** [comment]
> v3.31.2 已支持 `/create_group_file_folder`

感谢！

**Comment by gucheng599** [comment]
> v3.31.2 已支持 `/create_group_file_folder`

看到最近的release，了解到新增支持了`delete_group_folder`接口，请问LLOneBot怎么获取group_folder的folder_id呢

**Comment by idranme** [comment]
v3.31.6 已支持 `/get_group_root_files`
