### ISSUE TITLE
[BUG] 收到无历史消息成员从群内发起的临时会话的第一条消息，无法回复，之后消息都可以正常回复，只有第一条消息提示无法发送临时消息

### ISSUE THREAD

**Issue by aglszz** [LLOneBot/LLOneBot#246]
### 系统版本

win11

### QQNT 版本

最新

### LLOneBot 版本

最新

### OneBot 客户端

最新版本

### 发生了什么?

收到无历史消息成员从群内发起的临时会话的第一条消息，无法回复，之后消息都可以正常回复，只有第一条消息提示无法发送临时消息

### 如何复现

收到无历史消息成员从群内发起的临时会话的第一条消息，无法回复，之后消息都可以正常回复，只有第一条消息提示无法发送临时消息

### 期望的结果?

收到无历史消息成员从群内发起的临时会话的第一条消息，可以正常回复
![QQ截图20240602145710](https://github.com/LLOneBot/LLOneBot/assets/27655065/104dcfa8-09e3-416e-a8a3-e760168a38ab)

**Comment by Wendi056** [comment]
我也遇到了，成员向机器人qq（管理员）发起临时会话，有时候机器日会收不到消息，10个有3个左右收不到的，你解决了么？
