### ISSUE TITLE
[功能询问] get_stranger_info返回值有个字段不知道哪来的

### ISSUE THREAD

**Issue by caikun233** [LLOneBot/LLOneBot#247]
### 系统版本

Windows Server 2022 Datacenter

### QQNT 版本

9.9.9-23159

### LLOneBot 版本

3.23.0

### OneBot 客户端

Postman建立的Websocket API连接

### 发生了什么?

如图，action是`get_stranger_info`，翻了一下代码发现是通过IPC调取的，问题是这些信息中`address`的实际来源找不到。
![f94f4aa5ad7db506c57740c5a14b50fc](https://github.com/LLOneBot/LLOneBot/assets/69567735/709fccd5-cbda-40fe-b2ea-15d2f121352c)
我是被调取账号的主人，我从没在QQ的资料卡里填写详细地址之类的信息（也可能是忘了但我现在也找不到在哪改）。并且在我重启了一下QQ客户端后，这些信息就全都报查无此人，随后我写了这个issue的前半段，再去调取又能调出来。
![图片](https://github.com/LLOneBot/LLOneBot/assets/69567735/fca25105-5468-40f3-9d3c-7f14ee666335)

### 如何复现

呃我有点混乱，我不太清楚我要怎么准确的描述这个过程。可能我先是发现这些信息是公开的，所以我想去修改或者隐藏它们（因为它真的是准确的，精确到房间号），所以我一路追到了ntqqapi/ntcall.ts，发现是IPC通信后想不出什么好办法就重启了一次QQ客户端，再调又查无此人所以来submit issue，结果又能调了。

### 期望的结果?

1. 我大概是想先找到重启后报查无此人的原因；
2. 然后去找这些信息的来源，在我的账号上隐藏掉它们。

**Comment by linyuchen** [comment]
查无此人的原因可能是还没有获取到好友列表导致的，这个可能是个bug

address 字段你可以登录老版本的QQ（非NT）编辑个人资料里面看看

**Comment by caikun233** [comment]
> 查无此人的原因可能是还没有获取到好友列表导致的，这个可能是个bug
> 
> address 字段你可以登录老版本的QQ（非NT）编辑个人资料里面看看

非NT的9.7.20编辑个人资料里是没找到相关的设置
![图片](https://github.com/LLOneBot/LLOneBot/assets/69567735/6a94265e-4cc5-4862-bcca-f98c262d8a07)
但说真的我有点印象，好久之前的某个QQ客户端是有的，我一定是什么时候设置过，但我忘了在哪了
