### ISSUE TITLE
[功能建议]多账号登录的情况下，端口重复占用。

### ISSUE THREAD

**Issue by stevekiko** [LLOneBot/LLOneBot#248]
假设我登录了5个qq，再使用默认配置的情况下。五个qq同时使用一个配置，

**Comment by avexova** [comment]
今天刚开始试用llonebot，点击变更保存后他是以你Q号命名一个配置文件的，我两个QQ，看到的确出了2个配置文件。一个端口5700、一个端口6700没冲突。不知道你这边是什么情况。确保是最新的v3.26.5？

**Comment by idranme** [comment]
多账号同时登录的情况下，请为每个账号单独设置端口
