### ISSUE TITLE
[功能请求] 能否为反向 WS 添加 User-Agent 的 header

### ISSUE THREAD

**Issue by Bluefissure** [LLOneBot/LLOneBot#249]
相关代码 https://github.com/LLOneBot/LLOneBot/blob/d4427cf/src/onebot11/server/ws/ReverseWebsocket.ts#L84-L88 
这样可以方便在服务端添加识别不同协议与客户端，比如 "CQHttp", "MiraiHttp", "OneBot", "Shamrock" 等等

如果可行，我可以提供 PR，但是不清楚采取哪项方案比较好：
1. 为了和 OneBot 兼容仍然采取 OneBot 的 UA
2. 为了区分选择新的 UA （LLOneBot？）

**Comment by linyuchen** [comment]
get_version_info 这个 api 能获取到协议端的相关信息，这个满足不了你的需求吗

**Comment by Bluefissure** [comment]
> get_version_info 这个 api 能获取到协议端的相关信息，这个满足不了你的需求吗

这个 api 也需要连接后才能调用吧

**Comment by linyuchen** [comment]
> > get_version_info 这个 api 能获取到协议端的相关信息，这个满足不了你的需求吗
> 
> 这个 api 也需要连接后才能调用吧

是的，如果在连接成功之前就需要知道协议端信息，那这个有点怪，别的协议端都有这个 UA 吗，OneBot11 文档并没有看到相关说明

**Comment by Bluefissure** [comment]
> > > get_version_info 这个 api 能获取到协议端的相关信息，这个满足不了你的需求吗
> > 
> > 
> > 这个 api 也需要连接后才能调用吧
> 
> 是的，如果在连接成功之前就需要知道协议端信息，那这个有点怪，别的协议端都有这个 UA 吗，OneBot11 文档并没有看到相关说明

是的，大部分客户端（"CQHttp", "MiraiHttp", "OneBot", "Shamrock"）都有，我的服务通过UA来判断来的具体客户端类型

**Comment by linyuchen** [comment]
你可以提个pr，UA为LLOneBot
