### ISSUE TITLE
阻止发送空消息

### ISSUE THREAD

**Issue by A8Cl233395** [LLOneBot/LLOneBot#251]
我使用python， websocket universal
程序出现bug时发送了空消息，没有阻止，导致被qq封号
希望可以增加一个阻止发送空消息的功能

**Comment by linyuchen** [comment]
空消息是什么样的，有日志吗？

**Comment by A8Cl233395** [comment]
> 空消息是什么样的，有日志吗？

没有，是我的程序有问题，只是希望能增加一个阻止发送空消息的功能

**Comment by idranme** [comment]
![image](https://github.com/user-attachments/assets/a72b2707-c0ab-4df3-be37-e54aa3740964)
当前版本会阻止发送空消息
