### ISSUE TITLE
[BUG] 最新QQ启动报错

### ISSUE THREAD

**Issue by jhqwqmc** [LLOneBot/LLOneBot#253]
### 系统版本

Windows Server 2022 Standard 21H2

### QQNT 版本

9.9.11-24402

### LLOneBot 版本

3.26.6

### OneBot 客户端

未连接

### 发生了什么?

启动客户端直接报错

### 如何复现

1. 更新到最新客户端
2. 启动qq
3. 等待报错出现

### 期望的结果?

第3步的情况不复习

### LLOneBot 运行日志

```shell
无有用数据
```

### OneBot 客户端运行日志

```shell
未连接
```

**Comment by jhqwqmc** [comment]
![image](https://github.com/LLOneBot/LLOneBot/assets/113768629/e2d1786e-18a8-454e-b160-c39a980f8708)

**Comment by linyuchen** [comment]
关闭戳一戳功能，修改 `插件数据目录/LLOneBot/config_<QQ号>.json`中的`enablePoke`为`false`

**Comment by jhqwqmc** [comment]
> 关闭戳一戳功能，修改 `插件数据目录/LLOneBot/config_<QQ号>.json`中的`enablePoke`为`false`

没问题了

**Comment by A-pppp** [comment]
![Image](https://github.com/user-attachments/assets/8099d88d-1a0a-43ce-a435-59e41ba16aad) config_qq号.json怎么解决
