### ISSUE TITLE
[BUG] get_record接口获取的base64编码内容，未按照入参out_format指定的格式进行转码

### ISSUE THREAD

**Issue by LainNetWork** [LLOneBot/LLOneBot#257]
### 系统版本

winserver2022

### QQNT 版本

9.9.7-21804

### LLOneBot 版本

3.26.6

### OneBot 客户端

自己写的实现onebot协议的SDK

### 发生了什么?

我通过get_record成功调用获取到base64的内容并解码后，发现格式和我入参时填写的out_format不符，在日志中确认了bot接收到的请求体格式是正确的。将获取到的内容写到本地取MD5，发现和bot侧缓存文件的MD5一致，并且日志中无报错信息，ffmpeg配置也是正确的，也没有相关的报错。
![image](https://github.com/LLOneBot/LLOneBot/assets/20994069/606067c7-1c0a-45f1-a21e-bf5202a2a6d8)

![image](https://github.com/LLOneBot/LLOneBot/assets/20994069/34221a7c-4893-4b97-8850-646110756fc9)
![image](https://github.com/LLOneBot/LLOneBot/assets/20994069/974ae97d-ab61-46b2-9c2d-289c1e81a93a)

所以我认为这里应该是没有进行转码，而是直接把源文件发出来了？虽然这个base64字段不是标准的onebot接口的内容，但从获取录音内容的角度来说，这里base64输出的应当是转码后的内容才对吧，文件名也应当是转换后的
![image](https://github.com/LLOneBot/LLOneBot/assets/20994069/588127be-66a7-4e48-9faf-68530ebca558)

### 如何复现

调用get_record接口
![image](https://github.com/LLOneBot/LLOneBot/assets/20994069/eb6e2d2d-1e92-477f-b8cd-b5296fb07bc4)

### 期望的结果?

期望输出的内容为转码

### LLOneBot 运行日志

```shell
2024/6/16 05:08:22 Lain(xxxxxxxx): 收到http请求 /get_record {"access_token":"xxxxxx","file":"78664b6b7af535ffeeb3axxxxxxxxx.amr","out_format":"wav"}
```

**Comment by linyuchen** [comment]
llonebot暂未实现转码功能，输出的是原编码silk格式音频

**Comment by LainNetWork** [comment]
> llonebot暂未实现转码功能，输出的是原编码silk格式音频

音频相关的功能目前都是要求配置ffmpeg的，请问您后续有计划支持该参数吗？

**Comment by linyuchen** [comment]
3.26.7已支持

**Comment by LainNetWork** [comment]
感谢作者的勤劳付出~
