### ISSUE TITLE
[BUG] 无法打开QQ

### ISSUE THREAD

**Issue by Night-GUA** [LLOneBot/LLOneBot#258]
### 系统版本

Windows 11 家庭版 23H2

### QQNT 版本

9.9.11

### LLOneBot 版本

3.26.6

### OneBot 客户端

无

### 发生了什么?

LLOneBot安装后 再次打开QQ 发现提示“QQ遇到错误，给您带来不便，我们深表歉意”
错误模块是LLOneBot的crychic.node
.\LiteloaderQQNT\plugins\LLOneBot\main\crychic.node

### 如何复现

也许是安装LLOneBot后打开了两个QQ 再退出就无法打开了

### 期望的结果?

QQNT正常打开

**Comment by MliKiowa** [comment]
到配置文件关闭戳一戳

**Comment by linyuchen** [comment]
#253
