### ISSUE TITLE
[Feat]QQNT大约1个月会出现登录失效的弹窗

### ISSUE THREAD

**Issue by bianyuan456** [LLOneBot/LLOneBot#263]
QQNT大约1个月会出现登录失效的弹窗，我在想能不能再框架侧或者插件侧，在大概登录了29天时实现退出并重新登录QQNT，来避免出现QQNT登录失效，导致插件没有效果的情况？
<img src="https://pic.imgdb.cn/item/6676fcead9c307b7e94e893e.png" alt="QQ图片20240623003247.png">

**Comment by MliKiowa** [comment]
手动重启 没有别的方法
