### ISSUE TITLE
[BUG] rkey 获取失败

### ISSUE THREAD

**Issue by WarfarinBloodanger** [LLOneBot/LLOneBot#264]
### 系统版本

Windows 10

### QQNT 版本

9.9.11-24568

### LLOneBot 版本

3.26.7

### OneBot 客户端

自己搭建Flask http服务器

### 发生了什么?

通过返回的 CQ 码里的 url 不能下载图片。使用浏览器打开 url 后返回消息

```
{"retcode":-5503007,"retmsg":"download url has expired","retryflag":0}
```

在之前出现过 invakid rkey 错误，检查发现是 CQ 码的 url 里缺少 rkey 参数。重启片刻后虽然有了 rkey，但是仍然无法下载图片。已查阅之前的 issue #171，推测是因为 rkey 获取异常，导致图片 url expire。

检查日志后，发现的确是 rkey 出了问题。

### 如何复现

1. 配置 LLOneBot 端口，从任意 http 服务器端得到消息数据；
2. 通过消息数据中 CQ 码的 url 尝试下载图片，失败。
3. 观察日志。

### 期望的结果?

正常获取 rkey。

### LLOneBot 运行日志

```shell
2024/6/27 13:40:51 机器人(qq号): 获取rkey失败 {"cause":{"errno":-4077,"code":"ECONNRESET","syscall":"read"}}
```

### OneBot 客户端运行日志

```shell
无
```

**Comment by linyuchen** [comment]
检查能否正常访问 http://napcat-sign.wumiao.wang:2082/rkey

**Comment by WarfarinBloodanger** [comment]
补充：发出issue后，尝试关闭全局代理vpn时，rkey似乎可以正常获取

**Comment by MliKiowa** [comment]
tls没过 或者 代理网络环境 问题

**Comment by WarfarinBloodanger** [comment]
> 检查能否正常访问 http://napcat-sign.wumiao.wang:2082/rkey

同一wifi下，在开了 vpn 之后，电脑浏览器（Firefox）可以访问；关闭之后不能访问出现 connection reset（很像被墙了）；但这似乎与我上面关闭代理后暂时恢复正常的现象矛盾。或许上面恢复正常只是一种偶然？

以及，观察日志发现大部分错误都是 connection reset（有少量的 connection refused）。

**Comment by idranme** [comment]
无法复现

**Comment by 666dechaoge** [comment]
> > 检查能否正常访问 http://napcat-sign.wumiao.wang:2082/rkey
> 
> 同一wifi下，在开了 vpn 之后，电脑浏览器（Firefox）可以访问；关闭之后不能访问出现 connection reset（很像被墙了）；但这似乎与我上面关闭代理后暂时恢复正常的现象矛盾。或许上面恢复正常只是一种偶然？
> 
> 以及，观察日志发现大部分错误都是 connection reset（有少量的 connection refused）。

web server is down

**Comment by linyuchen** [comment]
> > > 检查能否正常访问 http://napcat-sign.wumiao.wang:2082/rkey
> > 
> > 
> > 同一wifi下，在开了 vpn 之后，电脑浏览器（Firefox）可以访问；关闭之后不能访问出现 connection reset（很像被墙了）；但这似乎与我上面关闭代理后暂时恢复正常的现象矛盾。或许上面恢复正常只是一种偶然？
> > 以及，观察日志发现大部分错误都是 connection reset（有少量的 connection refused）。
> 
> web server is down

http://napcat-sign.wumiao.wang:2082/rkey 是老的地址

现在rkey地址已经用新的了，需要更新LLOneBot，老的不再维护了
