### ISSUE TITLE
是否支持发送多层合并消息

### ISSUE THREAD

**Issue by ti-e** [LLOneBot/LLOneBot#265]
### 系统版本

win11

### QQNT 版本

版本: 9.9.11-24568 (64位)

### LLOneBot 版本

3.26.7

### OneBot 客户端

2.16

### 发生了什么?

![image](https://github.com/LLOneBot/LLOneBot/assets/152352974/4eb0be1b-1053-48b1-b057-10e764e85846)
在尝试多种JSON数据组合后依然无法发送 合并消息【合并消息【】，合并消息【】】，单层的 合并消息【】可以发送成功 

### 如何复现

QQ两个聊天记录合并转发

### 期望的结果?

镶嵌式的合并消息 是否支持？

**Comment by ti-e** [comment]
![image](https://github.com/LLOneBot/LLOneBot/assets/152352974/1417ec5a-7229-41a6-9a0c-2cee5f2bf8a3)

发送合并消息请求数据: {'group_id': 770626076, 'messages': [{'type': 'node', 'data': {'name': '小云儿', 'uin': 1094950020, 'content': [{'data': {'text': '测试'}, 'type': 'text'}]}}, {'type': 'node', 'data': {'name': '小云儿', 'uin': 1094950020, 'content': [{'data': {'id': '7385086735340206481'}, 'type': 'forward'}]}}]}

如此引用是不是我引用的方式不对，不显示多层

**Comment by linyuchen** [comment]
> ![image](https://private-user-images.githubusercontent.com/152352974/343680365-1417ec5a-7229-41a6-9a0c-2cee5f2bf8a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NzUyODcsIm5iZiI6MTcxOTQ3NDk4NywicGF0aCI6Ii8xNTIzNTI5NzQvMzQzNjgwMzY1LTE0MTdlYzVhLTcyMjktNDFhNi05YTBjLTJjZWU1ZjJiZjhhMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyN1QwNzU2MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZjE2ZjRjYzY0MDYwYjNhNGMyZTdhMjBlMDhkZWI3MDdiNzZhM2VjNWU1ZTkxMzZhZTEwYTA3MzU4OWE2ZmEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.t2dZrflr3W3H-fi1ji6DJohlQFqvJ5bxwvYwcknEGEw)
> 
> 发送合并消息请求数据: {'group_id': 770626076, 'messages': [{'type': 'node', 'data': {'name': '小云儿', 'uin': 1094950020, 'content': [{'data': {'text': '测试'}, 'type': 'text'}]}}, {'type': 'node', 'data': {'name': '小云儿', 'uin': 1094950020, 'content': [{'data': {'id': '7385086735340206481'}, 'type': 'forward'}]}}]}
> 
> 如此引用是不是我引用的方式不对，不显示多层

消息id为短id

**Comment by ti-e** [comment]
{"group_id": 466651521, "messages": [{"type": "node", "data": {"name": "小云儿", "uin": 1094950020, "content": [{"data": {"text": "测试"}, "type": "text"}]}}, {"type": "node", "data": {"name": "小云儿", "uin": 1094950020, "content": [{"data": {"message_id": "-2147483401"}, "type": "forward"}]}}]}

{"group_id": 466651521, "messages": [{"type": "node", "data": {"name": "小云儿", "uin": 1094950020, "content": [{"data": {"text": "测试"}, "type": "text"}]}}, {"type": "node", "data": {"name": "小云儿", "uin": 1094950020, "content": [{"data": {"id": "-2147483401"}, "type": "forward"}]}}]}

是不是这样大佬，还是不显示。。
