### ISSUE TITLE
[BUG] 当我往没有@全体次数的群聊发送消息的时候，返回的数据包没有错误提示

### ISSUE THREAD

**Issue by Waldo-Schaeffer** [LLOneBot/LLOneBot#266]
### 系统版本

Windows Server 2022 Datacenter 21H2

### QQNT 版本

9.9.11-24568 (64位)

### LLOneBot 版本

2.26.5

### OneBot 客户端

python 3.10

### 发生了什么?

当我执行以下代码的时候：

```
def send_live_broadcast_notification_2(group_id, anchor_name, live_title, room_number, cover_visual_url):
    """
    发送开播提醒到指定的QQ群。

    参数:
    - group_id (int): QQ群号，消息发送的目标群。
    - anchor_name (str): 主播的昵称，将在消息中提及。
    - live_title (str): 直播间的标题，描述直播内容。
    - room_number (int): 直播间的房间号，可以用于生成直播间的链接。
    - cover_visual_url (str): 直播间封面图的URL，用于在消息中显示图像。

    功能描述:
    该函数构造一个包括主播的昵称、直播标题、直播房间号和封面图像URL的消息，
    并发送到指定的QQ群中，用于提醒群成员关注直播。
    """
    
    roomurl = "https://live.bilibili.com/" + str(room_number)
    mention_qq = "all"
    raw_message={
        "group_id": group_id,
        "message":f"[CQ:at,qq={mention_qq}]{anchor_name}正在直播【{live_title}】\r\n{roomurl}\r\n[CQ:image,file={cover_visual_url}]"
    }
    
    # 示例：发送消息的代码（请根据实际使用的库或框架调整）
    return send_group_message(raw_message).text

def send_group_message(raw_message):
    url="http://127.0.0.1:3000/send_group_msg"
    headers = {
        "Authorization":""
    }
    resp=requests.post(url=url,data=raw_message, headers=headers)
    print(resp.status_code)
    #print(resp.text)
    return resp

if __name__ == '__main__':
    group_id = 967986977
    anchor_name = "Astro-虎太"
    live_title = "乖乖宝宝"
    room_number = 31204569
    cover_visual_url = "https://i0.hdslb.com/bfs/live/user_cover/43a6d09671beb59c4460e8ff386f31e4e9c611a9.jpg"
    resp = send_live_broadcast_notification_2(967986977,anchor_name,live_title,room_number,cover_visual_url)
    #print(resp.status_code)
    print(resp)
```

服务器不管该账号是否能够@全体成员，都会发送该消息，如果没有@全体次数或者不是管理员，则会删除@全体后再发送消息。同时返回的数据都是HTTP 200，并附带以下json（message_id涉及隐私已隐藏），而这个json和正常发送消息完全一样：
{"status":"ok","retcode":0,"data":{"message_id":-1},"message":"","wording":"","echo":null}
这就导致了一个问题，导致了一个功能无法实现：
基于MariaGo框架的机器人会根据返回的信息，如果@全体失败会@指定管理员，让其他管理员手动@全体，但是LLOneBot似乎“容错做的过好太过智能了”，导致该功能无法实现，需要调取聊天记录，查询自己发送的信息，再次判断。在面对拥有接近2000个关注推送的情况下，多次调用会导致python程序和QQ占用的内存超过10GiB甚至20GiB，这简直就是灾难

### 如何复现

执行上面的代码，向一个群发送带有@全体的消息即可

### 期望的结果?

可以在返回的信息，比如message中，附带一个提示：消息发送成功，但是@全体失败，失败原因……
或者@某个人失败，失败原因（比如这个人不在群里了）

**Comment by linyuchen** [comment]
之前有人提过当@全体失败时，gocq是依然可以发的出去，但是@全体成员不生效而已，所以LLOneBot也是延续了这种风格。
我想应该有一个查询剩余@全体次数的接口会更好？

@一个不存在的群成员我记得是会返回错误信息的

**Comment by Waldo-Schaeffer** [comment]
> 之前有人提过当@全体失败时，gocq是依然可以发的出去，但是@全体成员不生效而已，所以LLOneBot也是延续了这种风格。 我想应该有一个查询剩余@全体次数的接口会更好？
> 
> @一个不存在的群成员我记得是会返回错误信息的

确实是可以发出去的，也确实是不生效的，但是返回的数据中包含了@全体失败但是发送成功的提示

**Comment by Waldo-Schaeffer** [comment]
> @一个不存在的群成员我记得是会返回错误信息的

另外实测：“@一个不存在的群成员”也并没有返回错误信息，而是和没有@全体次数一样，“没有返回错误信息”，并且去掉错误的@信息发送消息

**Comment by Waldo-Schaeffer** [comment]
> 之前有人提过当@全体失败时，gocq是依然可以发的出去，但是@全体成员不生效而已，所以LLOneBot也是延续了这种风格。 我想应该有一个查询剩余@全体次数的接口会更好？
> 
> @一个不存在的群成员我记得是会返回错误信息的

我的想法是，只需要返回错误信息即可

**Comment by idranme** [comment]
日志里有提示

**Comment by Waldo-Schaeffer** [comment]
> 日志里有提示

作为使用HTTP调用的程序，本身不可能去读取日志文件，尤其是这个程序不可能在服务器localhost上运行。
疑问：您指的是不是：事件？

**Comment by idranme** [comment]
你想要在没有次数时中断发送吗？

**Comment by Waldo-Schaeffer** [comment]
> 现在 LLOneBot 已支持 `/get_group_at_all_remain` API，你可以在发送前查询次数。

是，我希望在@全体失败的时候，直接返回提示：没有@全体次数，但是发送成功/失败
因为我之前的程序逻辑是：如果是发送成功，则单独再发一条@指定人的消息，用意是帮忙@全体。如果发送失败，则直接修改发送内容，把@全体改为@指定管理员，用意相同

**Comment by idranme** [comment]
> > 现在 LLOneBot 已支持 `/get_group_at_all_remain` API，你可以在发送前查询次数。
> 
> 是，我确实希望中断发送（以前就是这么写的），我希望在@全体失败的时候，直接返回提示：没有@全体次数，但是发送成功/失败 因为我之前的程序逻辑是：如果是发送成功，则单独再发一条@指定人的消息，用意是帮忙@全体。如果发送失败，则直接修改发送内容，把@全体改为@指定管理员，用意相同

我担心这样中断发送，可能有一些 bot 会炸，所以还是建议用 `/get_group_at_all_remain` 查一下。

**Comment by Waldo-Schaeffer** [comment]
> > > 现在 LLOneBot 已支持 `/get_group_at_all_remain` API，你可以在发送前查询次数。
> > 
> > 
> > 是，我确实希望中断发送（以前就是这么写的），我希望在@全体失败的时候，直接返回提示：没有@全体次数，但是发送成功/失败 因为我之前的程序逻辑是：如果是发送成功，则单独再发一条@指定人的消息，用意是帮忙@全体。如果发送失败，则直接修改发送内容，把@全体改为@指定管理员，用意相同
> 
> 我担心这样中断发送，可能有一些 bot 会炸，所以还是建议用 `/get_group_at_all_remain` 查一下。

可以单独加一个可传递的参数吗？如果没有这个参数默认不中断
