### ISSUE TITLE
[Suggestion]希望在发送http文件时，下载文件的http header增加referer保证文件能正常下载

### ISSUE THREAD

**Issue by kaikaiblog** [LLOneBot/LLOneBot#268]
### 系统版本

Win11

### QQNT 版本

9.9.11-24568

### LLOneBot 版本

2.26.6

### OneBot 客户端

1

### 发生了什么?

通过直链发送视频时，有一些直链需要referer才可以下载发送，希望在发送视频时可以选择增加协议头

### 如何复现

发送抖音视频直链即可复现

### 期望的结果?

希望在发送视频时可以选择增加协议头

**Comment by idranme** [comment]
可以调用 `/download_file` API，支持传入 header
