### ISSUE TITLE
[BUG] message_id 和 real_id 的值异常

### ISSUE THREAD

**Issue by Cola-Ace** [LLOneBot/LLOneBot#269]
### 系统版本

Windows Server 2022 Datacenter

### QQNT 版本

9.9.11-24568

### LLOneBot 版本

3.26.7

### OneBot 客户端

Koishi v4.17.9 -> adapter-onebot v6.5.8

### 发生了什么?

使用ws接收消息事件时 `message_id` 和 `real_id` 参数的值均为int的 `-2147482433` ，只有开启了调试模式后才会在 `raw` 参数里正常显示id，翻看之前的issue发现可能是string转int导致的问题，恳请解决一下这个问题

### 如何复现

使用ws接收消息事件时均会触发

### 期望的结果?

正常显示string类型的id

**Comment by linyuchen** [comment]
id负数是正常的，LLOneBot的message_id就是从int32最小值开始递增的
