### ISSUE TITLE
[BUG] get_stranger_info获取不到好友，经过测试，只能获取到同一个群的群友信息（就算没有添加此群友）

### ISSUE THREAD

**Issue by VAHua** [LLOneBot/LLOneBot#270]
### 系统版本

Windows 10

### QQNT 版本

版本: 9.9.9-23424 (64位)

### LLOneBot 版本

3.26.7

### OneBot 客户端

onebot11

### 发生了什么?

get_stranger_info获取不到好友，经过测试，只能获取到同一个群的群友信息（就算没有添加此群友）
连接时用的nonebot

### 如何复现

调用接口get_stranger_info，获取好友昵称
![image](https://github.com/LLOneBot/LLOneBot/assets/129832780/65124550-db87-4686-a132-128199249e62)

### 期望的结果?

正确获取好友的信息

**Comment by idranme** [comment]
v3.29.3 是否存在该问题？
