### ISSUE TITLE
[Question] 图片消息的文件名被当做了文本消息处理？

### ISSUE THREAD

**Issue by smc0329** [LLOneBot/LLOneBot#274]
### 系统版本

Windows Server 2019

### QQNT 版本

9.9.10-24108

### LLOneBot 版本

3.26.7

### OneBot 客户端

XinxinCustomMessage-1.0.5-SNAPSHOT

### 发生了什么?

我设定关键词是ip,当机器人检测到有人在群内发ip这个词,机器人就会回复ip地址
但当群友发一个文件名为"iqshipdj.png"的图片
机器人也会回复ip地址

### 如何复现

当群友发一个文件名为"iqshipdj.png"的图片
机器人也会回复ip地址

### 期望的结果?

希望LLOneBot添加“不检测文件名”按钮
开启后，机器人将不会检测群友在群内发送的文件名

**Comment by linyuchen** [comment]
图片消息的文件名被当做了文本消息处理 这是你插件端的问题
