### ISSUE TITLE
无法在最新版本qq上使用

### ISSUE THREAD

**Issue by touchscale** [LLOneBot/LLOneBot#275]
![mmexport1720195319409.jpg](https://github.com/LLOneBot/LLOneBot/assets/107158734/594e8bba-5964-4198-ab5c-49b8c5ec38fa)

LLOnebot版本：3.26.7
LiteLoaderQQNT版本：1.1.2
出现报错的QQ版本：9.9.11.24568
目前回退到9.9.10.24108版本可以正常使用

**Comment by MliKiowa** [comment]
关闭戳一戳 到插件config去改

**Comment by touchscale** [comment]
> 关闭戳一戳 到插件config去改

我试试

**Comment by touchscale** [comment]
关闭后可以了，但还是希望能做下适配
