### ISSUE TITLE
[BUG] cpu占用高

### ISSUE THREAD

**Issue by wa684572** [LLOneBot/LLOneBot#276]
### 系统版本

windows 11

### QQNT 版本

9.9.11-24815

### LLOneBot 版本

3.26.7

### OneBot 客户端

1

### 发生了什么?

为什么开启LLOneBot这个插件，cpu占用这么高，导致QQ很卡，这不正常吧，下面启用插件后cpu截图，是不是哪有死循环，把这个插件禁用就正常（cpu占用只有10多%）
![图片](https://github.com/LLOneBot/LLOneBot/assets/65830052/6df4aa56-f92e-4b5d-a74a-93f3aca0b8a1)

### 如何复现

启用插件

### 期望的结果?

cpu占用正常

**Comment by wa684572** [comment]
这是不是因为群太多的原因，我两千+的群五十多个，其他的四百多个，是不是获取完了就不卡了

**Comment by linyuchen** [comment]
> 这是不是因为群太多的原因，我两千+的群五十多个，其他的四百多个，是不是获取完了就不卡了，是不是每次重新打开QQ都要获取一次

是的，打开QQ后会获取群列表，如果群比较多会占用CPU较高，获取完之后恢复正常
