### ISSUE TITLE
[BUG]  无法发送含有URL的图片

### ISSUE THREAD

**Issue by tianxiu2b2t** [LLOneBot/LLOneBot#277]
### 系统版本

Windows 10

### QQNT 版本

9.9.11-24815 (64位)

### LLOneBot 版本

3.26.7

### OneBot 客户端

Python Websocket

### 发生了什么?

无法发送含有URL的图片

### 如何复现

{"action": "send_group_msg", "params": {"group_id": 979914630, "message": [{"type": "image", "data": {"file": "https://bangbang93.ttb-network.top:4000/files/1.png"}}]}, "echo": "11eb1f52-659a-419f-a66f-48d194a5b05b"}

例如

网址是https://bangbang93.ttb-network.top:4000/files/1.png

### 期望的结果?

能发生url图片

**Comment by linyuchen** [comment]
LLOneBot实现了发送url文件的，可能是ssl证书问题导致的无法下载你这个url，检查你的域名证书问题
