### ISSUE TITLE
请求实现能配置http监听指定端口的配置 而不是0.0.0.0

### ISSUE THREAD

**Issue by rongrong1000** [LLOneBot/LLOneBot#282]
请求实现能配置http server 监听指定host的配置 而不是0.0.0.0

**Comment by idranme** [comment]
![image](https://github.com/user-attachments/assets/44aba69d-9469-4983-96ac-632350dfa7e7)
可以监听指定端口

**Comment by 3CB3EC** [comment]
> 请求实现能配置http server 监听指定host的配置 而不是0.0.0.0

默认好像是127.0.0.1而不是0.0.0.0

**Comment by 3CB3EC** [comment]
> ![image](https://private-user-images.githubusercontent.com/96647698/354912901-44aba69d-9469-4983-96ac-632350dfa7e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MTAwNzgsIm5iZiI6MTczNDUwOTc3OCwicGF0aCI6Ii85NjY0NzY5OC8zNTQ5MTI5MDEtNDRhYmE2OWQtOTQ2OS00OTgzLTk2YWMtNjMyMzUwZGZhN2U3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDA4MTYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiYmMxODcwODkxYjIwNTQ1NjljYjAyOGQwZDgzY2Q4YWZhNGE4NWIzYWIyMTdiMGRhYWUwZGU5ZTMwMzVmYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1KLDtytkpj5vRPydA5cemyYLeJzd1pK1CgRSs6dizFk) 可以监听指定端口

好像理解错问题了

**Comment by linyuchen** [comment]
现在已经有这个配置项了
![image](https://github.com/user-attachments/assets/d8c037f6-cbc7-4a4b-8424-c206debe64f9)
