### ISSUE TITLE
【建议】每个账号可以单独控制开关

### ISSUE THREAD

**Issue by QwindF** [LLOneBot/LLOneBot#284]
电脑上登入了两个qqnt
机器人的群聊少，开llonebot没什么问题。
问题是我常用的账号（不需要做机器人），一加载llonebot就十分的卡顿。
有没有办法单独关掉一个账号的llonebot。
我现在是先启动机器人账号，然后再把llonebot关掉再启动主账号，但是感觉太麻烦了。
希望每个账号可以单独控制开关

**Comment by linyuchen** [comment]
现在没有这样的功能，你可以安装两份QQ，bot账号的QQ只装LLOneBot

**Comment by QwindF** [comment]
> 现在没有这样的功能，你可以安装两份QQ，bot账号的QQ只装LLOneBot

现在代码不是可以每个qq一个配置文件吗。
可不可以在配置文件里面添加一个关闭的选项。

**Comment by linyuchen** [comment]
v3.27.0已支持

**Comment by QwindF** [comment]
> Referen

非常感谢，登上去等了半天重要关掉了。
也可以在配置文件的最好加上`"enableLLOB": false`关闭
