### ISSUE TITLE
[BUG] linux arm qq 似乎完全不起作用

### ISSUE THREAD

**Issue by sckiyo** [LLOneBot/LLOneBot#285]
### 系统版本

Debian Bookworm

### QQNT 版本

3.2.9-24815

### LLOneBot 版本

3.26.7

### OneBot 客户端

仅发送http post&仅websocket接受事件

### 发生了什么?

瑞芯微rk3566arm64处理器的开发板。

直接使用websocket连接，除了{"post_type":"meta_event","meta_event_type":"lifecycle","sub_type":"connect"}和{"post_type":"meta_event","meta_event_type":"heartbeat","status":{"online":true,"good":true},"interval":60000}之外，接收不到任何事件。

直接使用http post调用api，除了能获取到登录号信息，其他的也用不了：
![屏幕截图 2024-07-08 222155](https://github.com/LLOneBot/LLOneBot/assets/118417762/463b3dc5-f75c-44e7-84bd-d6d5e2b91ed9)
![68422438](https://github.com/LLOneBot/LLOneBot/assets/118417762/17419241-6ed2-4b86-b042-71cd984ebf6c)

### 如何复现

1、发送http post
2、websocket连接

### 期望的结果?

能正常接收事件、调用api

### LLOneBot 运行日志

```shell
2024/7/8 22:43:25 (): 收到http请求 /get_login_info {} 

2024/7/8 22:43:25 (): 收到http请求 /get_friend_list {} 

2024/7/8 22:43:30 (): ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelBuddyService/getBuddyList ["nodeIKernelBuddyService/getBuddyList",{"force_update":true},null] 

2024/7/8 22:43:30 (): 发生错误 ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelBuddyService/getBuddyList, nodeIKernelBuddyService/getBuddyList,[object Object], 

2024/7/8 22:43:30 (): 收到http请求 /get_group_list {} 

2024/7/8 22:43:35 (): ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelGroupService/getGroupList ["nodeIKernelGroupService/getGroupList",{"force_update":true},null]
```

**Comment by linyuchen** [comment]
降低QQ版本试试？

**Comment by BailPlus** [comment]
同样问题。使用HTTP上报只有心跳事件可以正常上报，但接收HTTP请求似乎全部支持

**Comment by idranme** [comment]
v3.29.5 是否存在该问题？

**Comment by sckiyo** [comment]
> v3.29.5 是否存在该问题？

http调用好像好了，试了几个api没发现问题，websocket仍然只能接收到meta_event。NTQQ版本3.2.12-26909。

**Comment by idranme** [comment]
v3.30.0 已修复
