### ISSUE TITLE
[BUG] 无法收到撤回事件上报

### ISSUE THREAD

**Issue by LuoRenMu** [LLOneBot/LLOneBot#289]
### 系统版本

Windows 11 专业版 23H2

### QQNT 版本

9.9.11-24568 (64位)

### LLOneBot 版本

3.26.7

### OneBot 客户端

HTTP

### 发生了什么?

group和private 都无法正常收到撤回事件的上报

### 如何复现

在框架的帮助下我发现无法正常处理撤回消息 我搭建了一个简单的HTTP服务接收上报信息 发现无法收到撤回信息

### 期望的结果?

上报撤回信息

**Comment by linyuchen** [comment]
3.27.1 fixed

**Comment by idranme** [comment]
v3.29.3 是否存在该问题？

**Comment by idranme** [comment]
> 测试最新版v3.30.5无法收到撤回上报

更新一下 QQ

**Comment by LuoRenMu** [comment]
> > 测试最新版v3.30.5无法收到撤回上报
> 
> 更新一下 QQ

我将LiteLoaderNT 及 QQ 全部更新到最新版依然无法收到

**Comment by linyuchen** [comment]
你装了防撤回插件？

**Comment by LuoRenMu** [comment]
感谢您的帮助 确实是因为防撤回导致无法正常上报
