### ISSUE TITLE
[BUG] 戳一戳变加好友事件

### ISSUE THREAD

**Issue by cnxysoft** [LLOneBot/LLOneBot#291]
### 系统版本

Windows 11 专业版 23H2

### QQNT 版本

9.9.12-25765

### LLOneBot 版本

3.27.1

### OneBot 客户端

Miao-Yunzai(自修改适配器)/Apifox

### 发生了什么?

好友poke消息变成了friend_add消息
{
    "time": 1720872806,
    "self_id": 1143469507,
    "post_type": "notice",
    "notice_type": "friend_add",
    "user_id": 0
}

### 如何复现

直接进行私聊戳一戳即可

### 期望的结果?

正确收到poke事件通知

**Comment by linyuchen** [comment]
v3.27.2 fixed
