### ISSUE TITLE
[BUG] LLOneBot导致QQNT严重卡顿

### ISSUE THREAD

**Issue by jsrcode** [LLOneBot/LLOneBot#296]
### 系统版本

Windows 11 专业版

### QQNT 版本

9.9.11-24568

### LLOneBot 版本

3.27.2

### OneBot 客户端

自建客户端

### 发生了什么?

打开LLOneBot之后QQNT前端变得非常卡顿 已经等待很久但是还是存在严重卡顿

### 如何复现

打开LLOneBot

### 期望的结果?

不卡顿

**Comment by idranme** [comment]
[v3.28.1](https://github.com/LLOneBot/LLOneBot/releases/tag/v3.28.1) 已修复
