### ISSUE TITLE
[BUG] 启动后非常卡顿，QQ自身功能都加载不出来

### ISSUE THREAD

**Issue by 1244453393** [LLOneBot/LLOneBot#297]
### 系统版本

Windows 11 Pro 22H2

### QQNT 版本

9.9.12-25765

### LLOneBot 版本

3.27.2

### OneBot 客户端

自建

### 发生了什么?

启用插件后，QQ非常卡顿，QQ自身功能都加载不全

### 如何复现

启用LLOneBot，登录QQ

### 期望的结果?

不卡顿，功能正常

**Comment by xlnrm3344556677** [comment]
是这样的，我打开qq之后侧边栏都加载不全，拖动和点击页面都没反应

**Comment by QwindF** [comment]
大概率是群，好友过多，除非关闭
#284

**Comment by 1244453393** [comment]
> 大概率是群，好友过多，除非关闭 #284

算了吧，我只用的3.26.x版本，一点不卡，换3.27.x就这样

**Comment by idranme** [comment]
[v3.28.1](https://github.com/LLOneBot/LLOneBot/releases/tag/v3.28.1) 已修复
