### ISSUE TITLE
[BUG] 申请加群消息中的user_id字段值为0

### ISSUE THREAD

**Issue by zhongjianhua163** [LLOneBot/LLOneBot#298]
### 系统版本

Windows 10 家庭中文版 22H2

### QQNT 版本

9.9.12-25493 (64位)

### LLOneBot 版本

3.27.2

### OneBot 客户端

无

### 发生了什么?

收到的加群消息上报如下，user_id字段一直是0，不知道是谁申请的加群。

{
  time: 1721306985,
  self_id: 123456789,
  post_type: 'request',
  group_id: 12345678,
  user_id: 0,
  request_type: 'group',
  sub_type: 'add',
  comment: '啊啊啊',
  flag: '1721306984123456'
}

### 如何复现

申请加群

### 期望的结果?

我需要user_id来判断此人是否在指定群中，从而进行不同的处理

**Comment by zhongjianhua163** [comment]
看了一下日志，内容如下：

`2024/7/20 16:42:08 yuki(1234567): 收到群通知 {"seq":"1721464927468817","type":7,"status":1,"group":{"groupCode":"654321","groupName":"xx群"},"user1":{"uid":"u_Nn_wnFhW23H2tkl-dgNVdg","nickName":"欲难止"},"user2":{"uid":"","nickName":""},"actionUser":{"uid":"","nickName":""},"actionTime":"0","invitationExt":{"srcType":0,"groupCode":"0","waitStatus":0},"postscript":"xw q ","repeatSeqs":["1721460237976770","1721460317272691","1721464613888333"],"warningTips":"","time":1721464928321} 

2024/7/20 16:42:08 yuki(1234567): 有加群请求 

2024/7/20 16:42:08 yuki(1234567): nodeIKernelProfileService/getUserDetailInfoWithBizInfo callback {"result":0,"errMsg":"success"} 

2024/7/20 16:42:08 yuki(1234567): nodeIKernelGroupService/getSingleScreenNotifies callback {"result":0,"errMsg":""} 

2024/7/20 16:47:10 yuki(1234567): 新消息事件HTTP上报失败(这是我调试断点太久导致的): http://127.0.0.1:40001  {} {"time":1721464928,"self_id":1234567,"post_type":"request","group_id":654321,"user_id":0,"request_type":"group","sub_type":"add","comment":"xw q ","flag":"1721464927468817"} 
`

**Comment by idranme** [comment]
v3.29.3 是否存在该问题？

**Comment by WJHXD1B** [comment]
> v3.29.3 是否存在该问题？

我也遇到此问题
系统版本
Windows 10 专业工作站版 22H2

QQNT 版本
9.9.15-27391 (64位)

LLOneBot 版本
3.31.1

OneBot 客户端
无

发生了什么?

{
    "time": 1724926678,
    "self_id": 3960701xxx,
    "post_type": "request",
    "request_type": "group",
    "sub_type": "add",
    "comment": "问题：xxxxxx\n答案：xxxxxxxxxx",
    "flag": "856407924|1724926677804396|7",
    "group_id": 856407xxx,
    "user_id": 0
}

"user_id"为0，无法获取qq number

如何复现
申请加群

Comment
liteloder为1.2.1
我需要user_id来记录加群人员，从而进行判断

**Comment by nsonline** [comment]
遇到同样问题，查看日志有报错：
onebot 获取加群人QQ号失败 Uid: u_KPYpmiCuQg5Hz5g_Y2czpg TypeError: Cannot read properties of undefined (reading 'get') at Proxy.getUinByUidV2

LLOneBot/3.31.1
QQ： 版本: 9.9.15-27391 (64位)

**Comment by idranme** [comment]
v3.31.3 已修复
