### ISSUE TITLE
[BUG] 即使安装修复过的版本后QQNT还是很卡

### ISSUE THREAD

**Issue by wuhaiqi0621** [LLOneBot/LLOneBot#305]
### 系统版本

Win11 专业版 23H2

### QQNT 版本

9.9.12-25493

### LLOneBot 版本

3.27.3

### OneBot 客户端

未连接也会卡

### 发生了什么?

每次启动qq都要加载5~10分钟，功能全都加载不出来，但是关闭OneBot就不会卡……

### 如何复现

开启OneBot的情况下 启动qqnt

### 期望的结果?

不卡顿！！！！！！！

**Comment by 1244453393** [comment]
至今未解决

**Comment by 1244453393** [comment]
今天仍然卡顿，难受

**Comment by idranme** [comment]
[v3.28.1](https://github.com/LLOneBot/LLOneBot/releases/tag/v3.28.1) 已修复

**Comment by 1244453393** [comment]
> [v3.28.1](https://github.com/LLOneBot/LLOneBot/releases/tag/v3.28.1) 已修复

3.268.2更卡了。。。。

**Comment by idranme** [comment]
> 3.28.6 更卡了。。。。

QQ版本是多少？

**Comment by 1244453393** [comment]
> > 3.28.6 更卡了。。。。
> 
> QQ 版本是多少？

9.9.12-25765 (64位)

**Comment by idranme** [comment]
> 9.9.12-25765 (64位)，我的好友和群确实多，但是在3.26.x的时候没卡过

试下 9.9.15

**Comment by ixubin** [comment]
刚更新了最新版本：9.9.15-28327 (64位)，依旧很卡呀。
之前的qq多流畅，怎么升级到nt后卡成这样了。
点个鼠标卡半天，我这还是64G内存的机器，搞毛呢！！
