### ISSUE TITLE
[BUG] 用liteloaderqqnt无法安装llonebot

### ISSUE THREAD

**Issue by zxy393360027** [LLOneBot/LLOneBot#313]
### 系统版本

windows 10 2016

### QQNT 版本

9.9.12-26466

### LLOneBot 版本

3.27.3

### OneBot 客户端

暂无

### 发生了什么?

用一件脚本安装好liteloaderqqnt后，能看见plugins文件夹里有llonebot，但安装不上去，其他所有的插件都可以正常安装

### 如何复现

liteloader 1.2.0 qqnt 9.912-26466 electron 31.0.1 chromium 126.0.6478.36 node.js 20.14.0

### 期望的结果?

.

### LLOneBot 运行日志

```shell
.
```

### OneBot 客户端运行日志

```shell
.
```

**Comment by linyuchen** [comment]
截图看下plugins文件夹以及LLOneBot文件夹内的内容

**Comment by zxy393360027** [comment]
![08df13e3f199b303238b2669851bc9a6](https://github.com/user-attachments/assets/3a2ae31d-a249-44c2-b397-a700551ff170)
![513a086b04f804a6bb30a6d04bd6e639](https://github.com/user-attachments/assets/72221faf-e7bd-4b64-9976-775715e550cb)
三个llonebot文件夹内容都是一样的。。可能我在插件列表文件夹里点了几次下载就有三个了。我是在云主机上装的，跟这个有关系吗

**Comment by linyuchen** [comment]
你下载的 LLOneBot 是源码，不是编译好的，到 release 里面下载

**Comment by zxy393360027** [comment]
可以了，谢谢大佬！！！     我是猪鼻~
