### ISSUE TITLE
[Feature Requested] 请求增加设置专属头衔的API支持

### ISSUE THREAD

**Issue by KyuubiRan** [LLOneBot/LLOneBot#334]
### 系统版本
Windows 11 家庭中文版 23H2    
### Liteloader版本
1.2.1
### LLOneBot 版本    
3.28.6
### QQ版本    
9.9.12-26466

### 功能请求
希望能增加对`set_group_special_title`的支持

### 参数

| 字段名 | 数据类型 | 默认值 | 说明 |
| ----- | ------- | ----- | --- |
| `group_id` | number | - | 群号 |
| `user_id` | number | - | 要设置的 QQ 号 |
| `special_title` | string | 空 | 专属头衔，不填或空字符串表示删除专属头衔 |
| `duration` | number | `-1` | 专属头衔有效期，单位秒，-1 表示永久，不过此项似乎没有效果，可能是只有某些特殊的时间长度有效，有待测试 |

### 响应数据

无

**Comment by KyuubiRan** [comment]
同时请求修复一下 #309 的问题 获取群员的某些信息不正确（比如加群、最后发言、群聊等级等）

**Comment by xihan123** [comment]
桌面NTQQ都还没出这个功能吧，都不存在的功能咋支持

**Comment by linyuchen** [comment]
4.2.0以上版本已支持
