### ISSUE TITLE
get_group_list 和 get_group_info 没有群备注名称

### ISSUE THREAD

**Issue by DeonLU** [LLOneBot/LLOneBot#353]
### 系统版本

Windows 11 企业版 23H2

### QQNT 版本

9.9.15-26909 (64位)

### LLOneBot 版本

3.29.5

### OneBot 客户端

3.29.5

### 发生了什么?

1. /get_group_list 和/get_group_info 没有群备注名称
2. 修改群备注没有上报事件

### 如何复现

get_group_list
get_group_info
这两个接口返回的数据中没有群备注名称

### 期望的结果?

get_group_list
get_group_info
希望这两个接口返回的数据中添加群备注名称并且添加群备注名称修改上报事件

**Comment by idranme** [comment]
v3.31.7 已修复
