### ISSUE TITLE
get_cookies 接口，本地可以获取到正确的cookie，部署到服务器不能get到正确的cookie[BUG] 

### ISSUE THREAD

**Issue by Blankdsad** [LLOneBot/LLOneBot#356]
### 系统版本

linux windows 12

### QQNT 版本

9.9.12-25765

### LLOneBot 版本

3.27.3

### OneBot 客户端

v3.27.3

### 发生了什么?

使用的http上报 ，本地起服务，get_cookies 能够拿到，部署到linux windows 12 后不能获得到正确的cookie

### 如何复现

本地起服务，get_cookies 能够拿到，部署到linux windows 12 后不能获得到正确的cookie

### 期望的结果?

均能get到 正确的cookie值

**Comment by idranme** [comment]
v3.29.6 是否存在该问题？

**Comment by Blankdsad** [comment]
> Collaborator

目前还没有升级 到最新版

**Comment by idranme** [comment]
> 目前还没有升级 到最新版

等你升了再说

**Comment by Blankdsad** [comment]
> > 目前还没有升级 到最新版
> 
> 等你升了再说

![QQ_1724232068588](https://github.com/user-attachments/assets/8725067e-c3e1-4254-84d2-e5f5dc7a2b98)
 还是 不一致，bkn 也不对

**Comment by Blankdsad** [comment]
补充 v3.27.3 是正常，新版本有问题
