### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by GongQiang2021** [LLOneBot/LLOneBot#359]
### 系统版本

windows11专业版

### QQNT 版本

9.9.12-26466

### LLOneBot 版本

3.296

### OneBot 客户端

1.2.1

### 发生了什么?

1、LLOneBot已部署，get请问3000端口 LLOneBot server 已启动
2、Post调用/send_private_msg 超时
{
    "user_id":"xxxxxx",
    "message":[
        {
            "type":"text",
            "data":{
                "text":"测试通过，没问题"
            }
        }
    ]
}

### 如何复现

1、部署LLOneBot
2、登录QQ 添加指定好友id xxxxx
3、ApiFox调用localhost:3000/send_private_msg post请求 body如下：
{
    "user_id":"xxxx",
    "message":[
        {
            "type":"text",
            "data":{
                "text":"测试通过，没问题"
            }
        }
    ]
}

### 期望的结果?

发送date的内容给指定的QQ好友

### LLOneBot 运行日志

```shell
2024/8/22 11:31:26 undefined(3804694509): 收到 HTTP 请求 /clean_cache {} 

2024/8/22 11:31:40 undefined(3804694509): 收到 HTTP 请求 /send_private_msg {"user_id":"739141633","message":[{"type":"text","data":{"text":"测试通过，没问题"}}]}
```

**Comment by idranme** [comment]
没能复现
