### ISSUE TITLE
[BUG] 换一个qq登录就要重新添加一次上报地址?

### ISSUE THREAD

**Issue by ChinaPhusun** [LLOneBot/LLOneBot#371]
### 系统版本

1

### QQNT 版本

1

### LLOneBot 版本

3.30.5

### OneBot 客户端

1

### 发生了什么?

如题,比如刚开始登录了一个QQ 12345 添加了一个上报地址,,,,如果退出来换一个67890的qq号登录,,那么之前添加的上报地址会没有了,需要重新添加.,,

### 如何复现

如题,比如刚开始登录了一个QQ 12345 添加了一个上报地址,,,,如果退出来换一个67890的qq号登录,,那么之前添加的上报地址会没有了,需要重新添加.,,

### 期望的结果?

能不能添加一次之后通用.不管登录哪个号码都不需要再重复添加了?

### LLOneBot 运行日志

```shell
1
```

### OneBot 客户端运行日志

```shell
1
```

**Comment by idranme** [comment]
每个账号的配置是独立的
