### ISSUE TITLE
[BUG] 无法检测退群消息

### ISSUE THREAD

**Issue by Momoi-coder** [LLOneBot/LLOneBot#379]
### 系统版本

WIN 11家庭版

### QQNT 版本

9.9.12-26466（64位）

### LLOneBot 版本

3.31.1

### OneBot 客户端

onebot v11

### 发生了什么?

一个别人写的插件，检测到有人退群，机器人就会发送消息说谁谁谁退群了，但是现在机器人窗口看不到别人退群了，进群倒是可以看到

### 如何复现

import random
from subprocess import run
import json
import requests
import psutil
import os, sys, builtins, threading
import nonebot
from nonebot.rule import Rule
from nonebot import get_driver, on_request, on_notice, on_command, on_message
from nonebot.adapters.onebot.v11 import Bot, GroupIncreaseNoticeEvent, \
    MessageSegment, Message, GroupMessageEvent, Event, NoticeEvent, GroupDecreaseNoticeEvent, GroupRecallNoticeEvent
from nonebot.matcher import Matcher
from nonebot.params import ArgPlainText, CommandArg, ArgStr

superuser = int(list(get_driver().config.superusers)[0])

requests_handle = on_request(priority=5, block=True)

def INCchecker():
    async def _checker(bot: Bot, event: GroupIncreaseNoticeEvent) -> bool:
        return True
    return Rule(_checker)

inc = on_notice(rule=INCchecker(), priority=1, block=True)

@inc.handle()
async def GroupNewMember(bot: Bot, event: GroupIncreaseNoticeEvent):
    # s = str(event.get_event_description())
    # await inc.send(s, at_sender=True)
    # s = str(event.get_event_name())
    # await inc.send(s, at_sender=True)
    if event.user_id == event.self_id:
        await bot.send_group_msg(group_id=event.group_id, message=Message(
            MessageSegment.text('邦邦卡邦！爱丽丝来啦！') + MessageSegment.face(318)))
    else:
        await bot.send_group_msg(group_id=event.group_id, message=Message(
            MessageSegment.at(event.user_id) + MessageSegment.text("  邦邦卡邦！！！有新成员加入到勇者爱丽丝的队伍中啦！！") + MessageSegment.face(318) + MessageSegment.image("D:\\Desktop\\bluearchive\\bbkb.jpg")))

def DECchecker():
    async def _checker(bot: Bot, event: GroupDecreaseNoticeEvent) -> bool:
        return True
    return Rule(_checker)

inc = on_notice(rule=DECchecker(), priority=1, block=True)

@inc.handle()
async def GroupDECMember(bot: Bot, event: GroupDecreaseNoticeEvent):
    if event.user_id == event.self_id:
        # 被踢了
        pass
    else:
        await bot.send_group_msg(group_id=event.group_id, message=Message(MessageSegment.at(event.user_id) + MessageSegment.text(f"（QQ号：{event.user_id}）退群了🥺") + MessageSegment.image("D:\\Desktop\\bluearchive\\momoi.jpg")))

### 期望的结果?

能检测到别人退群，并且返回消息

**Comment by Momoi-coder** [comment]
管理员可以，非管理员不行，但是之前我用napcat的时候，非管理员也可以，不知道为什么

**Comment by idranme** [comment]
非管理员的话，应该算正常吧…
