### ISSUE TITLE
[BUG] 无法下载抖音视频

### ISSUE THREAD

**Issue by duiaic** [LLOneBot/LLOneBot#380]
### 系统版本

win2012

### QQNT 版本

9.9.15-27333

### LLOneBot 版本

3.30.5

### OneBot 客户端

0.0.01

### 发生了什么?

解析短视频，llo无法下载抖音视频，其他平台都正常下载。抖音的视频直连地址通过手机电脑都能访问。

### 如何复现

正常解析视频。就是不能下载视频发送出来。
没别的了。

### 期望的结果?

希望修复一下，其他平台都正常能下载。

**Comment by idranme** [comment]
可以联系抖音解决
