### ISSUE TITLE
[BUG] send_group_msg 无法发送图片

### ISSUE THREAD

**Issue by zzy-plus** [LLOneBot/LLOneBot#382]
### 系统版本

Windows Server 2022

### QQNT 版本

9.9.15-26909

### LLOneBot 版本

3.29.2

### OneBot 客户端

http

### 发生了什么?

http服务：使用/send_group_msg 无法发送图片。
发送图片的代码：
`resp = requests.get(url + '/send_group_msg?' + f'group_id={group_id}&message=[CQ:image,file={filename},type=show,id=4000]')`
确定filename指向的文件存在

返回信息为：
`{'status': 'failed', 'retcode': 200, 'data': None, 'message': "Error: ENOENT: no such file or directory, open 'C:\\Users\\Administrator\\LiteLoaderQQNT-main\\data\\LLOneBot\\temp\\005e00f1-317a-4f34-955e-b1ac3bffb07e'", 'wording': "Error: ENOENT: no such file or directory, open 'C:\\Users\\Administrator\\LiteLoaderQQNT-main\\data\\LLOneBot\\temp\\005e00f1-317a-4f34-955e-b1ac3bffb07e'", 'echo': None}`
要发送的图片不在 **C:\\Users\\Administrator\\LiteLoaderQQNT-main\\data\\LLOneBot\\temp\\** 这个目录下

**在未更新LLOneBot以前（版本忘了）可以正常发送图片**
**在另一台设备上（windows 11、QQ9.9.15-27333、LLOneBot3.31.2）使用该api功能正常**

### 如何复现

不知道

### 期望的结果?

无报错信息，图片正常发送

### LLOneBot 运行日志

```shell
2024/8/30 17:10:43 undefined(2817004705): 收到http请求 /send_group_msg {"group_id":"852654526","message":"[CQ:image,file=C:\\Users\\Administrator\\Desktop\\botTest\\dragon\\1.jpg,type=show,id=4000]"} 

2024/8/30 17:10:43 undefined(2817004705): 发生错误 {"errno":-4058,"code":"ENOENT","syscall":"open","path":"C:\\Users\\Administrator\\LiteLoaderQQNT-main\\data\\LLOneBot\\temp\\b49342d2-d8f8-4d0f-9eaf-defbaad79a17"}
```

**Comment by idranme** [comment]
更新 llonebot 到最新版

**Comment by zzy-plus** [comment]
> 更新 LLOneBot 到最新版

OK 问题解决。
