### ISSUE TITLE
[BUG] 群聊撤回消息API失效

### ISSUE THREAD

**Issue by bianyuan456** [LLOneBot/LLOneBot#384]
### 系统版本

windows 11

### QQNT 版本

9.9.15-27391

### LLOneBot 版本

3.31.3

### OneBot 客户端

3.31.3

### 发生了什么?

群聊撤回消息API失效

### 如何复现

发消息，用API撤回，返回成功，但是没有撤回！

### 期望的结果?

应该撤回成功呀

### LLOneBot 运行日志

```shell
2024/9/1 14:28:17 [info] l❤d(๑❛ᴗ❛๑)(1603751153) | onebot 收到 HTTP 请求 /delete_msg { message_id: '117548639' }

2024/9/1 14:29:09 [info] l❤d(๑❛ᴗ❛๑)(1603751153) | onebot 收到 HTTP 请求 /delete_msg { message_id: '1066925466' }

{"status":"ok","retcode":0,"message":"","wording":""}
```

**Comment by idranme** [comment]
没能复现

**Comment by bianyuan456** [comment]
> 没能复现

抱歉，我忘了给管理员权限，我把管理员权限给错人了。。哈哈，我的问题

**Comment by EatHatsuneShallots** [comment]
> 抱歉，我忘了给管理员权限

是指非管理员撤回别人的消息吗？如果是的话，响应是有问题的（不应该是 `status:ok` ）

**Comment by bianyuan456** [comment]
> > 抱歉，我忘了给管理员权限
> 
> 是指非管理员撤回别人的消息吗？如果是的话，响应是有问题的（不应该是 `"status":"ok"` ）

是的，非管理员撤回别人的消息，返回的是成功的结果。应该返回失败，而且注明是没管理员权限。

**Comment by bianyuan456** [comment]
> > 是的，非管理员撤回别人的消息，返回的是成功的结果。应该返回失败，而且注明是没管理员权限。
> 
> 下个版本会在撤回失败时返回失败

好的，谢谢，我今天单独发了个建议优化的帖子，里面还提到了2种情况，就是要记得测试 管理员撤回群创建者的消息 。我这就去吧那个建议帖子关了吧。
