### ISSUE TITLE
[BUG] 连接websocket的path问题

### ISSUE THREAD

**Issue by Zightch** [LLOneBot/LLOneBot#389]
### 系统版本

Windows 11 

### QQNT 版本

9.9.15-27597

### LLOneBot 版本

3.31.4

### OneBot 客户端

自己开发的机器人程序

### 发生了什么?

# 前提
我已经在QQ的`设置`界面设置好了LLOneBot的工作方式和端口, 如图所示  
![image](https://github.com/user-attachments/assets/0eaf0886-462b-4338-a585-f592e8a99b17)  
# 问题
### 1. 使用websocket的api接口`ws://127.0.0.1:3002/api`连接至LLOneBot, LLOneBot按理说是不会上报event消息的, 但实际上它上报了
![image](https://github.com/user-attachments/assets/e3beee3b-7d7a-4280-b312-8c80a3ee999e)
### 2. 使用任意的websocket的路径连接到`ws://127.0.0.1:3002/xxx`也会允许连接, 效果同上
![image](https://github.com/user-attachments/assets/e81e1799-1bf6-43b7-aaed-c2f2ce31e0f7)
### 3. 使用websocket的event接口`ws://127.0.0.1:3002/event`连接至LLOneBot, 并发送api请求, 按理说不应该做响应, 但是请求成功, QQ中消息也发出去了
![image](https://github.com/user-attachments/assets/90fc2848-dfb7-48bb-89b1-7accfbe82810)

### 如何复现

1. 安装好LiteLoaderQQNT, LLOneBot, 启动QQ并设置好正向websocket, 端口号3002
2. 使用`websocket本地软件工具`或者`机器人`或者`网页版在线websocket工具`连接`ws://127.0.0.1:3002/任意path`
3. 会在接收窗口内收到来event的消息上报
4. 可以在不合理的path的连接中发送api请求

### 期望的结果?

我的机器人因为此问题出了BUG, 我排查了好久, 我一直不相信是LLOneBot的问题, 但是现在不得不怀疑了

在onebot11文档中, 不应该出现上述情况. 如下onebot11的文档  
https://github.com/botuniverse/onebot-11/blob/master/communication/ws.md  
在理想状态下, LLOneBot应该只接受来自`/api`, `/event`, `/`的连接, 其他path连接应当拒绝  
同时`/api`只接收api请求和回复给客户端执行后的结果, `/event`只上报事件, 不做任何接收数据的处理

**Comment by idranme** [comment]
v3.31.6 已修复
