### ISSUE TITLE
发送群公告接口_send_group_notice没有支持image参数

### ISSUE THREAD

**Issue by sd3970566** [LLOneBot/LLOneBot#399]
### 系统版本

2024年9月6日前的最新版本

### QQNT 版本

2024年9月6日前的最新版本

### LLOneBot 版本

2024年9月6日前的最新版本

### OneBot 客户端

2024年9月6日前的最新版本

### 发生了什么?

发送本地图片：“{"group_id":"173123783","content":"hahaha","image":"C:\\Users\\Administrator\\Desktop\\aaa.png"}”
发送网络图片  “{"group_id":"173123783","content":"hahaha","image":"https://www.baidu.com/img/flexible/logo/pc/result.png"}”
两种方式均不行。可能还没适配吧

### 如何复现

发送本地图片：“{"group_id":"173123783","content":"hahaha","image":"C:\\Users\\Administrator\\Desktop\\aaa.png"}”
发送网络图片  “{"group_id":"173123783","content":"hahaha","image":"https://www.baidu.com/img/flexible/logo/pc/result.png"}”
两种方式均不行。可能还没适配吧

### 期望的结果?

希望公告支持图片

### LLOneBot 运行日志

```shell
希望公告支持图片
```

### OneBot 客户端运行日志

```shell
希望公告支持图片
```

**Comment by idranme** [comment]
v3.32.0 已支持
