### ISSUE TITLE
【建议】upload_group_file 上传群文件时已经传过的文件，再次传时无法秒传。(官方客户端却可以) 或者建议新增一个群文件分享的功能。

### ISSUE THREAD

**Issue by sd3970566** [LLOneBot/LLOneBot#400]
【建议】upload_group_file 上传群文件时已经传过的文件，再次传时无法秒传。(官方客户端却可以) 或者建议新增一个群文件分享的功能。
比如50M的RAR文件传到群文件成功后。再传一模一样的又要真实上传而不是秒传，最早用的哪款QQ机器人有个文件分享的API。 也可以实现秒传！

**Comment by idranme** [comment]
v3.32.0 优化了发送速度；发送本地文件可以秒传已经发过的文件
