### ISSUE TITLE
[BUG] 获取好友列表不全面

### ISSUE THREAD

**Issue by Fiend-14574572** [LLOneBot/LLOneBot#401]
### 系统版本

Windows 10 专业版 21H1

### QQNT 版本

版本: 9.9.15-27597 (64位)

### LLOneBot 版本

3.31.8

### OneBot 客户端

LLOneBot 3.31.8

### 发生了什么?

我有1k个好友，访问api，只能获取到290个好友信息，获取不全面

### 如何复现

https://wmimg.com/i/559/2024/09/66dbd70dc2499.png
https://wmimg.com/i/559/2024/09/66dbd70dabe22.png
https://wmimg.com/i/559/2024/09/66dbd70dbb507.png
https://wmimg.com/i/559/2024/09/66dbd70eb7b48.png

### 期望的结果?

能获取全面

### LLOneBot 运行日志

```shell
1
```

### OneBot 客户端运行日志

```shell
1
```

**Comment by idranme** [comment]
使用了哪个 API？

**Comment by Fiend-14574572** [comment]
> 使用了哪个 API？

这个
![9d56d12b4a403b9bd88cd3e75d242f16](https://github.com/user-attachments/assets/924776fe-b20a-4f9a-a183-1f77814bc5d1)

**Comment by idranme** [comment]
获取不到的好友是单项好友吗？

**Comment by idranme** [comment]
使用 no_cache 参数能否获取完整？

**Comment by idranme** [comment]
v3.31.10 已修复
