### ISSUE TITLE
[BUG] 2个不宜发现的问题

### ISSUE THREAD

**Issue by Fiend-14574572** [LLOneBot/LLOneBot#405]
### 系统版本

Windows 10 专业版 21H1

### QQNT 版本

版本: 9.9.15-27597 (64位)

### LLOneBot 版本

3.31.10

### OneBot 客户端

3.31.10

### 发生了什么?

2个不宜发现的问题
以前那些版本就存在了，可能他们测试没有我怎么大的信息量所以没发现
前提条件（我所有群全部接收信息，100群左右，消息量非常大）
【1】去调用api去发个信息，有时候不会去执行。
【2】我同意了好友，一般来说会有事件被触发，（增加好友），有时候会被无视。

### 如何复现

有图片的，但是找不到了。。

### 期望的结果?

【1】优化调用api
【2】找到不触发的原因点优化

**Comment by idranme** [comment]
v3.32.4 是否存在该问题？

**Comment by idranme** [comment]
v3.32.6 已修复
