### ISSUE TITLE
[BUG] 无法上传到 群文件夹 查看代码没有关于 floder id 的配置，群满了 进不了群

### ISSUE THREAD

**Issue by kkgg0521** [LLOneBot/LLOneBot#412]
### 系统版本

最新

### QQNT 版本

最新

### LLOneBot 版本

最新

### OneBot 客户端

最新

### 发生了什么?

 无法上传到 群文件夹 查看代码没有关于 floder id 的配置，群满了 进不了群

### 如何复现

 无法上传到 群文件夹 查看代码没有关于 floder id 的配置，群满了 进不了群

### 期望的结果?

 无法上传到 群文件夹 查看代码没有关于 floder id 的配置，群满了 进不了群

### LLOneBot 运行日志

```shell
无法上传到 群文件夹 查看代码没有关于 floder id 的配置，群满了 进不了群
```

### OneBot 客户端运行日志

```shell
无法上传到 群文件夹 查看代码没有关于 floder id 的配置，群满了 进不了群
```

**Comment by idranme** [comment]
v3.32.4 已修复

**Comment by idranme** [comment]
folder id 可从 `get_group_root_files` API 获取
