### ISSUE TITLE
3.32.4对好友和加群 验证不会处理了

### ISSUE THREAD

**Issue by zheng-zwd** [LLOneBot/LLOneBot#414]
系统版本
windows server 2012 datacenter

QQNT 版本
版本：QQ_9.9.15_240902_x64_01

LLOneBot 版本
3.32.4

OneBot 客户端
3.32.4

**Comment by idranme** [comment]
请提供复现步骤

**Comment by zheng-zwd** [comment]
复现：
只要打开机器人的通过验证  正常是有人申请加群或加好友   机器人会自动处理 通过或不通过的
现在这种操作  机器人做出了动作 ，可是插件没动作

**Comment by zheng-zwd** [comment]
对  收不到  机器人发出的验证处理指令   
您的这个插件不反馈给QQ 进行处理

**Comment by zheng-zwd** [comment]
3.28的版本是正常的  往后的版本都是有这种问题

**Comment by ACaiCat** [comment]
![image](https://github.com/user-attachments/assets/5c208663-7fc6-4587-912b-ceb6f716747f)
![image](https://github.com/user-attachments/assets/88ba9a5e-14f7-4947-a50e-3da83adf5c73)
