### ISSUE TITLE
[BUG] 无法正常上报bot自身的进群事件

### ISSUE THREAD

**Issue by ShoulderDorry** [LLOneBot/LLOneBot#419]
### 系统版本

 Windows Server 2022

### QQNT 版本

9.9.15-29740

### LLOneBot 版本

3.32.6

### OneBot 客户端

Nonebot2 2.3.2

### 发生了什么?

当机器人初次被邀请到一个的群聊时（此前从未加入过该群聊），无论该群创建时长如何，均不会上报机器人自身的进群事件[notice.group_increase.invite]，
而当机器人第二次进入该群聊时，可以正常上报[notice.group_increase.invite]。
LLOnebot 3.27.4版本并未出现过该问题。

### 如何复现

1.机器人被邀请到一个此前从未加入过的群聊（无论创建时长如何）。
2.Onebot客户端控制台并未如预期的那样出现[notice.group_increase.invite]的上报。
3.将机器人移出该群聊，此后再次邀请机器人进入该群聊。
4.Onebot客户端控制台出现了机器人自身进群上报：[notice.group_increase.invite]: {'time': 1726410244, 'self_id': 机器人QQ, 'post_type': 'notice', 'notice_type': 'group_increase', 'sub_type': 'invite', 'user_id': 机器人QQ, 'group_id': 该群的群号, 'operator_id': 邀请者的QQ号}
5.先后在 Windows Server 2022、Windows 11，使用同一LLOnebot版本（3.32.6）和相同版本Onebot客户端重复上述操作，均得到相同的结果（对于初次进入的群聊，不上报机器人自身的进群事件）

### 期望的结果?

希望能如此前的LLOnebot版本（3.27.4）那样实现机器人初次进入群聊就能上报自身的进群事件，而非第二次进群才上报。

**Comment by idranme** [comment]
9.9.15-27597 下没能复现

1. 创建一个新群
2. 邀请机器人进入其中
3. 管理员同意机器人加群请求
4. 出现了机器人自身进群上报：[notice.group_increase.invite]: {'time': 1726410244, 'self_id': 机器人QQ, 'post_type': 'notice', 'notice_type': 'group_increase', 'sub_type': 'invite', 'user_id': 机器人QQ, 'group_id': 该群的群号, 'operator_id': 邀请者的QQ号}
