### ISSUE TITLE
[BUG] 私聊戳一戳被错误地上报为[notice.friend_add]

### ISSUE THREAD

**Issue by ShoulderDorry** [LLOneBot/LLOneBot#420]
### 系统版本

 Windows Server 2022

### QQNT 版本

9.9.15-29740

### LLOneBot 版本

3.32.6

### OneBot 客户端

Nonebot2 2.3.2

### 发生了什么?

在私聊中，戳一戳会被错误地上报为[notice.friend_add]，而不是预期的[notice.notify.poke]；
私聊戳一戳上报的内容为：
[notice.friend_add]: {'time': 1726424339, 'self_id': 机器人QQ, 'post_type': 'notice', 'notice_type': 'friend_add', 'user_id': 发送者QQ}

### 如何复现

1.在私聊中对机器人发送戳一戳
2.观察到Onebot客户端显示的上报为[notice.friend_add]: {'time': 1726424339, 'self_id': 机器人QQ, 'post_type': 'notice', 'notice_type': 'friend_add', 'user_id': 发送者QQ}

### 期望的结果?

希望能让私聊戳一戳正确地上报为[notice.notify.poke]，而不是[notice.friend_add]

### OneBot 客户端运行日志

```shell
09-16 02:30:15 [SUCCESS] nonebot | OneBot V11 机器人QQ | [notice.friend_add]: {'time': 1726425015, 'self_id': 机器人QQ, 'post_type': 'notice', 'notice_type': 'friend_add', 'user_id': 发送者QQ}
```

**Comment by idranme** [comment]
v3.32.7 已修复
