### ISSUE TITLE
LLOneBot 版本3.32.6 不会自动同意入群申请

### ISSUE THREAD

**Issue by zheng-zwd** [LLOneBot/LLOneBot#421]
系统版本
Windows Server 2012

QQNT 版本
9.9.15-29740

LLOneBot 版本
3.32.6

OneBot 客户端
3.32.6

如何复现
1.对机器人设置 入群 自动同意
2.用另一个号申请入群 ，不会自动同意

期望的结果?
希望能让机器人会自动同意入群申请

**Comment by idranme** [comment]
无法复现
