### ISSUE TITLE
[BUG] 有时候不会触发（增加好友）事件-随机触发

### ISSUE THREAD

**Issue by Fiend-14574572** [LLOneBot/LLOneBot#427]
### 系统版本

Windows 10 专业版 21H1

### QQNT 版本

版本: 9.9.15-27597 (64位)

### LLOneBot 版本

3.32.8

### OneBot 客户端

3.32.8

### 发生了什么?

[BUG] 有时候不会触发（增加好友）事件-随机触发
<img src="https://wmimg.com/i/559/2024/09/66eac2faa88b8.png" alt="6b02bc1c854e15439ac8e9cb3aeca095.png" title="6b02bc1c854e15439ac8e9cb3aeca095.png" />
<img src="https://wmimg.com/i/559/2024/09/66eac2fc0cbfb.png" alt="4adb03742ffe758948ea9321f9867796.png" title="4adb03742ffe758948ea9321f9867796.png" />
<img src="https://wmimg.com/i/559/2024/09/66eac2fc55a72.png" alt="d2d6ec2ec97e0621548f1a3456c3cbda.png" title="d2d6ec2ec97e0621548f1a3456c3cbda.png" />
<img src="https://wmimg.com/i/559/2024/09/66eac2fc46888.png" alt="9f79e02fcaa7aea2e02c8da61178ec4c.png" title="9f79e02fcaa7aea2e02c8da61178ec4c.png" />

### 如何复现

大量的消息和增加同意好友就会出现

### 期望的结果?

优化一下

### LLOneBot 运行日志
2024/9/19 18:52:38 配置已更新 {"enableLLOB":true,"ob11":{"httpPort":3000,"httpHosts":[],"httpSecret":"","wsPort":3001,"wsHosts":[],"enableHttp":true,"enableHttpPost":false,"enableWs":true,"enableWsReverse":false,"messagePostFormat":"string","enableHttpHeart":false,"enableQOAutoQuote":false,"listenLocalhost":false},"heartInterval":60000,"token":"","enableLocalFile2Url":false,"debug":false,"log":true,"reportSelfMessage":true,"autoDeleteFile":false,"autoDeleteFileSecond":60,"musicSignUrl":"","msgCacheExpire":120} 

2024/9/19 18:52:38 开始检查 FFmpeg  

2024/9/19 18:52:38 FFmpeg is not installed or not found in PATH: {} 

2024/9/19 18:52:40 配置已更新 {"enableLLOB":true,"ob11":{"httpPort":3000,"httpHosts":[],"httpSecret":"","wsPort":3001,"wsHosts":[],"enableHttp":true,"enableHttpPost":false,"enableWs":true,"enableWsReverse":false,"messagePostFormat":"string","enableHttpHeart":false,"enableQOAutoQuote":false,"listenLocalhost":false},"heartInterval":60000,"token":"","enableLocalFile2Url":false,"debug":false,"log":true,"reportSelfMessage":true,"autoDeleteFile":false,"autoDeleteFileSecond":60,"musicSignUrl":"","msgCacheExpire":120} 

2024/9/19 18:52:40 开始检查 FFmpeg  

2024/9/19 18:52:40 FFmpeg is not installed or not found in PATH: {} 

2024/9/19 18:52:41 FFmpeg is not installed or not found in PATH: {} 

2024/9/19 18:52:41 查询 LLOneBot 错误信息 没有找到 FFmpeg, 音频只能发送 WAV 和 SILK, 视频尺寸可能异常 

2024/9/19 18:52:41 开始检查 FFmpeg  

2024/9/19 18:54:05 [info] (2692097794) | app 好友列表变动 1088

2024/9/19 18:54:13 [info] (2692097794) | app 好友列表变动 1088

2024/9/19 18:54:14 [info] (2692097794) | app 好友列表变动 1088

2024/9/19 18:54:46 [info] (2692097794) | onebot ws connect /

2024/9/19 18:54:46 [info] (2692097794) | onebot WebSocket 事件上报  meta_event

2024/9/19 18:54:46 [info] (2692097794) | onebot 收到 HTTP 请求 /get_login_info [Object: null prototype] {}

2024/9/19 18:54:53 [info] 欲望(2692097794) | app 好友列表变动 1090

2024/9/19 18:55:00 [info] 欲望(2692097794) | app 好友列表变动 1090

2024/9/19 18:54:58 [info] 欲望(2692097794) | app 好友列表变动 1090

2024/9/19 18:55:06 [info] 欲望(2692097794) | app 好友列表变动 1090

2024/9/19 18:55:11 [info] 欲望(2692097794) | onebot 有一个 Websocket 连接断开

2024/9/19 18:55:16 开始检查 FFmpeg  

2024/9/19 18:55:16 查询 LLOneBot 错误信息 没有找到 FFmpeg, 音频只能发送 WAV 和 SILK, 视频尺寸可能异常 

2024/9/19 18:55:16 FFmpeg is not installed or not found in PATH: {} 

2024/9/19 18:55:18 LLOneBot latest version ["3","33","1"] 

2024/9/19 18:55:18 [info] 欲望(2692097794) | app 好友列表变动 1090

_No response_

### OneBot 客户端运行日志
2024/9/19 18:52:38 配置已更新 {"enableLLOB":true,"ob11":{"httpPort":3000,"httpHosts":[],"httpSecret":"","wsPort":3001,"wsHosts":[],"enableHttp":true,"enableHttpPost":false,"enableWs":true,"enableWsReverse":false,"messagePostFormat":"string","enableHttpHeart":false,"enableQOAutoQuote":false,"listenLocalhost":false},"heartInterval":60000,"token":"","enableLocalFile2Url":false,"debug":false,"log":true,"reportSelfMessage":true,"autoDeleteFile":false,"autoDeleteFileSecond":60,"musicSignUrl":"","msgCacheExpire":120} 

2024/9/19 18:52:38 开始检查 FFmpeg  

2024/9/19 18:52:38 FFmpeg is not installed or not found in PATH: {} 

2024/9/19 18:52:40 配置已更新 {"enableLLOB":true,"ob11":{"httpPort":3000,"httpHosts":[],"httpSecret":"","wsPort":3001,"wsHosts":[],"enableHttp":true,"enableHttpPost":false,"enableWs":true,"enableWsReverse":false,"messagePostFormat":"string","enableHttpHeart":false,"enableQOAutoQuote":false,"listenLocalhost":false},"heartInterval":60000,"token":"","enableLocalFile2Url":false,"debug":false,"log":true,"reportSelfMessage":true,"autoDeleteFile":false,"autoDeleteFileSecond":60,"musicSignUrl":"","msgCacheExpire":120} 

2024/9/19 18:52:40 开始检查 FFmpeg  

2024/9/19 18:52:40 FFmpeg is not installed or not found in PATH: {} 

2024/9/19 18:52:41 FFmpeg is not installed or not found in PATH: {} 

2024/9/19 18:52:41 查询 LLOneBot 错误信息 没有找到 FFmpeg, 音频只能发送 WAV 和 SILK, 视频尺寸可能异常 

2024/9/19 18:52:41 开始检查 FFmpeg  

2024/9/19 18:54:05 [info] (2692097794) | app 好友列表变动 1088

2024/9/19 18:54:13 [info] (2692097794) | app 好友列表变动 1088

2024/9/19 18:54:14 [info] (2692097794) | app 好友列表变动 1088

2024/9/19 18:54:46 [info] (2692097794) | onebot ws connect /

2024/9/19 18:54:46 [info] (2692097794) | onebot WebSocket 事件上报  meta_event

2024/9/19 18:54:46 [info] (2692097794) | onebot 收到 HTTP 请求 /get_login_info [Object: null prototype] {}

2024/9/19 18:54:53 [info] 欲望(2692097794) | app 好友列表变动 1090

2024/9/19 18:55:00 [info] 欲望(2692097794) | app 好友列表变动 1090

2024/9/19 18:54:58 [info] 欲望(2692097794) | app 好友列表变动 1090

2024/9/19 18:55:06 [info] 欲望(2692097794) | app 好友列表变动 1090

2024/9/19 18:55:11 [info] 欲望(2692097794) | onebot 有一个 Websocket 连接断开

2024/9/19 18:55:16 开始检查 FFmpeg  

2024/9/19 18:55:16 查询 LLOneBot 错误信息 没有找到 FFmpeg, 音频只能发送 WAV 和 SILK, 视频尺寸可能异常 

2024/9/19 18:55:16 FFmpeg is not installed or not found in PATH: {} 

2024/9/19 18:55:18 LLOneBot latest version ["3","33","1"] 

2024/9/19 18:55:18 [info] 欲望(2692097794) | app 好友列表变动 1090

_No response_

**Comment by idranme** [comment]
v3.33.2 已修复
