### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by gaqwe767** [LLOneBot/LLOneBot#429]
### 系统版本

WIN10 LTSC 21H2

### QQNT 版本

QQ-9.9.15-27597

### LLOneBot 版本

3.33.0

### 发生了什么?

![QQ截图20240918212520](https://github.com/user-attachments/assets/9ca471cf-90ee-4060-960d-256ea7535131)
其他插件没问题，装上LLOneBot，QQNT就报错

### 如何复现

自从更新到[LLOneBot v3.32.8]就开始报错，尝试重新安装QQNT无效、重新安装LiteLoaderQQNT无效、清空LLOneBot的data数据无效。

### 期望的结果?

QQNT启动不报错，正常使用。

**Comment by idranme** [comment]
可能与某些插件发生冲突，如 NapCat.Framework
