### ISSUE TITLE
整个api可以(屏蔽)和(解放)群

### ISSUE THREAD

**Issue by Fiend-14574572** [LLOneBot/LLOneBot#430]
整个api可以(屏蔽)和(解放)群,方便管理群的信息接收.
<img src="https://wmimg.com/i/559/2024/09/66eaeae712bba.jpg" alt="17452df94997f03bffd78989fbce7dd1_720.jpg" title="17452df94997f03bffd78989fbce7dd1_720.jpg" />

**Comment by linyuchen** [comment]
4.3.0 已支持
