### ISSUE TITLE
[BUG] 精华消息 message_id 不一致

### ISSUE THREAD

**Issue by kukume** [LLOneBot/LLOneBot#432]
### 系统版本

Windows server 2022

### QQNT 版本

9.9.15-27597 

### LLOneBot 版本

3.32.2

### 发生了什么?

添加精华消息事件，其中的 message_id 不是对应精华消息的 message_id

### 如何复现

1、记录消息的message_id
2、设置精华
3、查看事件数据，message_id 不一致

### 期望的结果?

message_id 一致

**Comment by idranme** [comment]
v3.33.1 已修复
