### ISSUE TITLE
[BUG] HTTP上报秘钥甚至不生效

### ISSUE THREAD

**Issue by Waldo-Schaeffer** [LLOneBot/LLOneBot#437]
### 系统版本

Windows Server 2022 21H2

### QQNT 版本

9.9.11-24568 (64位)

### LLOneBot 版本

3.28.6

### OneBot 客户端

PYTHON 3.10

### 发生了什么?

我填写了HTTP上报信息，但是在抓取的时候，输出haders并没有看到有上报秘钥，重启QQ之后
![QQ图片20240922164020](https://github.com/user-attachments/assets/a852d3dc-fa46-47a1-99a3-70d0534fee0e)

### 如何复现

使用python部署一个简单的监听器：
```
from http.server import BaseHTTPRequestHandler, HTTPServer
from socketserver import ThreadingMixIn
import threading

class ThreadedHTTPServer(ThreadingMixIn, HTTPServer):
    """Combines an HTTPServer with threading capabilities."""
    pass

class RequestHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        self.send_response(200)
        self.send_header('Content-type', 'text/html')
        self.end_headers()
        self.wfile.write(b"Hello, world! This is a response to GET request.")
    
    def do_POST(self):
        self.send_response(200)
        self.send_header('Content-type', 'text/html')
        self.end_headers()
        self.wfile.write(b"Hello, world! This is a response to POST request.")
        
        authorization = self.headers.get('Authorization')
        print("上报密钥：", authorization)
        
        content_length = int(self.headers['Content-Length'])
        post_data = self.rfile.read(content_length)
        imessage_data = json.loads(post_data.decode('utf-8'))
        print(self.headers)
        print(post_data)
    
    #def log_message(self, format, *args):
        # 覆写 log_message 方法来禁止服务器日志的输出
        #pass

class HTTPServer:
    def __init__(self, address='127.0.0.1', port=18888, handler_class=RequestHandler):
        self.server_address = (address, port)
        self.handler_class = handler_class
        self.server = ThreadedHTTPServer(self.server_address, self.handler_class)

    def start_server(self):
        server_thread = threading.Thread(target=self.server.serve_forever)
        server_thread.daemon = False  # 设置为非守护线程
        server_thread.start()
        print(f"网页服务器在以下地址中启动：{self.server_address[0]}:{self.server_address[1]}...")
if __name__ == '__main__':
    网页服务器 = HTTPServer(address='127.0.0.1', port=18888)
    网页服务器.start_server()
```
就可以直接查看输出的headr信息和data信息
注：我同时开启了HTTP监听和上报，而且监听和上报都配置了Token秘钥

### 期望的结果?

应该在上报的时候，heeader中添加Authorization和秘钥

**Comment by Waldo-Schaeffer** [comment]
我服务器同时跑了好几个QQ，这是第二个启动的Q号，又及

**Comment by linyuchen** [comment]
![image](https://github.com/user-attachments/assets/ca0f3111-0ffa-4ec5-9ee3-7fc556dc5986)
https://github.com/botuniverse/onebot-11/blob/master/communication/http-post.md

**Comment by Waldo-Schaeffer** [comment]
> ![image](https://private-user-images.githubusercontent.com/10002169/369676040-ca0f3111-0ffa-4ec5-9ee3-7fc556dc5986.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxODYzNDAsIm5iZiI6MTcyNzE4NjA0MCwicGF0aCI6Ii8xMDAwMjE2OS8zNjk2NzYwNDAtY2EwZjMxMTEtMGZmYS00ZWM1LTllZTMtN2ZjNTU2ZGM1OTg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDEzNTQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiOTUyNmRjYzM0ZDdmMWM4MzkwOTc4MzJjZTAwY2UxYzQxMmU3YjAyMTU3YWQxNDUzYWI0MjJkYmJlNTIzYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.sIJCe7lDtZxdbUu6H-sNbbNhHHTR45HzYoBsAx5qpXU) https://github.com/botuniverse/onebot-11/blob/master/communication/http-post.md

谢谢
