### ISSUE TITLE
[功能建议]增加设置群备注API 

### ISSUE THREAD

**Issue by DeonLU** [LLOneBot/LLOneBot#439]
### 系统版本

Windows 11 企业版 23H2

### QQNT 版本

9.9.15-26909 (64位)

### LLOneBot 版本

3.33.5

### OneBot 客户端

3.29.5

### 发生了什么?

没有设置群备注的API
没有群备注修改事件数据上传

### 如何复现

没有设置群备注的API
没有群备注修改事件数据上传

### 期望的结果?

1.增加设置群备注API
2.增加群备注修改事件数据上传

**Comment by idranme** [comment]
![image](https://github.com/user-attachments/assets/78ee83f6-5dd9-471b-ba34-8eb985d6ddab)
是这个 API 吗？

**Comment by DeonLU** [comment]
你截图中是设置某个群成员的备注，属于群管的功能API，我指的是自己所在的群给他修改的备注，如图：
![image](https://github.com/user-attachments/assets/6c7584b0-df3d-4615-af4d-677673a0220b)

**Comment by DeonLU** [comment]
> ![image](https://private-user-images.githubusercontent.com/96647698/369792632-78ee83f6-5dd9-471b-ba34-8eb985d6ddab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwOTMzMzAsIm5iZiI6MTcyNzA5MzAzMCwicGF0aCI6Ii85NjY0NzY5OC8zNjk3OTI2MzItNzhlZTgzZjYtNWRkOS00NzFiLWJhMzQtOGViOTg1ZDZkZGFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDEyMDM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyM2NkNTQ5MzFlN2IyN2JmNTQ5ZTljODBjOGNlMzViMWVhMGZkNzEwMzFmMDE2OWIyNzRkNjE1ODkwZWQ5MzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ib6KvDhg0yp2a4TPb7IAm4fI_3Djlk6YIhpLUek5rcs) 是这个 API 吗？

按这个功能理解的话，用上面的API可以实现修改：我的本群昵称，但是我没有找到给群起备注的API，如果能添加上的话，把修改的事件数据上传也一并加上

**Comment by linyuchen** [comment]
4.3.0 已增加设置群备注 API
