### ISSUE TITLE
[BUG] 对新好友发送消息时有概率发送到临时会话导致失败

### ISSUE THREAD

**Issue by ShoulderDorry** [LLOneBot/LLOneBot#442]
### 系统版本

 Windows Server 2016

### QQNT 版本

9.9.15-27597

### LLOneBot 版本

3.33.5

### OneBot 客户端

Nonebot2 2.3.2

### 发生了什么?

使用set_friend_add_request同意好友请求，同意后机器人等待10s后使用send_private_msg向新好友私聊发送消息，此时有一定概率会发送到临时会话，导致消息发送失败，并抛出错误：nonebot.adapters.onebot.v11.exception.ActionFailed: ActionFailed(status='failed', retcode=1200, data=None, message='ntqq api call failed, nodeIKernelMsgService/sendMsg, ', wording='ntqq api call failed, nodeIKernelMsgService/sendMsg, ', echo='19904')，一旦出现这种情况，后续任何尝试私聊向该好友发送消息的操作都会失败，并抛出同样的错误。
如果尝试对该好友使用send_like，则会抛出错误“账号转换失败”。

以上错误概率发生，是否存在规律未知，初步排除是添加好友操作过于频繁导致。
![ab23561b7b2b412bf15b49c542b40627](https://github.com/user-attachments/assets/9078a2df-1cce-4378-af1a-d0ac014d6d7b)
![3e2d183ac93f5b7e5bc6f96709710c55](https://github.com/user-attachments/assets/c8658b8e-027f-4192-9eb4-a809fae6f4bc)

### 如何复现

1.机器人使用set_friend_add_request同意了一个好友请求。
2.等待10s后，机器人调用send_private_msg向该好友发送了一条消息。
3.消息被发送到了与该好友的临时会话，且发送失败。观察到控制台抛出了nonebot.adapters.onebot.v11.exception.ActionFailed: ActionFailed(status='failed', retcode=1200, data=None, message='ntqq api call failed, nodeIKernelMsgService/sendMsg, ', wording='ntqq api call failed, nodeIKernelMsgService/sendMsg, ', echo='19904')错误。
4.后续任何对该好友发送消息的操作均失败，且抛出了同样的错误。
5.尝试对该好友使用send_like，抛出了“账号转换失败”错误。

### 期望的结果?

同意好友请求后，消息不应被发送到临时会话。

**Comment by idranme** [comment]
v3.33.7 是否存在该问题？

**Comment by sd3970566** [comment]
> v3.33.7 是否存在该问题？

3.33.8问题一样，但是我不是新好友，我是已经加了好多年的大小号测试

**Comment by idranme** [comment]
> 3.33.8问题一样，但是我不是新好友，我是已经加了好多年的大小号测试

是单向好友吗？

**Comment by ShoulderDorry** [comment]
> v3.33.7 是否存在该问题？

今天发现依旧存在该问题
