### ISSUE TITLE
[Feature Requested] 群禁言API

### ISSUE THREAD

**Issue by Sn0wo2** [LLOneBot/LLOneBot#446]
### 系统版本

Windows 11 专业版 23H2

### Liteloader版本

1.2.1

### LLOneBot 版本

3.33.7

### QQ版本

9.9.15-27597

### 功能请求

希望能增加对于`自身`或`群列表`的禁言API，获得`自身`或`群列表`的禁言状态(例如在发送消息前检查此群是否已被禁言)
我已阅读文档，暂未发现有此API的支持，如果有请大佬指点，非常感谢o7

**Comment by idranme** [comment]
v3.33.8 会在群内被禁言时阻止自身发送消息
