### ISSUE TITLE
[BUG] QQ版本: 9.9.15-28327 (64位) 更新后，安装框架无法在NTQQ的设置里显示了，并且也无法进行通信和使用了

### ISSUE THREAD

**Issue by sd3970566** [LLOneBot/LLOneBot#447]
### 系统版本

Windows 10 专业版21H1内部版本号9043.985

### QQNT 版本

9.9.15-28327 (64位)

### LLOneBot 版本

用的是LLOneBot的CMD下载客户端，自动下载的应该是最新的吧

### OneBot 客户端

用的是LLOneBot的CMD下载客户端，自动下载的应该是最新的吧

### 发生了什么?

[BUG] QQ版本: 9.9.15-28327 (64位) 更新后，安装框架无法在NTQQ的设置里显示了，并且也无法进行通信和使用了

### 如何复现

[BUG] QQ版本: 9.9.15-28327 (64位) 更新后，安装框架无法在NTQQ的设置里显示了，并且也无法进行通信和使用了

### 期望的结果?

[BUG] QQ版本: 9.9.15-28327 (64位) 更新后，安装框架无法在NTQQ的设置里显示了，并且也无法进行通信和使用了

### LLOneBot 运行日志

```shell
[BUG] QQ版本: 9.9.15-28327 (64位) 更新后，安装框架无法在NTQQ的设置里显示了，并且也无法进行通信和使用了
```

### OneBot 客户端运行日志

```shell
[BUG] QQ版本: 9.9.15-28327 (64位) 更新后，安装框架无法在NTQQ的设置里显示了，并且也无法进行通信和使用了
```

**Comment by ShoulderDorry** [comment]
这不是bug...更新qq以后llnt都没了，怎么可能还会留着llob

**Comment by sd3970566** [comment]
> 这不是bug...更新qq以后llnt都没了，怎么可能还会留着llob

重新安装了还是不显示··

**Comment by PandaXHFF** [comment]
重新安装llob也不显示，退回旧版本安装也不显示

**Comment by idranme** [comment]
> 重新安装llob也不显示，退回旧版本安装也不显示

说明没有安装上liteloader

**Comment by idranme** [comment]
https://github.com/super1207/install_llob/releases/tag/0.0.9

这是安装器，会帮你安装liteloader和llonebot。

**Comment by PandaXHFF** [comment]
> https://github.com/super1207/install_llob/releases/tag/0.0.9
> 
> 这是安装器，会帮助安装liteloader和llonebot。

用的是这个，你试试吧，也不知道是什么问题

**Comment by idranme** [comment]
我用 https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/commit/5bf0e63c755afe25556b76d963b2cd342fc07571

![e30623cd3a8c4712048f7a038493f3aa](https://github.com/user-attachments/assets/b19c6dd3-5fd0-4052-8dfb-91ef8f9d8128)

**Comment by PandaXHFF** [comment]
> 我用 [LiteLoaderQQNT/LiteLoaderQQNT@5bf0e63](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/commit/5bf0e63c755afe25556b76d963b2cd342fc07571)
> 
> ![e30623cd3a8c4712048f7a038493f3aa](https://private-user-images.githubusercontent.com/96647698/371014400-b19c6dd3-5fd0-4052-8dfb-91ef8f9d8128.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMzc0NTUsIm5iZiI6MTcyNzMzNzE1NSwicGF0aCI6Ii85NjY0NzY5OC8zNzEwMTQ0MDAtYjE5YzZkZDMtNWZkMC00MDUyLThkZmItOTFlZjhmOWQ4MTI4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDA3NTIzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1NjQwMjI4ODQwZTI3ZjFlYmJkZmUzZTIyZTlhMmM2NjExZmYzMDE3MDA2ZWE4ZTVjZWQ2ZTFjMzA3NzRjODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.v66uAM_dP9WV_j3LFv6pvCC_aAUCjIOexJL2OLua2AU)

安装了llob的旧版本升级到最新版，不显示，重新使用llob安装器安装依然不显示。卸载qq（并删除qqnt文件夹）重新安装新版qq后，安装llob仍然不显示。还需要清理缓存信息吗？

**Comment by idranme** [comment]
> 安装了llob的旧版本升级到最新版，不显示，重新使用llob安装器安装依然不显示。卸载qq（并删除qqnt文件夹）重新安装新版qq后，安装llob仍然不显示。还需要清理缓存信息吗？

尝试 https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/releases/tag/1.2.2
