### ISSUE TITLE
[BUG] 配置修改无效

### ISSUE THREAD

**Issue by 1244453393** [LLOneBot/LLOneBot#464]
### 系统版本

Windows 11 Pro 22H2

### QQNT 版本

9.9.9-23424

### LLOneBot 版本

4.0.4

### 发生了什么?

保存配置功能无效，仅本地配置文件变了，服务监听的端口什么的还是原来的，通过源码调试输出，发现是`CHANNEL_SET_CONFIG_CONFIRMED`的事件没有响应
```typescript
ipcMain.on(CHANNEL_SET_CONFIG_CONFIRMED, (event, config: LLOBConfig) => {
      console.log('配置保存')
      ctx.parallel('llob/config-updated', config)
})
```
如上，`配置保存`没有打印出来，但是`CHANNEL_SET_CONFIG`是正常响应的，并且Promise返回true

### 如何复现

修改任何一项配置

### 期望的结果?

修改配置正常

**Comment by 1244453393** [comment]
消息什么的也监听不到，控制台不输出

**Comment by idranme** [comment]
将 QQ 更新到 9.9.12 及以上版本后，是否还存在该问题？

**Comment by 1244453393** [comment]
> 将 QQ 更新到 9.9.12 及以上版本后，是否还存在该问题？

存在，一开始我以为是版本太高了，发现切换到我服务器上挂机的版本9.9.9-23424，也不行

**Comment by idranme** [comment]
v4.0.10 已修复
