### ISSUE TITLE
[BUG] 4.0.7和4.0.8版本更新之后QQ遇到错误无法正常登录启动

### ISSUE THREAD

**Issue by kaguramaisakuya** [LLOneBot/LLOneBot#471]
### 系统版本

Windows 11 Pro 23H2

### QQNT 版本

9.9.15-27254

### LLOneBot 版本

4.0.7 4.0.8

### 发生了什么?

QQ登录就会报错，没法正常登录，4.0.7和4.0.8版本都不行，但4.0.6版本可以正常使用

![image](https://github.com/user-attachments/assets/48069149-eddd-40ad-a6fc-74c2f150e024)

### 如何复现

启动QQ点登录

### 期望的结果?

QQ正常启动登录

**Comment by idranme** [comment]
安装 VC 运行库

https://learn.microsoft.com/zh-cn/cpp/windows/latest-supported-vc-redist?view=msvc-170#latest-microsoft-visual-c-redistributable-version

**Comment by idranme** [comment]
重新安装一下

**Comment by idranme** [comment]
将QQ更新到最新版本

**Comment by idranme** [comment]
v4.0.9 已修复
