### ISSUE TITLE
[request] 希望get_group_msg_history可以向前回溯

### ISSUE THREAD

**Issue by Natsukage** [LLOneBot/LLOneBot#472]
get_group_msg_history这个API似乎只能向前取得最多100条，但是提供了message_seq后，它就变成了取得给定id之后的消息而不是之前了，所以没法用递归的方法继续向前回溯
例如我现在有`1-300`条消息，在不传递message_seq的情况下，用get_group_msg_history获得了`201-300`条以后，我提供第201条消息的messageId作为message_seq请求100条消息，get_group_msg_history方法会返回从201开始的接下来100条消息也就是201-300条，而不是101-200条，导致无论如何都没法回溯到201之前的消息。我尝试传递负值进去也没用
以前LLOnebot的逻辑好像是回溯的（也可能是我记错了），所以可以通过递归传递message_seq不断往前回溯，直到message的时间超出范围，但是现在不行了。想问下LLonebot有其他办法实现这种例如"取得最近一天的所有消息“的操作吗？
或者，在传递了message_seq的情况下，是否可以允许向get_group_msg_history的count传递负数来实现向前检索指定数量条信息，而不是向后？
辛苦了，抱歉打扰了！

**Comment by idranme** [comment]
v4.0.9 已修复
