### ISSUE TITLE
[BUG] 设置里Onebot协议下配置没有保存按键

### ISSUE THREAD

**Issue by Wenaka2004** [LLOneBot/LLOneBot#476]
### 系统版本

Win11 23H2

### QQNT 版本

9.9.15-27333

### LLOneBot 版本

4.0.10

### OneBot 客户端

找不到，但与问题无关

### 发生了什么?

设置里Onebot协议下配置没有保存按键
退出设置界面后配置无法保存

### 如何复现

进入qq，设置，LLonebot选项卡，更改Onebot协议下的任意配置后没有保存按钮，关闭窗口后再次进入设置配置恢复原样

### 期望的结果?

像Satori协议配置下一样提供保存按键

**Comment by idranme** [comment]
保存按键在上面，会保存所有配置
