### ISSUE TITLE
[BUG] 4.0.10--4.0.12戳一戳api不生效

### ISSUE THREAD

**Issue by ShoulderDorry** [LLOneBot/LLOneBot#480]
### 系统版本

 Windows Server 2016

### QQNT 版本

9.9.15-27597

### LLOneBot 版本

4.0.12

### OneBot 客户端

Nonebot2 2.3.2

### 发生了什么?

使用4.0.9版本 LLOnebot时，执行await bot.call_api("group_poke", group_id=group_id, user_id=user_id)和await bot.call_api("friend_poke", user_id=user_id)，均可成功执行且显示戳一戳notify，但更新到4.0.10、4.0.11、4.0.12后。均存在“发送请求时未报错，执行结果未报错，LLOnebot日志未报错，但在pc端与手机端均不显示发出去的戳一戳”，视为发送戳一戳失败。

此后，我重启LLOnebot，未解决，情况与上述相同。

之后尝试回退到4.0.9版本，再次执行await bot.call_api("group_poke", group_id=group_id, user_id=user_id)，观察到机器人成功发送戳一戳，因此认为4.0.9之后的版本戳一戳接口未生效。

### 如何复现

1.使用4.0.10及以上LLOnebot，QQNT 9.9.15-27597，执行await bot.call_api("group_poke", group_id=group_id, user_id=user_id)和await bot.call_api("friend_poke", user_id=user_id)，结果为发送请求时未报错，执行结果未报错，LLOnebot日志未报错，但在pc端与手机端均不显示发出去的戳一戳”，视为发送戳一戳失败。

2.回退到4.0.9版本重复上述操作，成功发送戳一戳。

### 期望的结果?

4.0.9之后的版本也能让/group_poke接口和/friend_poke接口生效

### LLOneBot 运行日志

```shell
2024/10/19 02:58:23 [info] (2461136989) | onebot 收到反向 Websocket 消息 { action: 'group_poke', params: { group_id: 949394928, user_id: 3781569860 }, echo: '10453' }

2024/10/19 02:58:23 [info] (2461136989) | onebot 收到反向 Websocket 消息 { action: 'group_poke', params: { group_id: 949394928, user_id: 3781569860 }, echo: '10454' }

2024/10/19 02:58:23 [info] (2461136989) | onebot 收到反向 Websocket 消息 { action: 'group_poke', params: { group_id: 949394928, user_id: 3781569860 }, echo: '10455' }

2024/10/19 02:58:23 [info] (2461136989) | onebot 收到反向 Websocket 消息 { action: 'group_poke', params: { group_id: 949394928, user_id: 3781569860 }, echo: '10456' }

2024/10/19 02:58:23 [info] (2461136989) | onebot 收到反向 Websocket 消息 { action: 'group_poke', params: { group_id: 949394928, user_id: 3781569860 }, echo: '10457' }
```

**Comment by idranme** [comment]
LLOneBot 启动时日志内是否存在报错？

**Comment by ShoulderDorry** [comment]
> LLOneBot 启动时日志内是否存在报错？

启动时仅存在该条报错：
2024/10/19 02:51:16 [warn] (2461136989) | app crychic 加载失败 Error: EBUSY: resource busy or locked, copyfile 'C:\Users\Administrator\LiteLoaderQQNT-main\plugins\LLOneBot\main\chunks\crychic-win32-x64-DtkSVC2T.node' -> 'C:\Users\Administrator\LiteLoaderQQNT-main\data\LLOneBot\temp\crychic-win32-x64-DtkSVC2T.node' at async Object.copyFile (node:internal/fs/promises:620:10) at async Native.start (C:\Users\Administrator\LiteLoaderQQNT-main\plugins\LLOneBot\main\main.cjs:14:25394) { errno: -4082, code: 'EBUSY', syscall: 'copyfile', path: 'C:\\Users\\Administrator\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\chunks\\crychic-win32-x64-DtkSVC2T.node', dest: 'C:\\Users\\Administrator\\LiteLoaderQQNT-main\\data\\LLOneBot\\temp\\crychic-win32-x64-DtkSVC2T.node' }

但此后LLOnebot能够正常上报与响应

**Comment by idranme** [comment]
你是否同时登陆多个账号？

**Comment by idranme** [comment]
下个版本修复

**Comment by idranme** [comment]
v4.0.13 已修复
