### ISSUE TITLE
[BUG] 进群事件，如果申请人QQ被提示 该账号存在风险，请谨慎操作，bot就不会有进群申请的事件上报

### ISSUE THREAD

**Issue by mysever08967** [LLOneBot/LLOneBot#484]
### 系统版本

Windows Server 2022 Datacenter

### QQNT 版本

9.9.15-28498

### LLOneBot 版本

4.0.13

### OneBot 客户端

留空

### 发生了什么?

进群事件，如果申请人QQ被提示 该账号存在风险，请谨慎操作，bot就不会有进群申请的事件上报

### 如何复现

用一个进群会提示账号风险的QQ，申请进群，

### 期望的结果?

申请人QQ如果有提示风险，bot也上报事件消息，并附加上风险提示，bot也可执行同意和拒绝的操作。

**Comment by idranme** [comment]
v4.1.0 是否存在该问题？

**Comment by mysever08967** [comment]
> v4.1.0是否存在该问题？
4.1 已经可以了，谢谢

**Comment by mysever08967** [comment]
刚发现个小bug，如果申请人账号风险的话，已有事件上报，但bot操作同意进群，虽然返回ok，但没效果，正常的就可以

**Comment by idranme** [comment]
> 刚发现个小bug，如果申请人账号风险的话，已有事件上报，但bot操作同意进群，虽然返回ok，但没效果，正常的就可以

v4.1.1 已修复
