### ISSUE TITLE
[功能建议]  增加一些简单的账号密码认证以增强安全性。

### ISSUE THREAD

**Issue by BrokenWingsIcarus** [LLOneBot/LLOneBot#486]
### 系统版本

linux

### QQNT 版本

9.9.7

### LLOneBot 版本

3.18.0

### 发生了什么?

http接口直接不需要任何授权就能访问，服务器在公网的话，还是太容易被搞了。

### 如何复现

不需要复现.

### 期望的结果?

增加token或者账号密码验证来增强安全性。

**Comment by linyuchen** [comment]
不是有 access token 设置的吗
