### ISSUE TITLE
[BUG] 构造合并转发时，展示的用户头像无法自定义

### ISSUE THREAD

**Issue by ShoulderDorry** [LLOneBot/LLOneBot#488]
### 系统版本

 Windows Server 2016

### QQNT 版本

9.9.15-27597

### LLOneBot 版本

4.1.0

### OneBot 客户端

Nonebot2 2.3.2

### 发生了什么?

构造合并转发时，虽然用户昵称已经可以自定义了，但展示的用户头像依旧是机器人自身的头像。

### 如何复现

1.使用send_forward_msg构建合并转发消息
2.观察到展示的昵称虽然已经是自定义的了，但用户头像依旧显示的是机器人自身头像

### 期望的结果?

构造合并转发能够自定义用户头像

**Comment by idranme** [comment]
v4.1.1 已修复
