### ISSUE TITLE
[BUG] 当user_id为自身时，group_increase未上报

### ISSUE THREAD

**Issue by phillaria** [LLOneBot/LLOneBot#490]
### 系统版本

Windows 10企业版 1909

### QQNT 版本

9.9.10-26909

### LLOneBot 版本

4.1.1

### 发生了什么?

bot加入新群时，没有group_increase事件的上报

### 如何复现

让bot加入一个新的群聊，查看日志

### 期望的结果?

正常上报group_increase事件

### LLOneBot 运行日志

```shell
2024/9/21 11:50:47 [info] (3122310660) | onebot 收到 HTTP 请求 /set_friend_add_request { flag: 'u_9_uMHx6EDCbKpXpIBVkKEQ|1726890039', approve: 'true' }

2024/9/21 11:50:48 [info] (3122310660) | onebot 收到 HTTP 请求 /send_private_msg { user_id: '2705892349', message: 'OK，已经处理好了~' }

2024/9/21 11:50:48 [info] (3122310660) | app 好友列表变动 548

2024/9/21 11:50:48 [info] (3122310660) | app 好友列表变动 548

2024/9/21 11:50:48 [info] (3122310660) | onebot 消息发送 1017831635

2024/9/21 11:50:48 [info] (3122310660) | onebot HTTP 事件上报: https://172-17-129-163.lan.quicker.cc:8080/ message 200

2024/9/21 11:50:49 [info] (3122310660) | onebot HTTP 事件上报: https://172-17-129-163.lan.quicker.cc:8080/ notice 200
```

**Comment by ShoulderDorry** [comment]
现在似乎是只有第二次同意拉群邀请或初次主动进群会上报group_increase，初次同意拉群邀请进群不上报

**Comment by idranme** [comment]
> 现在似乎是只有第二次同意拉群邀请或初次主动进群会上报group_increase，初次同意拉群邀请进群不上报

另外提一个 issue 吧

**Comment by idranme** [comment]
v4.1.2 已修复

**Comment by idranme** [comment]
> 现在似乎是只有第二次同意拉群邀请或初次主动进群会上报group_increase，初次同意拉群邀请进群不上报

可在 v4.1.2 查看 group_increase (approve) 事件是否会上报

**Comment by ShoulderDorry** [comment]
> > 现在似乎是只有第二次同意拉群邀请或初次主动进群会上报group_increase，初次同意拉群邀请进群不上报
> 
> 可在 v4.1.2 查看 group_increase (approve) 事件是否会上报

依旧没有解决，除非是自身主动申请进群，否则只有退群后再次同意拉群邀请才会上报group_increase.invite

**Comment by ShoulderDorry** [comment]
> > 现在似乎是只有第二次同意拉群邀请或初次主动进群会上报group_increase，初次同意拉群邀请进群不上报
> 
> 可在 v4.1.2 查看 group_increase (approve) 事件是否会上报

该错误仅会在不需要管理员审批，只需自身同意进群的群聊，对于需要管理员审批进入的群聊，初次进群即会上报group_increase.invite，不会出现该issue提到的错误
