### ISSUE TITLE
安装完了之后， qq设置里边没有相关的设置项。 Qq已经自动更新最新版了，现在好像装不上去了

### ISSUE THREAD

**Issue by GaoYuan522** [LLOneBot/LLOneBot#491]

**Comment by idranme** [comment]
更新 LiteLoaderQQNT 至最新版

LiteLoaderQQNT 安装教程：[安装 | LiteLoaderQQNT](https://liteloaderqqnt.github.io/guide/install.html#%E5%AE%89%E8%A3%85%E5%89%8D%E7%9A%84%E5%87%86%E5%A4%87%E5%B7%A5%E4%BD%9C)
