### ISSUE TITLE
[BUG] LLOneBot v4.0.12更新后get_stranger_info无法获取一些字段的内容

### ISSUE THREAD

**Issue by cxchency** [LLOneBot/LLOneBot#493]
### 系统版本

Windows

### QQNT 版本

9.9.12-26466

### LLOneBot 版本

4.0.12

### 发生了什么?

LLOneBot v4.0.12更新后get_stranger_info无法获取一些字段的内容：
无法获取原本可以获取的个性签名、标签、等信息。

### 如何复现

调用get_stranger_info接口获取用户信息

### 期望的结果?

希望能提供额外的获取方式

**Comment by idranme** [comment]
个性签名依然可以获取，为 `long_nick`

**Comment by Atrium4641** [comment]
v4.1.2无法获取陌生人信息，显示为null
![82602fe44e57aca579e5c2e9a92e739b](https://github.com/user-attachments/assets/5be394dc-64e1-44af-9470-025a98ad3f77)

**Comment by Atrium4641** [comment]
我这里是直接返回null，所有字段的内容都无法获取
