### ISSUE TITLE
[BUG] 几个问题

### ISSUE THREAD

**Issue by Atrium4641** [LLOneBot/LLOneBot#495]
### 系统版本

Windows 10 专业工作站版 22H2

### QQNT 版本

9.9.12-26466

### LLOneBot 版本

4.1.2

### OneBot 客户端

在哪看

### 发生了什么?

1. 获取群成员列表    get_group_member_list
所有人的join_time和last_sent_time字段的值都一模一样，qq_level也全都是0
貌似只有下面这几个字段的值是有效的，其他的字段的值貌似都是无效的
user_id
group_id
card
nickname
role

2. 获取陌生人信息    get_stranger_info 只能获取群内的不是互为好友的人的信息？还是只能获取群内就算是互为好友的人的信息也能获取？还是说群外的不是互为好友的信息也能获取？

3. 获取群成员信息    get_group_member_info 获取到不同的人的信息有时是正常的有时获取到的信息是null

### 如何复现

1

### 期望的结果?

1

### LLOneBot 运行日志

```shell
1
```

### OneBot 客户端运行日志

```shell
1
```

**Comment by idranme** [comment]
临时解决办法：更新 QQ 至 9.9.15 及以上版本

**Comment by Atrium4641** [comment]
![image](https://github.com/user-attachments/assets/7c03eb72-652a-473b-ae0d-6ad1066b7131)

![image](https://github.com/user-attachments/assets/75f683fb-1dff-47f9-a8f7-51286ea3ae09)

![image](https://github.com/user-attachments/assets/0d072859-9ed0-4d1b-9425-87e37980aefa)

**Comment by Atrium4641** [comment]
![image](https://github.com/user-attachments/assets/b6dcf56a-fb07-4e48-88a2-a1a4ed0dd67a)

我已确定的是这个人和我是好友并且在群内，所以无法获取陌生人信息？只能获取不是互为好友的人的信息吗？还是说受什么因素影响有概率无法获取？听说是这个人没开什么隐私权限不让别人查看他的资料导致的？

**Comment by idranme** [comment]
看一下 llonebot 日志

**Comment by Atrium4641** [comment]
> 看一下 llonebot 日志

2024/10/31 01:05:55 [info] (2115018924) | onebot 收到正向 Websocket 消息 { action: 'get_stanger_info', echo: '123456789abc123412341231201234-123412345670-4123456789abc12345678123456789ab-123456712123456789a-123456789abc123456789abcde123456789abc123456789abcde123456789abc123412345671234567123456789a123456781234', params: { user_id: 2370408621, no_cache: true } }

**Comment by idranme** [comment]
> > 看一下 llonebot 日志
> 
> 2024/10/31 01:05:55 [info] (2115018924) | onebot 收到正向 Websocket 消息 { action: 'get_stanger_info', echo: '123456789abc123412341231201234-123412345670-4123456789abc12345678123456789ab-123456712123456789a-123456789abc123456789abcde123456789abc123456789abcde123456789abc123412345671234567123456789a123456781234', params: { user_id: 2370408621, no_cache: true } }

之后有没有出现报错？

**Comment by Atrium4641** [comment]
> > > 看一下 llonebot 日志
> > 
> > 
> > 2024/10/31 01:05:55 [info] (2115018924) | onebot 收到正向 Websocket 消息 { action: 'get_stanger_info', echo: '123456789abc123412341231201234-123412345670-4123456789abc12345678123456789ab-123456712123456789a-123456789abc123456789abcde123456789abc123456789abcde123456789abc123412345671234567123456789a123456781234', params: { user_id: 2370408621, no_cache: true } }
> 
> 之后有没有出现报错？

没有

**Comment by idranme** [comment]
get_stranger_info 可以好友并且在群内的信息
![be867f7f4734457c016b1ffb6a5a48a6](https://github.com/user-attachments/assets/9a7895c8-f861-46d2-acbf-91fa510cae14)

**Comment by idranme** [comment]
get_group_member_list 出于性能考虑，会把 `qq_level` 固定为 0，如果你想获取 `qq_level`，可以使用 get_group_member_info

**Comment by idranme** [comment]
get_group_member_info 相关问题未能复现

**Comment by Atrium4641** [comment]
> get_stranger_info 可以获取好友并且在群内的信息 ![be867f7f4734457c016b1ffb6a5a48a6](https://private-user-images.githubusercontent.com/96647698/384657612-9a7895c8-f861-46d2-acbf-91fa510cae14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyMTYxNTUsIm5iZiI6MTczMTIxNTg1NSwicGF0aCI6Ii85NjY0NzY5OC8zODQ2NTc2MTItOWE3ODk1YzgtZjg2MS00NmQyLWFjYmYtOTFmYTUxMGNhZTE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEwVDA1MTczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5ZGU4MjU5NGI1MGQ1MzIwMmVmZDFiYWMzMzlkNGUxNjgxMDA0NWNiZjZhNzQzMWU3ZTEzODU2YjMzODFiMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dar-cYqVjxQ4Z8FMp-1jtt7NVdn8KEUwtTE5tPztddU)

陌生人呢，不是好友并且不在群内的

**Comment by Atrium4641** [comment]
> > get_stranger_info 可以获取好友并且在群内的信息 ![be867f7f4734457c016b1ffb6a5a48a6](https://private-user-images.githubusercontent.com/96647698/384657612-9a7895c8-f861-46d2-acbf-91fa510cae14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyMTYxNTUsIm5iZiI6MTczMTIxNTg1NSwicGF0aCI6Ii85NjY0NzY5OC8zODQ2NTc2MTItOWE3ODk1YzgtZjg2MS00NmQyLWFjYmYtOTFmYTUxMGNhZTE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEwVDA1MTczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5ZGU4MjU5NGI1MGQ1MzIwMmVmZDFiYWMzMzlkNGUxNjgxMDA0NWNiZjZhNzQzMWU3ZTEzODU2YjMzODFiMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dar-cYqVjxQ4Z8FMp-1jtt7NVdn8KEUwtTE5tPztddU)
> 
> 陌生人呢，不是好友并且不在群内的

我要在有新人进群判断他的QQ等级是否大于10才能通过申请，应该如何实现

**Comment by Atrium4641** [comment]
> get_group_member_list 出于性能考虑，会把 `qq_level` 固定为 0，如果你想获取 `qq_level`，可以使用 get_group_member_info
> 
> get_group_member_list 的 `join_time` 和 `last_sent_time` 在 9.9.15 及以上版本是正常的

![image](https://github.com/user-attachments/assets/96eb04b1-d037-457c-a100-e66c79683dbf)
我记得我qq版本很高的来着

**Comment by Atrium4641** [comment]
> get_group_member_list 出于性能考虑，会把 `qq_level` 固定为 0，如果你想获取 `qq_level`，可以使用 get_group_member_info
> 
> get_group_member_list 的 `join_time` 和 `last_sent_time` 在 9.9.15 及以上版本是正常的

![image](https://github.com/user-attachments/assets/000baf5f-dc38-4561-a44b-653d3a0a6e2e)
get_group_member_info和get_group_member_list的qq_level全是0

**Comment by idranme** [comment]
> ![image](https://private-user-images.githubusercontent.com/173249132/384664132-000baf5f-dc38-4561-a44b-653d3a0a6e2e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyMjE0ODUsIm5iZiI6MTczMTIyMTE4NSwicGF0aCI6Ii8xNzMyNDkxMzIvMzg0NjY0MTMyLTAwMGJhZjVmLWRjMzgtNDU2MS1hNDRiLTY1M2QzYTBhNmUyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMFQwNjQ2MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOWYwMTZiYWI0ODhmYjM1ODBmMGRlZDNjZmY5OTgxMGYyOTFmNGZkOTVkY2YyYjAwZDAxN2NhNTYyNWVjZTM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.FlV3J90m676NvqBoeCRyx8a_QF_KeZlf9UOiwn4S5hI) get_group_member_info和get_group_member_list的qq_level全是0

应该是对方隐藏等级了

**Comment by idranme** [comment]
> ![image](https://private-user-images.githubusercontent.com/173249132/384661617-96eb04b1-d037-457c-a100-e66c79683dbf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyMjE0ODUsIm5iZiI6MTczMTIyMTE4NSwicGF0aCI6Ii8xNzMyNDkxMzIvMzg0NjYxNjE3LTk2ZWIwNGIxLWQwMzctNDU3Yy1hMTAwLWU2NmM3OTY4M2RiZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMFQwNjQ2MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iN2RmOGYyOWIyMWNjZjhjMDc4YjM3YzU4N2E4NmM2MDc1NDZiNjg1NzhhOGJlNmMxOGM1ZGMzZjE0ZGIwMGIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5CUN01auZffOwLmj5ZSpfAguo82Z54wiEL4Dyr_co4c) 我记得我qq版本很高的来着

你之前反馈问题时使用了 9.9.12-26466

**Comment by idranme** [comment]
> 陌生人呢，不是好友并且不在群内的

我不确定

**Comment by Atrium4641** [comment]
> > ![image](https://private-user-images.githubusercontent.com/173249132/384664132-000baf5f-dc38-4561-a44b-653d3a0a6e2e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyMjE0ODUsIm5iZiI6MTczMTIyMTE4NSwicGF0aCI6Ii8xNzMyNDkxMzIvMzg0NjY0MTMyLTAwMGJhZjVmLWRjMzgtNDU2MS1hNDRiLTY1M2QzYTBhNmUyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMFQwNjQ2MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOWYwMTZiYWI0ODhmYjM1ODBmMGRlZDNjZmY5OTgxMGYyOTFmNGZkOTVkY2YyYjAwZDAxN2NhNTYyNWVjZTM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.FlV3J90m676NvqBoeCRyx8a_QF_KeZlf9UOiwn4S5hI) get_group_member_info和get_group_member_list的qq_level全是0
> 
> 应该是对方隐藏等级了

这是我，我没隐藏

**Comment by idranme** [comment]
> 这是我，我没隐藏

![888c8eaf04967e91cf7c26f4b2a86fad](https://github.com/user-attachments/assets/ee13daaa-6000-4b52-99ad-347c47b0764c)
我这里使用 get_group_member_info 可以正常获取

**Comment by idranme** [comment]
> 我要在有新人进群判断他的QQ等级是否大于10才能通过申请，应该如何实现

使用 `level` 字段
![image](https://github.com/user-attachments/assets/851400dd-6f8c-4c5e-ba9e-456352a5aa38)

**Comment by Atrium4641** [comment]
> > 我要在有新人进群判断他的QQ等级是否大于10才能通过申请，应该如何实现
> 
> 使用 `level` 字段 ![image](https://private-user-images.githubusercontent.com/96647698/384667277-851400dd-6f8c-4c5e-ba9e-456352a5aa38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyMjI4ODYsIm5iZiI6MTczMTIyMjU4NiwicGF0aCI6Ii85NjY0NzY5OC8zODQ2NjcyNzctODUxNDAwZGQtNmY4Yy00YzVlLWJhOWUtNDU2MzUyYTVhYTM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEwVDA3MDk0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyOTcxYjIyYzM1M2Y5YzJmNmNiMmFkZTUwYWU5YjhkMWE1Y2NhMWZhN2EyN2M5Y2U4YWE1YWJkNWMyMDdhYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.c6zcKddrrVB1DKVXbcp0gf1zncItVghpK7FeJV6WvoY)

这个不是群等级吗？
![image](https://github.com/user-attachments/assets/bc2b69a9-e8f5-46fe-88d2-3fde6457084a)

**Comment by idranme** [comment]
> 这个不是群等级吗？ ![image](https://private-user-images.githubusercontent.com/173249132/384667462-bc2b69a9-e8f5-46fe-88d2-3fde6457084a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyMjMwOTAsIm5iZiI6MTczMTIyMjc5MCwicGF0aCI6Ii8xNzMyNDkxMzIvMzg0NjY3NDYyLWJjMmI2OWE5LWU4ZjUtNDZmZS04OGQyLTNmZGU2NDU3MDg0YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMFQwNzEzMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNmFjY2QwMjk4YzA5MzFmYWNlYTZkZmNiNjc2MGZkMTI5MjE2YTU4MDRjMDI4NmU1M2UwN2VjMjRjNzFhNzc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.WB1E9-7EhR4zJjdkRqDB9Ye1JGHm2OjiNh-s_B__wFE)

get_stranger_info 的 `level` 不是群等级
