### ISSUE TITLE
[BUG] download_file 疑似调用超时

### ISSUE THREAD

**Issue by abc1763613206** [LLOneBot/LLOneBot#498]
### 系统版本

Windows Server 2022 Datacenter 21H2

### QQNT 版本

9.9.16-28971

### LLOneBot 版本

4.1.2

### OneBot 客户端

nonebot-adapter-onebot 2.4.3

### 发生了什么?

在通过反向 WS 调用 `download_file` 时，出现连接超时现象   
无论使用 url 或是 base64 直接投送文件都会触发。

### 如何复现

1. 使用反向 Websocket 方式连接 Nonebot
2. 使用类似如下代码调用 `download_file` 事件
```python
b64 = base64.b64encode(json_file.encode("utf-8")).decode("utf-8")
b64ret = await bot.download_file(base64=b64)
```
3. 观测到在使用 URL 或是 base64 均返回超时错误，其他消息没问题，即使 API_TIMEOUT 被设置为 45s。
可供参考的相关 issue：https://github.com/kitUIN/nonebot-plugin-ncm/issues/29

### 期望的结果?

正常完成下载，并和 `go-cqhttp` 一样正常返回

### LLOneBot 运行日志
为排除网络连接相关问题，使用 base64 传送文件，可在日志中正常观测：
```shell
2024/11/2 23:36:49 [info] [数据删除]([数据删除]) | onebot 收到反向 Websocket 消息 { action: 'download_file', params: { base64: 'WwogICA'... 161912 more characters }, echo: '62' }
```

之后未观测到后续上报事件。

### OneBot 客户端运行日志

```shell
11-02 23:37:33 [ERROR] miscurl | NetWorkError(message='WebSocket call api download_file timeout')
```

**Comment by cn1095** [comment]
如何设置超时呢 我也想试试改成久一点
我也遇到了超时 我在responseTimeout填了600000 都没有效果

```shell
session Error: Error with request send_group_msg, args: {"group_id":37***97*9,"message":[{"type":"video","data":{"file":"https://cn-sccd-ct-01-29.bilivideo.com/upgcxcode/83/24/981432483/981432483-1-16.mp4?e=ig8euxZM2rNcNbRVhwdVhwdlhWdVhwdVhoNvNC8BqJIzNbfq9rVEuxTEnE8L5F6VnEsSTx0vkX8fqJeYTj_lta53NCM=&uipk=5&nbs=1&deadline=1730619593&gen=playurlv2&os=bcache&oi=1848130790&trid=0000313d0e51cd5c42198a3556a0541ee380h&mid=0&platform=html5&og=cos&upsig=057a36ffd1b1329a397f6cba3f41b40d&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform,og&cdnid=62629&bvc=vod&nettype=0&f=h_0_0&bw=50996&logo=80000000","cache":0}}]}, retcode: 1200
```

**Comment by Shua-github** [comment]
我切换成napcatqq就好了。
![c7b53406-e0f3-4460-ae72-3af7efd71eaf](https://github.com/user-attachments/assets/2349602b-046d-4ca2-895a-93023f0a3b85)

**Comment by idranme** [comment]
v4.1.4 是否存在该问题？

**Comment by abc1763613206** [comment]
之前为了缓解问题迁移到了 NapCat ，刚刚重新测试了下，问题已经解决。
![image](https://github.com/user-attachments/assets/85b53ebb-b459-4fc0-a80c-0d8e0462f938)
