### ISSUE TITLE
[BUG] get_stranger_info 接口字段不全

### ISSUE THREAD

**Issue by phillaria** [LLOneBot/LLOneBot#499]
### 系统版本

Windows 10企业版 1909

### QQNT 版本

9.9.10-26909

### LLOneBot 版本

4.1.2

### OneBot 客户端

1.2.1

### 发生了什么?

get_stranger_info 接口字段不全（缺少deatail等字段）

### 如何复现

使用get_stranger_info 接口获取任意好友或群成员信息，查看返回的内容

### 期望的结果?

返回全部字段信息

**Comment by idranme** [comment]
你需要 `deatail` 里面的哪些字段？

**Comment by phillaria** [comment]
> 你需要 `deatail` 里面的哪些字段？

主要是所在城市吧，发现这个问题也是因为最近的天气预报获取不到城市了

**Comment by idranme** [comment]
v4.2.0 已增加 `city` 字段
