### ISSUE TITLE
[BUG] 与 Transitio 冲突

### ISSUE THREAD

**Issue by TransparentLC** [LLOneBot/LLOneBot#503]
### 系统版本

Windows 11 专业版 24H2

### QQNT 版本

9.9.16-28971

### LLOneBot 版本

4.1.4

### 发生了什么?

LLOneBot 可以正常使用，但是 Transitio 无法读取和应用样式，且在 Transitio 的设置界面点击“打开目录”没有反应。

Transitio 的设置界面的 console 有报错：

```
Uncaught TypeError: Cannot set properties of undefined (setting 'innerHTML')
    at showError (local:///C:\Program Files\Tencent\QQNT\resources\app\LiteLoaderQQNT\plugins\LLOneBot\renderer\index.js:346:26)
```

Transitio 的作者认为是 LLOneBot 的 hook 操作导致的问题，与 Transitio 无关。

在 Transitio 的 repo 提出的 issue：https://github.com/PRO-2684/transitio/issues/52

### 如何复现

1. 安装 LLOneBot 4.1.4 和 Transitio 1.5.4（当前最新版），移除其他插件
2. 在 `/path/to/LiteLoaderQQNT/data/transitio/styles` 随便添加一个样式
3. 运行 QQ，打开 Transitio 插件的设置，检查样式列表

### 期望的结果?

不产生冲突

### LLOneBot 运行日志

[llonebot-2024-11-10 17-30-36.log](https://github.com/user-attachments/files/17690906/llonebot-2024-11-10.17-30-36.log)

**Comment by linyuchen** [comment]
4.2.1已修复

**Comment by TransparentLC** [comment]
用 4.2.1 试了一下，似乎还存在冲突问题：

1. 运行 QQ，打开 Transitio 的设置，此时没有任何样式
2. 添加一些用户样式，现在用户样式列表可以读取添加的样式了
3. 打开一个聊天窗口，刚刚添加的样式生效了
4. 关闭设置再重新打开 Transitio 的设置，**刚刚添加的样式消失了**
5. 再打开一个聊天窗口（可以和上一个是同一个），此时**样式没有生效**
6. 重新导入样式并且不要关闭设置，打开关闭再打开一个聊天窗口，此时样式没有生效
7. 在设置中打开/关闭一个样式，对应的样式在刚刚打开的聊天窗口 A 上会生效/失效，但是其他的样式仍然没有生效，关闭聊天窗口 A 后再打开 A，样式生效情况和上次打开相同，关闭后打开别的聊天窗口 B 则所有样式失效，再打开 A 也是所有样式失效

**Comment by linyuchen** [comment]
> 用 4.2.1 试了一下，似乎还存在冲突问题：
> 
> 1. 运行 QQ，打开 Transitio 的设置，此时没有任何样式
> 2. 添加一些用户样式，现在用户样式列表可以读取添加的样式了
> 3. 打开一个聊天窗口，刚刚添加的样式生效了
> 4. 关闭设置再重新打开 Transitio 的设置，**刚刚添加的样式消失了**
> 5. 再打开一个聊天窗口（可以和上一个是同一个），此时**样式没有生效**
> 6. 重新导入样式并且不要关闭设置，打开关闭再打开一个聊天窗口，此时样式没有生效
> 7. 在设置中打开/关闭一个样式，对应的样式在刚刚打开的聊天窗口 A 上会生效/失效，但是其他的样式仍然没有生效，关闭聊天窗口 A 后再打开 A，样式生效情况和上次打开相同，关闭后打开别的聊天窗口 B 则所有样式失效，再打开 A 也是所有样式失效

感谢测试，4.2.2已修复

**Comment by TransparentLC** [comment]
没问题了，谢谢～
