### ISSUE TITLE
[BUG] 出现 crychic 错误而登陆不了 QQ

### ISSUE THREAD

**Issue by tianxiu2b2t** [LLOneBot/LLOneBot#509]
### 系统版本

Windows 11

### QQNT 版本

9.9.15

### LLOneBot 版本

4.1.4

### 发生了什么?

\\?\D:\llob\data\LLOneBot\temp\crychic-win32-x64-DtkSVC2T.node
crychic-win32-x64-DtkSVC2T.node
会出现打不开qq的问题

### 如何复现

1. 正常登录之后就crash这个问题

### 期望的结果?

应该正常打开

**Comment by linyuchen** [comment]
QQ版本要求大于等于27333，低于(不包含)28060

**Comment by tianxiu2b2t** [comment]
如果我安装最新的qq为 QQ_9.9.16_241118_x64_01 则出现闪退问题

**Comment by tianxiu2b2t** [comment]
[llonebot-2024-11-22 13-45-55.log](https://github.com/user-attachments/files/17868965/llonebot-2024-11-22.13-45-55.log)
[llonebot-2024-11-22 18-49-27.log](https://github.com/user-attachments/files/17868966/llonebot-2024-11-22.18-49-27.log)
[llonebot-2024-11-22 18-51-09.log](https://github.com/user-attachments/files/17868969/llonebot-2024-11-22.18-51-09.log)
[llonebot-2024-11-22 18-51-22.log](https://github.com/user-attachments/files/17868970/llonebot-2024-11-22.18-51-22.log)

**Comment by idranme** [comment]
截图一下报错界面

**Comment by tianxiu2b2t** [comment]
> 截图一下报错界面

我没办法截图，如果你要 dmp 文件我可以发，毕竟你说报错界面我该怎么截呢……

**Comment by idranme** [comment]
> 我没办法截图，如果你要 dmp 文件我可以发，毕竟你说报错界面我该怎么截呢……

QQ 在崩溃时会弹出一个界面

**Comment by idranme** [comment]
> 那就是 qq 的 crash 软件

你的 QQ 崩溃时没有弹出这个软件的界面吗？

**Comment by tianxiu2b2t** [comment]
> > 那就是 qq 的 crash 软件
> 
> 你的 QQ 崩溃时没有弹出这个软件的界面吗？

弹了

**Comment by idranme** [comment]
> 弹了

我想看一眼那个界面
