### ISSUE TITLE
[BUG] 调用API发送好友信息失败

### ISSUE THREAD

**Issue by Fiend-14574572** [LLOneBot/LLOneBot#512]
### 系统版本

Windows 10 专业版 21H1

### QQNT 版本

9.9.16

### LLOneBot 版本

4.4.1

### OneBot 客户端

4.4.1

### 发生了什么?

正常发送好友信息，突然出现调用接口失效
[url=https://imgse.com/i/pAfUlU1][img]https://s21.ax1x.com/2024/11/22/pAfUlU1.png[/img][/url]
[url=https://imgse.com/i/pAfUQER][img]https://s21.ax1x.com/2024/11/22/pAfUQER.png[/img][/url]
[url=https://imgse.com/i/pAfU14x][img]https://s21.ax1x.com/2024/11/22/pAfU14x.png[/img][/url]
[url=https://imgse.com/i/pAfUuDJ][img]https://s21.ax1x.com/2024/11/22/pAfUuDJ.png[/img][/url]
[url=https://imgse.com/i/pAfUKb9][img]https://s21.ax1x.com/2024/11/22/pAfUKb9.png[/img][/url]

### 如何复现

群发好友招呼消息

### 期望的结果?

修改一下

### LLOneBot 运行日志

```shell
https://wxdf-zxh.lanzouj.com/iG4jA2fwsxij
```

**Comment by idranme** [comment]
Duplicate of #513
