### ISSUE TITLE
[BUG] 调用API发送好友信息突然失效

### ISSUE THREAD

**Issue by Fiend-14574572** [LLOneBot/LLOneBot#513]
### 系统版本

Windows 10 专业版 21H1

### QQNT 版本

9.9.16

### LLOneBot 版本

4.4.1

### OneBot 客户端

4.4.1

### 发生了什么?

正常发送好友信息，突然出现调用接口失效
<img src="https://wmimg.com/i/559/2024/11/6740a844afc09.png" alt="捕23获.PNG" title="捕23获.PNG" />
<img src="https://wmimg.com/i/559/2024/11/6740a84499f14.png" alt="捕666666获.PNG" title="捕666666获.PNG" />
<img src="https://wmimg.com/i/559/2024/11/6740a844b41a8.png" alt="1捕获.PNG" title="1捕获.PNG" />
<img src="https://wmimg.com/i/559/2024/11/6740a844b0f86.png" alt="9966捕获.PNG" title="9966捕获.PNG" />
<img src="https://wmimg.com/i/559/2024/11/6740a844e124d.png" alt="捕获.PNG" title="捕获.PNG" />
https://wmimg.com/i/559/2024/11/6740a844afc09.png
https://wmimg.com/i/559/2024/11/6740a84499f14.png
https://wmimg.com/i/559/2024/11/6740a844b41a8.png
https://wmimg.com/i/559/2024/11/6740a844b0f86.png
https://wmimg.com/i/559/2024/11/6740a844e124d.png

### 如何复现

群发好友招呼信息

### 期望的结果?

修复

### LLOneBot 运行日志

```shell
https://wxdf-zxh.lanzouj.com/iG4jA2fwsxij

日志太大了，上传到蓝奏了，dll改txt
```

### OneBot 客户端运行日志

```shell
https://wxdf-zxh.lanzouj.com/iG4jA2fwsxij

日志太大了，上传到蓝奏了，dll改txt
```

**Comment by idranme** [comment]
https://multimedia.nt.qq.com.cn/download?appid=1406&fileid=EhSBojFideUlGqUrE4jj94VUo22O7hixxCIg_goo6szJnpfwiQMyBHByb2RaEB4x5YGMPl8bU3X50Qk_NqY&spec=0&rkey=CAQSKAB6JWENi5LM78MghxjPiUNegKOAIfz2xRdmxohZ22MVa-rD35W-fnQ

图片资源过期
