### ISSUE TITLE
[BUG] 你的账号当前登录已失效

### ISSUE THREAD

**Issue by 759039446** [LLOneBot/LLOneBot#514]
### 系统版本

windows 10

### QQNT 版本

9.9.16-29927

### LLOneBot 版本

v4.4.1

### OneBot 客户端

1

### 发生了什么?

正常使用，没有其他特殊操作，会频繁提示下线通知，你的账号当前登录已失效，请重新登录，目前排查是和插件有一定关系。
请问开发者是否有遇到这种情况，是如何解决的
![0C3A01EF09A5F4653FEA1988543A58E6](https://github.com/user-attachments/assets/3750c434-05a0-4bfa-8761-f37612208eb6)

### 如何复现

使用环境：
 挂的云服务器
用到的功能：
1.开启了http消息转发
2.发送消息的接口
QQ和插件均升级至2024.11.24的最新版本
目前已经有三四台服务器都遇到了这情况，自己电脑不会

### 期望的结果?

不出现下线通知 

### LLOneBot 运行日志

```shell
0
```

### OneBot 客户端运行日志

```shell
0
```

**Comment by EatHatsuneShallots** [comment]
https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues/1032

**Comment by linyuchen** [comment]
最近风控力度加强，大概是触发了TX的检测，所有框架都会遇到这种问题

**Comment by TLBLL** [comment]
试一下这个方法，我用这个之后就不会频繁掉线了
如果使用LiteLoaderQQNT插件加载器，对于 Windows 系统用户，还需要去除 QQNT 文件校验，以下有两种方式，DLLHijackMethod（推荐，简单好用）https://github.com/LiteLoaderQQNT/QQNTFileVerifyPatch/tree/DLLHijackMethod，在 Release 下载 dll 文件，重命名为 dbghelp.dll 放入 QQ.exe 同级目录下即可
