### ISSUE TITLE
[BUG] 调用接口获取被过滤的加群申请的时候，NTQQ会给出提示窗口，该窗口不自动关闭，则该接口无法再次请求。

### ISSUE THREAD

**Issue by leriocn** [LLOneBot/LLOneBot#515]
### 系统版本

WIN11

### QQNT 版本

版本: 9.9.15-28498 (64位)

### LLOneBot 版本

4.4.1

### OneBot 客户端

POSTMAN

### 发生了什么?

![image](https://github.com/user-attachments/assets/2b6e5c82-76c0-4788-89d3-2b275d6f3826)

{
    "status": "failed",
    "retcode": 200,
    "data": null,
    "message": "ntqq api timeout IPC_UP_2, ns-WindowApi-2, openExternalWindow, [\"GroupNotifyFilterWindow\"]",
    "wording": "ntqq api timeout IPC_UP_2, ns-WindowApi-2, openExternalWindow, [\"GroupNotifyFilterWindow\"]"
}

### 如何复现

直接接口调用：localhost:3001/get_group_ignore_add_request

### 期望的结果?

正常返回如下：
{
    "status": "ok",
    "retcode": 0,
    "data": [
        {
            "group_id": ******，
            "user_id": *******,
            "flag": "1732545*****212"
        }
    ],
    "message": "",
    "wording": ""
}

**Comment by linyuchen** [comment]
4.4.2 已经将 获取被过滤的加群申请 的接口合并到 `get_group_system_msg `，不再会弹窗
