### ISSUE TITLE
[功能建议]增加群通知里面的申请加群列表API

### ISSUE THREAD

**Issue by WJHXD1B** [LLOneBot/LLOneBot#518]
这样当Bot因一些特殊情况恢复后可以快速的处理加群请求

**Comment by linyuchen** [comment]
https://llonebot.apifox.cn/api-227238038

**Comment by WJHXD1B** [comment]
> https://llonebot.apifox.cn/api-227238038

但是这个缺少`flag`参数

**Comment by linyuchen** [comment]
> > https://llonebot.apifox.cn/api-227238038
> 
> 但是这个缺少`flag`参数

用 request_id

**Comment by WJHXD1B** [comment]
> > > https://llonebot.apifox.cn/api-227238038
> > 
> > 
> > 但是这个缺少`flag`参数
> 
> 用 request_id

使用`flag=request_id`并请求后，虽返回成功，但并没有加群
```
{
    "status": "ok",
    "retcode": 0,
    "data": null,
    "message": "",
    "wording": ""
}
```

**Comment by idranme** [comment]
> 使用`flag=request_id`并请求后，虽返回成功，但并没有加群
> 
> ```
> {
>     "status": "ok",
>     "retcode": 0,
>     "data": null,
>     "message": "",
>     "wording": ""
> }
> ```

v4.4.3 已修复
