### ISSUE TITLE
[功能求助]请问是否支持ARM的WINDOWS，比如ARM的win11上运行

### ISSUE THREAD

**Issue by dragon0629** [LLOneBot/LLOneBot#519]
RT，一键安装脚本不支持ARM的windows运行
尝试过手动安装，启动会提示QQ损坏（放了环境跳过监测那个dll）。
在多个群咨询过没有得到比较准确的答复
所以这边咨询一下，是否可以在arm版的windows上运行起来 0_0

**Comment by linyuchen** [comment]
支持的，能安装 NTQQ 的系统都能，arm 的 Windows 要下载 [dbghelp_arm64.dll](https://github.com/LiteLoaderQQNT/QQNTFileVerifyPatch/releases/tag/DllHijack_1.1.1) 并重命名成 dbghelp.dll 放到 QQ.exe 旁，但是这个 dll 支持的QQ版本应该是 28060 以下？

**Comment by dragon0629** [comment]
![image](https://github.com/user-attachments/assets/594be20b-d573-428a-88eb-b82bc3805037)
似乎这个有一些问题0_0 

之前官网下载的这些可以安装登陆
![image](https://github.com/user-attachments/assets/a0f7ac55-c9c0-4278-8902-5d11923301a9)

系统信息：
![image](https://github.com/user-attachments/assets/f0d3a767-59bd-40f0-bd9c-cd86fbb347d0)

**Comment by linyuchen** [comment]
> ![image](https://github.com/user-attachments/assets/594be20b-d573-428a-88eb-b82bc3805037)
> 
> 似乎这个有一些问题0_0 
> 
> 
> 
> 之前官网下载的这些可以安装登陆
> 
> ![image](https://github.com/user-attachments/assets/a0f7ac55-c9c0-4278-8902-5d11923301a9)
> 
> 
> 
> 系统信息：
> 
> ![image](https://github.com/user-attachments/assets/f0d3a767-59bd-40f0-bd9c-cd86fbb347d0)
> 
> 
> 
> 
> 
> 

啊这，你试试按照x64的去按照吧，不用ARM的

**Comment by dragon0629** [comment]
啊这，但是安装的脚本无法运行囧，咨询过说是不支持ARM系统上运行
![image](https://github.com/user-attachments/assets/caee2228-143f-4565-b32b-85c11b4c9b42)
混乱中，我再摸索摸索0_0
