### ISSUE TITLE
[Feature] 可不可以支持 Satori 协议

### ISSUE THREAD

**Issue by CyanChanges** [LLOneBot/LLOneBot#52]
感谢作者制作了这个插件, 很好用
如果能够支持 Satori 协议就更好了

### 原因
Satori 有完整的协议文档 
<https://satori.chat/zh-CN> or <https://satori.js.org/>
[GitHub 源代码](https://github.com/satorijs/satori)
相比于 Onebot 更加清晰, 更加通用

使用了 TypeScript 开发 
协议中类型等常量在 `@satorijs/protocol` 中均有列出 <https://github.com/satorijs/satori/blob/master/packages/protocol/>

并且, 很多框架都支持 Satori 协议
[Koishi](https://koishi.chat/) - [@koishijs/plugin-adapter-satori](https://github.com/koishijs/upstream/tree/main/adapter/satori) 上游 [@satorijs/adapter-satori](https://github.com/satorijs/satori/tree/master/adapters/satori)
[Nonebot2](https://nonebot.dev) - [nonebot-adapter-satori](https://github.com/nonebot/adapter-satori)
[Avilla](https://graia.readthedocs.io/avilla) - <https://github.com/GraiaProject/Avilla/tree/master/avilla/satori>
而 Onebot 已经被 Koishi 移入社区支持, 
类似的 Chronocat 也推荐使用 Satori 协议, 而不是 Red (一个基于 Onebot 协议的扩展协议)

### 测试?
使用 [Koishi](https://koishi.chat/zh-CN/) 框架, 测试 Bot 的日常使用
使用 [logirl](https://github.com/ilharp/logiri) 可以在终端中连接 Satori 以接受并显示消息

**Comment by linyuchen** [comment]
目前在完善一些基础功能，比如群管理的一些操作
现在的代码解耦做的还是可以的，添加新的协议很简单，就看有没有时间做了，多来点PR就好了

**Comment by CyanChanges** [comment]
> 目前在完善一些基础功能，比如群管理的一些操作 现在的代码解耦做的还是可以的，添加新的协议很简单，就看有没有时间做了，多来点PR就好了

我可能要稍微熟悉熟悉代码(

**Comment by CyanChanges** [comment]
scripts 里面好多 npm run 的, 要不要考虑试试用 yarn 什么的 (

**Comment by linyuchen** [comment]
> scripts 里面好多 npm run 的, 要不要考虑试试用 yarn 什么的 (

可以的呀，不过实际上用的包很少，yarn可能优势不大，你可以试着对比下，我没试过。
另外如果能把webpack改成vite就好了，webpack有点慢。
更多细节你可以加tg群聊（如果你方便的话，链接在readme

**Comment by CyanChanges** [comment]
> > scripts 里面好多 npm run 的, 要不要考虑试试用 yarn 什么的 (
> 
> 可以的呀，不过实际上用的包很少，yarn可能优势不大，你可以试着对比下，我没试过。 另外如果能把webpack改成vite就好了，webpack有点慢。 更多细节你可以加tg群聊（如果你方便的话，链接在readme

加了, 改 Vite 的话我看看, 只直接用过 rollup 和 esbuild (

**Comment by MliKiowa** [comment]
> > > scripts 里面好多 npm run 的, 要不要考虑试试用 yarn 什么的 (
> > 
> > 
> > 可以的呀，不过实际上用的包很少，yarn可能优势不大，你可以试着对比下，我没试过。 另外如果能把webpack改成vite就好了，webpack有点慢。 更多细节你可以加tg群聊（如果你方便的话，链接在readme
> 
> 改好了, 跑起来了一点 #74

你这个方案需要多余依赖 而且版本已经偏离main太多 我在 #97 直接基于main修改了

**Comment by linyuchen** [comment]
Chronocat 已复活
