### ISSUE TITLE
希望可以增加get_stranger_info接口的信息

### ISSUE THREAD

**Issue by phillaria** [LLOneBot/LLOneBot#526]
就是旧版本有过的详细信息（detail）字段，新版本没有了；之前在#499提过一次，但现在发现信息还是不太够……

目前发现所在国家和生日信息是能用到的：所在国家用于天气预报获取所在地区时，排除不在中国的（可能是随便填的）；生日信息用于生日当天发祝福语

**Comment by idranme** [comment]
v4.5.0 已增加返回的信息
