### ISSUE TITLE
[BUG] 完全转发一个消息（带图片），发到第一个群会报错，第二个群之后就正常

### ISSUE THREAD

**Issue by moumouren** [LLOneBot/LLOneBot#527]
### 系统版本

windows 2012

### QQNT 版本

9.9.16-29456 (64位)

### LLOneBot 版本

4.4.3

### OneBot 客户端

使用http协议链接

### 发生了什么?

转发消息带图片 提示不正常

### 如何复现

就是完全转发别的群的消息（带图片的）的时候就会提示这个，但是发第二次就正常了，。
比如完全转发a群的消息到b，c两个群，b群就会提示错误发不出，c群就可以正常发出去

### 期望的结果?

应该可以正常发送出去才对

### LLOneBot 运行日志

```shell
{"status":"failed","retcode":200,"data":null,"message":"Error: ENOENT: no such file or directory, open 'C:\\Users\\Administrator\\Desktop\\NTQQ9.9.16.29456绿色版\\QQNT\\versions\\9.9.16-29456\\resources\\app\\app_launcher\\LiteLoaderQQNT\\data\\LLOneBot\\temp\\0'","wording":"Error: ENOENT: no such file or directory, open 'C:\\Users\\Administrator\\Desktop\\NTQQ9.9.16.29456绿色版\\QQNT\\versions\\9.9.16-29456\\resources\\app\\app_launcher\\LiteLoaderQQNT\\data\\LLOneBot\\temp\\0'"}
```

**Comment by moumouren** [comment]
通过http发送的消息是这样的格式：测试消息[CQ:image,file={8393CCBD-7B31-0248-D3FC-250D46430B13}.jpg,subType=0,url=https://gchat.qpic.cn/gchatpic_new/2389883716/2181841592-2601656191-8393CCBD7B310248D3FC250D46430B13/0?term=255&amp;is_origin=0,file_size=5545]

**Comment by moumouren** [comment]
4.5版本也会出现如上bug，错误返回如下，之前4.4.3也有这个错误返回，同样是转发倒a群提示错误，b群就正常。

原消息：
测试[CQ:image,file={D86CEFE7-65FB-CEAD-57AE-932CF03096A1}.jpg,subType=0,url=https://gchat.qpic.cn/gchatpic_new/2389883716/2181841592-2601656191-D86CEFE765FBCEAD57AE932CF03096A1/0?term=255&amp;is_origin=0,file_size=5545]

错误返回：{"status":"failed","retcode":200,"data":null,"message":"ntqq api call failed, nodeIKernelMsgService/sendMsg, {\"result\":-1,\"errMsg\":\"rich media transfer failed\"}","wording":"ntqq api call failed, nodeIKernelMsgService/sendMsg, {\"result\":-1,\"errMsg\":\"rich media transfer failed\"}"}

**Comment by idranme** [comment]
v4.5.1 是否解决了该问题？

**Comment by moumouren** [comment]
> v4.5.1 是否解决了该问题？

没有解决，依然报错，你看楼下我发了一个4.5.1的报错，之前4.4.3也会有这个报错

**Comment by moumouren** [comment]
> v4.5.1 是否解决了该问题？

问题解决了，谢谢
