### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by baixiangyuan** [LLOneBot/LLOneBot#528]
### 系统版本

win10

### QQNT 版本

9.9.7

### LLOneBot 版本

2.21.2

### 发生了什么?

死了

### 如何复现

1

### 期望的结果?

1

**Comment by itzdrli** [comment]
合影留念

**Comment by baixiangyuan** [comment]
你好。已收到你的邮件，我会在起床后尽快处理。————————————这是来自QQ邮箱的自动回复邮件。

**Comment by baixiangyuan** [comment]
哈哈哈

**Comment by leopard-1** [comment]
合影留念
![Image_1734701619219](https://github.com/user-attachments/assets/d12975e7-dc3c-468b-b712-4037d4818ed1)
在这里放一只铃兰
