### ISSUE TITLE
[Feature] 是否有兼容go-cqhttp的需求

### ISSUE THREAD

**Issue by disymayufei** [LLOneBot/LLOneBot#55]
尽管go-cqhttp基于OneBot API开发，然而其部分包对OneBot API规定的内容有所扩展（如get_version_info这一API，go-cqhttp除了实现了OneBot API规定必须实现的```app_name```，```app_version```和```protocol_version```外，还额外添加了许多其他信息（如运行时环境参数，运行系统等））。现有的机器人插件大部分基于go-cqhttp开发，因此目前部分API由于缺少go-cqhttp独有的部分字段，而使得这些插件无法直接迁移。

想询问一下作者您是否有意向让本插件做到尽量完全兼容go-cqhttp（尽管这样会引入一些历史包袱），如果您有意向完成该工作，我可以着手先尝试对一些API做出修改（前提是开学后我这边别太忙）

**Comment by disymayufei** [comment]
啊抱歉点的太快了，不应该有bug这个标签的，这不是bug反馈（汗）

**Comment by linyuchen** [comment]
我个人是没有打算兼容go-cqhttp的，看有没有人愿意一起开发，现在主要是把基础功能完善，基础模块抽离出来，新增协议的话不是什么难事，也许以后会加入新的协议支持

**Comment by MliKiowa** [comment]
> 我个人是没有打算兼容go-cqhttp的，看有没有人愿意一起开发，现在主要是把基础功能完善，基础模块抽离出来，新增协议的话不是什么难事，也许以后会加入新的协议支持

有联系方式吗？（我想问问某些问题

**Comment by linyuchen** [comment]
> > 我个人是没有打算兼容go-cqhttp的，看有没有人愿意一起开发，现在主要是把基础功能完善，基础模块抽离出来，新增协议的话不是什么难事，也许以后会加入新的协议支持
> 
> 有联系方式吗？（我想问问某些问题

直接开issue问吧

**Comment by MliKiowa** [comment]
> > > 我个人是没有打算兼容go-cqhttp的，看有没有人愿意一起开发，现在主要是把基础功能完善，基础模块抽离出来，新增协议的话不是什么难事，也许以后会加入新的协议支持
> > 
> > 
> > 有联系方式吗？（我想问问某些问题
> 
> 直接开issue问吧

不是project的问题啦，是关于ntqq的某些问题

**Comment by linyuchen** [comment]
不知不觉已经在兼容了
