### ISSUE TITLE
无法上传mp4文件

### ISSUE THREAD

**Issue by Ray-lea** [LLOneBot/LLOneBot#64]
QQ版本：9.9.7-20979

LLOneBot版本：3.6.0

调用LLOneBot的方式或者应用端(如postman直接调用，或NoneBot2、Koishi)：Trss-yunzai

BUG描述：无法上传mp4文件

复现步骤：上传mp4文件

LLOneBot日志:

> 2024/2/22 14:21:53 洛箐箐(脱敏内容): 可以进行发送消息，设置发送成功回调 {} 
> 
> 2024/2/22 14:21:53 洛箐箐(脱敏内容): ws 消息上报 ws://localhost:2536/go-cqhttp {"status":"ok","retcode":0,"data":{"message_id":脱敏内容},"message":"","wording":"","echo":"41325f34-511a-440d-afdd-7267bdeac730"} 
> 
> 2024/2/22 14:21:54 洛箐箐(脱敏内容): 收到反向Websocket消息 {"action":"send_msg","params":{"group_id":脱敏内容,"message":[{"type":"video","data":{"file":"./data/rcmp4/脱敏内容/temp.mp4"}}]},"echo":"9741aad6-4896-4007-9787-2d726dffb052"} 
> 
> 2024/2/22 14:21:54 洛箐箐(脱敏内容): ws 消息上报 ws://localhost:2536/go-cqhttp {"status":"failed","retcode":1200,"data":null,"message":"消息体无法解析","wording":"消息体无法解析","echo":"9741aad6-4896-4007-9787-2d726dffb052"}

**Comment by bianyuan456** [comment]
我也需要上传文件的api。盼着你的问题得到解决

**Comment by KeluIsAfkeru** [comment]
+1，也遇到这样的问题

**Comment by linyuchen** [comment]
最新版已支持发送视频，但是我看你的日志发送格式有点问题，file字段是如果是本地文件应该是file:///d:\\a.mp4这种

**Comment by linyuchen** [comment]
> 最新版已支持发送视频，但是我看你的日志发送格式有点问题，file字段是如果是本地文件应该是file:///d:\a.mp4这种

3.11.0现在支持直接路径了，不需要file://开头
