### ISSUE TITLE
[Feature] 实现获取“列表”相关的各类功

### ISSUE THREAD

**Issue by jiangyin14** [LLOneBot/LLOneBot#72]
没法获得群列表 没法获得好友列表 没法获得群成员列表 没法获得监听退群成员 没法主动退群
![image](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/assets/106649516/f6d3cb70-fc14-448a-8264-7b76dd54201c)
这种有号 但是没昵称

比如说 能获知谁退群了 但是自己没法退 因为没法获知自己的群列表 但是能收到信息推送的群号

请求实现。

**Comment by linyuchen** [comment]
看你的描述，似乎是bug？有点不太理解你说的。
是列表相关api调用返回为空吗？
如果是bug，按照bug模板填写一下，不然我没法定位问题所在。

**Comment by jiangyin14** [comment]
就是go-cqhttp怼进去能用 这个怼进去用不了，根据 @disymayufei 所说，它没有做这块的实现。

我使用的具体的项目repo是https://github.com/TimeRainStarSky/Yunzai

关于实现对接go-cqhttp（Onebot接口）的代码在项目/plugins/adapter/go-cqhttp.js

**Comment by Ray-lea** [comment]
该bug疑似代码有误，最近我也遇到过，联系插件作者修好了，建议联系插件作者适配trss-yunzai

**Comment by jiangyin14** [comment]
> undefined相关bug疑似代码有误，最近我也遇到过，联系插件作者修好了，建议联系插件作者适配trss-yunzai

版本undefined的问题我和 @disymayufei  做了研究，应该是go-cqhttp实现了一些非OneBot标准之内的额外字段，指示版本信息并非OneBot规范中的一部分，而go-cqhttp是有的，而且TRSSyz也适配了。

现在我发现，在很多地方都出现了Undefined之类的信息，我认为这些不是巧合。可能是在信息处理上有一些问题，而且出现了很多玄学的错误
