### ISSUE TITLE
获取群主和管理员信息失败了，data里没有role

### ISSUE THREAD

**Issue by zlove7i** [LLOneBot/LLOneBot#73]
![Screenshot_2024-02-23-16-17-24-636_com microsoft rdc androidx-edit](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/assets/98206011/71e6b3ee-964e-486d-8357-8dfd587428aa)

**Comment by linyuchen** [comment]
[v3.7.0](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/releases) fixed
