### ISSUE TITLE
[Feature] 自动清理本地图片缓存

### ISSUE THREAD

**Issue by ShiaBox** [LLOneBot/LLOneBot#76]
就十几个群的测试帐号，1天1GB聊天缓存，小硬盘服务器有些绷不住。
能否添加自动清理聊天内容及图片缓存的功能？（或者有没有相关其他实现此功能的插件？🤣）

**Comment by sangxiang1** [comment]
bat

> 就十几个群的测试帐号，1天1GB聊天缓存，小硬盘服务器有些绷不住。 能否添加自动清理聊天内容及图片缓存的功能？（或者有没有相关其他实现此功能的插件？🤣）

用cmd定时循环删除.bat，批处理文件执行

**Comment by linyuchen** [comment]
[v3.8](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/releases)新增了自动删除功能

**Comment by Elflare** [comment]
> [v3.8](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/releases)新增了自动删除功能

建议延长删除时间，或能设置删除时间。因为很多插件会用到之前的图片

**Comment by linyuchen** [comment]
> > [v3.8](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/releases)新增了自动删除功能
> 
> 建议延长删除时间，或能设置删除时间。因为很多插件会用到之前的图片

[v3.11.0](https://github.com/LLOneBot/LLOneBot/releases)已支持设置删除时间
