### ISSUE TITLE
无法获取加群人QQ号码

### ISSUE THREAD

**Issue by ALittle-Cool** [LLOneBot/LLOneBot#77]
QQ版本：9.9.7-21484

LLOneBot版本：3.7.0

调用LLOneBot的方式或者应用端(如postman直接调用，或NoneBot2、Koishi)：

BUG描述：无法获取加群人QQ号码

复现步骤：有人加群的时候

LLOneBot日志:
): ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelGroupService/getSingleScreenNotifies ["nodeIKernelGroupService/getSingleScreenNotifies",{"doubt":false,"startSeq":"","number":14},null] 

2024/2/24 09:38:43 PlusNEBot(2896803955): ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelProfileService/getUserSimpleInfo ["nodeIKernelProfileService/getUserSimpleInfo",{"force":true,"uids":["u_gk3_dCsO39hFdXraBDpN0A"]},null] 

2024/2/24 09:38:43 PlusNEBot(2896803955): 获取加群人QQ号失败 ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelProfileService/getUserSimpleInfo, nodeIKernelProfileService/getUserSimpleInfo,[object Object],

**Comment by linyuchen** [comment]
[v3.8](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/releases)fixed
