### ISSUE TITLE
希望收到的图片消息段中有"url"字段，即"http_file"改为"url"

### ISSUE THREAD

**Issue by super1207** [LLOneBot/LLOneBot#81]
QQ版本：最新 9.9.7-21357 (64位)

LLOneBot版本：最新 3.7.0

调用LLOneBot的方式或者应用端(如postman直接调用，或NoneBot2、Koishi)：postman

BUG描述： 希望收到的图片消息段中有“url”字段，即"http_file"改为"url"。

复现步骤：

![image](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/assets/30586004/b226db94-fb95-4d09-8fc9-0feb8073fbbc)

![image](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/assets/30586004/e9a02b24-f23e-4512-a50d-c571e09c8eb2)

LLOneBot日志: -

**Comment by linyuchen** [comment]
感谢提醒，[v3.8](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/releases)已修正

**Comment by super1207** [comment]
已经测试，没有问题！先close issue了
