### ISSUE TITLE
send_private_forward_msg时直接引用message_id的子消息不呈现

### ISSUE THREAD

**Issue by leihao** [LLOneBot/LLOneBot#93]
QQ版本：3.2.5-21453

LLOneBot版本：3.9.0

调用LLOneBot的方式或者应用端(如postman直接调用，或NoneBot2、Koishi)：nonebot

BUG描述：send_private_forward_msg messsages里包含直接引用message id类型的node时,未正确发送
![image](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/assets/1472064/db33f991-2178-4d25-881a-de0f5ea67712)

复现步骤：

```
msg_list.append({
            "type": "node",
            "data": {
                "name": "BOT",
                "uin": f"{bot.self_id}",
                "content": f"{recall_user_name} ({event.user_id}) \n在群聊 {group_name} ({event.group_id}) 撤回了一条消息",
            },
        })
msg_list.append({
             "type": "node",
             "data": {
                 "name": "BOT",
                 "uin": f"{bot.self_id}",
                 "content": f"{recall_message_content['message']}",
             },
         })        
msg_list.append({
             "type": "node",
             "data": {
                 "id": recall_message_id
             }
         })
await bot.send_private_forward_msg(user_id=superuser, messages=msg_list)
```

LLOneBot日志:

`2/28/2024, 6:33:53 AM Toss(2112403019): 收到反向Websocket消息 {"action":"send_private_forward_msg","params":{"user_id":"1***7","messages":[{"type":"node","data":{"name":"BOT","uin":"2***9","content":"OL (1***7) \n在群聊 A***群 (7***3) 撤回了一条消息"}},{"type":"node","data":{"name":"BOT","uin":"2***9","content":"[{'data': {'text': '测试'}, 'type': 'text'}]"}},{"type":"node","data":{"id":1709***347}}]},"echo":"38"}`

**Comment by linyuchen** [comment]
[v3.11.0](https://github.com/LLOneBot/LLOneBot/releases)已修复
