### ISSUE TITLE
[Feature] 建议支持get_image这个api

### ISSUE THREAD

**Issue by Elflare** [LLOneBot/LLOneBot#96]
![image](https://github.com/LLOneBot/LLOneBot/assets/31814960/7540c82d-01d0-477a-aec6-0500b9dd1301)

**Comment by linyuchen** [comment]
[v3.11.0](https://github.com/LLOneBot/LLOneBot/releases)已支持

**Comment by Elflare** [comment]
> [v3.11.0](https://github.com/LLOneBot/LLOneBot/releases)已支持

感谢
