### ISSUE TITLE
Missing X-Self-ID Header

### ISSUE THREAD

**Issue by WindraiteLesd** [LLOneBot/LLOneBot#98]
QQ版本：9.9.7-21484

LLOneBot版本：3.11.0

调用LLOneBot的方式或者应用端(如postman直接调用，或NoneBot2、Koishi)：nonebot2

BUG描述：Missing X-Self-ID Header导致连接断开

复现步骤：通过本插件以反向ws连接OnebotV11协议的nonebot2或TRSS-Yunzai

LLOneBot日志:
```
2024/3/2 18:19:57 : ntqq api timeout IPC_UP_2, ns-GlobalDataApi-2, fetchAuthData ["fetchAuthData"] 

2024/3/2 18:19:57 : retry get self info 

2024/3/2 18:19:57 : Trying to connect to the websocket server: ws://127.0.0.1:8080/onebot/v11/ws 

2024/3/2 18:19:57 : {} 

2024/3/2 18:19:57 : The websocket connection: ws://127.0.0.1:8080/onebot/v11/ws closed, trying reconnecting... 

2024/3/2 18:19:57 : 反向ws断开 ws://127.0.0.1:8080/onebot/v11/ws 

```

**Comment by linyuchen** [comment]
重启QQ后依然存在这个问题吗

**Comment by PurpleNoon** [comment]
看到你的日志里有一条是 retry get self info，要不看看是不是个人资料没加载出来？今天刚碰到一次由于qq个人资料加载不出来导致机器人无法上线的问题
![image](https://github.com/LLOneBot/LLOneBot/assets/24586760/cd84fe6b-f511-4863-9443-7b58cb3176a1)

**Comment by WindraiteLesd** [comment]
> 重启QQ后依然存在这个问题吗

是的

**Comment by WindraiteLesd** [comment]
> 看到你的日志里有一条是 retry get self info，要不看看是不是个人资料没加载出来？今天刚碰到一次由于qq个人资料加载不出来导致机器人无法上线的问题
> ![image](https://github.com/LLOneBot/LLOneBot/assets/24586760/cd84fe6b-f511-4863-9443-7b58cb3176a1)
> 

并没有加载不出资料的问题，我记得这个标头在onebot里应该是指QQ号，但是我的账号那里可以看到QQ号

**Comment by PurpleNoon** [comment]
那看来和我的问题不是一个，我是之前个人资料页面只显示qq号，不显示其他信息，重新点击几次刷新后，显示全部资料后就正常了

**Comment by linyuchen** [comment]
[LLOneBot.zip](https://github.com/LLOneBot/LLOneBot/files/14469562/LLOneBot.zip)
你试一下这个，我把self info的日志输出了出来，看看获取到你的QQ号是不是正常的

**Comment by WindraiteLesd** [comment]
> [LLOneBot.zip](https://github.com/LLOneBot/LLOneBot/files/14469562/LLOneBot.zip) 你试一下这个，我把self info的日志输出了出来，看看获取到你的QQ号是不是正常的

get self simple info {"uid":"","uin":"","nick":"","online":true} 
直接获取不到

**Comment by linyuchen** [comment]
> > [LLOneBot.zip](https://github.com/LLOneBot/LLOneBot/files/14469562/LLOneBot.zip) 你试一下这个，我把self info的日志输出了出来，看看获取到你的QQ号是不是正常的
> 
> get self simple info {"uid":"","uin":"","nick":"","online":true} 直接获取不到

实在没法复现你的情况，要不你加[TG群](https://t.me/+nLZEnpne-pQ1OWFl)看一下或者把完整的日志发上来

**Comment by WindraiteLesd** [comment]
> > > [LLOneBot.zip](https://github.com/LLOneBot/LLOneBot/files/14469562/LLOneBot.zip) 你试一下这个，我把self info的日志输出了出来，看看获取到你的QQ号是不是正常的
> > 
> > get self simple info {"uid":"","uin":"","nick":"","online":true} 直接获取不到
> 
> 实在没法复现你的情况，要不你加[TG群](https://t.me/+nLZEnpne-pQ1OWFl)看一下或者把完整的日志发上来

日志里的报错就只有上面那一段在无限循环
