### ISSUE TITLE
语音消息长度显示异常

### ISSUE THREAD

**Issue by initialencounter** [LLOneBot/LLOneBot#99]
QQ版本：linuxqq_3.2.5-21453

LLOneBot版本：3.11.0

调用LLOneBot的方式或者应用端(如postman直接调用，或NoneBot2、Koishi)：koishi-plugin-adaptet-onebot

BUG描述：语音消息长度显示异常
![Screenshot_2024-03-02-18-27-57-18_9d26c6446fd7bb8e41d99b6262b17def.jpg](https://github.com/LLOneBot/LLOneBot/assets/109729945/36463ac6-bfe7-4a7a-a43d-223957f22a1b)
前两个 BOT 是 LLOnebot-API 的，实际语音长度只有两秒钟，这里显示的是2分钟

复现步骤：让 BOT 发送语音

LLOneBot日志:无

**Comment by linyuchen** [comment]
可以上传一下你发的语音原文件吗

**Comment by initialencounter** [comment]
这是语音文件[zhenxun.wav](http://121.37.247.122/zhenxun.wav)

**Comment by linyuchen** [comment]
> 这是语音文件[zhenxun.wav](http://121.37.247.122/zhenxun.wav)

正常的啊，没法复现你的情况，你是不是弄错了什么

**Comment by initialencounter** [comment]
> > 这是语音文件[zhenxun.wav](http://121.37.247.122/zhenxun.wav)
> 
> 正常的啊，没法复现你的情况，你是不是弄错了什么

不好意思，版本弄错了，LLOneBot 3.11.0是正常的
